/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_PANED_H
#define XTCW_PANED_H
#include <X11/Constraint.h>
_XFUNCPROTOBEGIN
#ifndef XtNtest
#define XtNtest "test"
#endif
#ifndef XtCTest
#define XtCTest "Test"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

typedef struct _PanedClassRec *PanedWidgetClass;
typedef struct _PanedRec *PanedWidget;
externalref WidgetClass panedWidgetClass;
_XFUNCPROTOEND
#endif /* XTCW_PANED_H */
