/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_WCOMBOP_H
#define XTCW_WCOMBOP_H
#include <xtcw/WlabelP.h>
#include <xtcw/Wcombo.h>
_XFUNCPROTOBEGIN
typedef void (*initialize_Proc)(
#if NeedFunctionPrototypes
void
#endif
);
#define XtInherit_initialize ((initialize_Proc) _XtInherit)
typedef void (*destroy_Proc)(
#if NeedFunctionPrototypes
void
#endif
);
#define XtInherit_destroy ((destroy_Proc) _XtInherit)

typedef struct {
/* methods */
initialize_Proc initialize;
destroy_Proc destroy;
/* class variables */
 visible_interest;
} WcomboClassPart;

typedef struct _WcomboClassRec {
WcomboClassPart wcombo_class;
} WcomboClassRec;

typedef struct {
/* resources */
XtCallbackList  combo_cb;
XtCallbackList  refresh_list;
StringMArray  lst;
int  selection;
int  lines_height;
/* private state */
Widget  shell;
Widget  listbox;
int  entry_mode;
int  filter;
int  f_lst;
int  k_lst;
} WcomboPart;

typedef struct _WcomboRec {
WcomboPart wcombo;
} WcomboRec;

externalref WcomboClassRec wcomboClassRec;

_XFUNCPROTOEND
#endif /* XTCW_WCOMBOP_H */
