/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_WLABEL_H
#define XTCW_WLABEL_H
#include <xtcw/Wheel.h>
_XFUNCPROTOBEGIN
#ifndef XtNlabel
#define XtNlabel "label"
#endif
#ifndef XtCLabel
#define XtCLabel "Label"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNfontFace
#define XtNfontFace "fontFace"
#endif
#ifndef XtCFontFace
#define XtCFontFace "FontFace"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNfontSize
#define XtNfontSize "fontSize"
#endif
#ifndef XtCFontSize
#define XtCFontSize "FontSize"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNcornerRoundPercent
#define XtNcornerRoundPercent "cornerRoundPercent"
#endif
#ifndef XtCCornerRoundPercent
#define XtCCornerRoundPercent "CornerRoundPercent"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNleftOffsetPercent
#define XtNleftOffsetPercent "leftOffsetPercent"
#endif
#ifndef XtCLeftOffsetPercent
#define XtCLeftOffsetPercent "LeftOffsetPercent"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNupdate
#define XtNupdate "update"
#endif
#ifndef XtCUpdate
#define XtCUpdate "Update"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNalignment
#define XtNalignment "alignment"
#endif
#ifndef XtCAlignment
#define XtCAlignment "Alignment"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

typedef struct _WlabelClassRec *WlabelWidgetClass;
typedef struct _WlabelRec *WlabelWidget;
externalref WidgetClass wlabelWidgetClass;
_XFUNCPROTOEND
#endif /* XTCW_WLABEL_H */
