/* Generated by wbuild from "XmATerm.w"
** (generator version $Revision: 3.0 $ of $Date: 95/08/30 17:50:38 $)
*/
#ifndef _XmAnsiTermP_H_
#define _XmAnsiTermP_H_
#include <Xm/PrimitiveP.h>
#include <Xfwf/XmATerm.h>
_XFUNCPROTOBEGIN
#define ATTRIB_BOLD (1 <<0 )


#define ATTRIB_REV (1 <<1 )


#define ATTRIB_ULINE (1 <<2 )


#define ATTRIB_INVIS (1 <<3 )


#define ATTRIB_DIRTY (1 <<7 )


#define Init 0 


#define Esc 1 


#define EscLB 2 


#define EscLBGT 3 


#define EscLBGT2 4 


#define Register0 5 


#define Register1 6 


#define Register2 7 


#define Register3 8 


#define Register4 9 


#define XtNnavigationType XmNnavigationType 


#define XtCNavigationType XmCNavigationType 


#define XtRNavigationType XmRNavigationType 


typedef void (*write_Proc)(
#if NeedFunctionPrototypes
Widget,char *,int 
#endif
);
#define XtInherit_write ((write_Proc) _XtInherit)

typedef struct {
/* methods */
write_Proc write;
/* class variables */
} XmAnsiTermClassPart;

typedef struct _XmAnsiTermClassRec {
CoreClassPart core_class;
XmPrimitiveClassPart xmPrimitive_class;
XmAnsiTermClassPart xmAnsiTerm_class;
} XmAnsiTermClassRec;

typedef struct {
/* resources */
int  rows;
int  columns;
String  font;
XFontStruct * boldfont;
int  margin;
XtCallbackList  keyCallback;
XtCallbackList  resizeCallback;
/* private state */
int  cellwidth;
int  cellheight;
int  uline_pos;
int  uline_thick;
XFontStruct * fnt;
GC  gc;
GC  boldgc;
GC  revgc;
GC  revboldgc;
char ** contents;
char ** attribs;
int  allocated_rows;
int  allocated_columns;
int  cursorx;
int  cursory;
int  old_cx;
int  old_cy;
int  savedx;
int  savedy;
Bool  cursor_on;
char  cur_attrib;
Bool  insert_mode;
char  last_char;
int  state;
int  escparm[5];
XtIntervalId  timer;
int  start_x;
int  start_y;
int  end_x;
int  end_y;
char * selection;
int  selection_len;
Bool  drag_started;
int  locked_lines;
} XmAnsiTermPart;

typedef struct _XmAnsiTermRec {
CorePart core;
XmPrimitivePart xmPrimitive;
XmAnsiTermPart xmAnsiTerm;
} XmAnsiTermRec;

externalref XmAnsiTermClassRec xmAnsiTermClassRec;

_XFUNCPROTOEND
#endif /* _XmAnsiTermP_H_ */
