/* Generated by wbuild from "VScrollb.w"
** (generator version $Revision: 3.0 $ of $Date: 95/08/30 17:50:38 $)
*/
#ifndef _XfwfVScrollbarP_H_
#define _XfwfVScrollbarP_H_
#include <Xfwf/ScrollbarP.h>
#include <Xfwf/VScrollb.h>
_XFUNCPROTOBEGIN

typedef struct {
/* methods */
/* class variables */
int dummy;
} XfwfVScrollbarClassPart;

typedef struct _XfwfVScrollbarClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
XfwfCommonClassPart xfwfCommon_class;
XfwfFrameClassPart xfwfFrame_class;
XfwfBoardClassPart xfwfBoard_class;
XfwfScrollbarClassPart xfwfScrollbar_class;
XfwfVScrollbarClassPart xfwfVScrollbar_class;
} XfwfVScrollbarClassRec;

typedef struct {
/* resources */
/* private state */
int dummy;
} XfwfVScrollbarPart;

typedef struct _XfwfVScrollbarRec {
CorePart core;
CompositePart composite;
XfwfCommonPart xfwfCommon;
XfwfFramePart xfwfFrame;
XfwfBoardPart xfwfBoard;
XfwfScrollbarPart xfwfScrollbar;
XfwfVScrollbarPart xfwfVScrollbar;
} XfwfVScrollbarRec;

externalref XfwfVScrollbarClassRec xfwfVScrollbarClassRec;

_XFUNCPROTOEND
#endif /* _XfwfVScrollbarP_H_ */
