/* Generated by wbuild
 * (generator version 3.3)
 */
#include <X11/IntrinsicP.h>
#include <X11/StringDefs.h>
#line 87 "SmeLine2.widget"
#include <X11/Xaw/SmeP.h>
#include <xtcw/SmeLine2P.h>
static void _resolve_inheritance(
#if NeedFunctionPrototypes
WidgetClass
#endif
);
#line 17 "SmeLine2.widget"
static void initialize(
#if NeedFunctionPrototypes
Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 23 "SmeLine2.widget"
static void destroy(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 28 "SmeLine2.widget"
static Boolean  set_values(
#if NeedFunctionPrototypes
Widget ,Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 41 "SmeLine2.widget"
static void expose(
#if NeedFunctionPrototypes
Widget,XEvent *,Region 
#endif
);
#line 55 "SmeLine2.widget"
static void DestroyGC(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 64 "SmeLine2.widget"
static void CreateGC(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 55 "SmeLine2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 55 "SmeLine2.widget"
static void DestroyGC(Widget self)
#else
#line 55 "SmeLine2.widget"
static void DestroyGC(self)Widget self;
#endif
#line 56 "SmeLine2.widget"
{
    if (((SmeLine2Widget)self)->smeLine2.stipple != XtUnspecifiedPixmap)
        XFreeGC(XtDisplayOfObject(self), ((SmeLine2Widget)self)->smeLine2.gc);
    else
        XtReleaseGC(self, ((SmeLine2Widget)self)->smeLine2.gc);
}
#line 64 "SmeLine2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 64 "SmeLine2.widget"
static void CreateGC(Widget self)
#else
#line 64 "SmeLine2.widget"
static void CreateGC(self)Widget self;
#endif
#line 65 "SmeLine2.widget"
{
    XGCValues values;
    XtGCMask mask = GCForeground | GCGraphicsExposures | GCLineWidth;

    values.foreground = ((SmeLine2Widget)self)->smeLine2.foreground;
    values.graphics_exposures = False;
    values.line_width = ((SmeLine2Widget)self)->smeLine2.line_width;

    if (((SmeLine2Widget)self)->smeLine2.stipple != XtUnspecifiedPixmap) {
        values.stipple = ((SmeLine2Widget)self)->smeLine2.stipple;
        values.fill_style = FillStippled;
        mask |= GCStipple | GCFillStyle;

         ((SmeLine2Widget)self)->smeLine2.gc = XCreateGC(XtDisplayOfObject(self),
                                      RootWindowOfScreen(XtScreenOfObject(self)),
                                      mask, &values);
    }
    else
        ((SmeLine2Widget)self)->smeLine2.gc = XtGetGC(self, mask, &values);
}

static XtResource resources[] = {
#line 4 "SmeLine2.widget"
{XtNline_width,XtCLine_width,XtRDimension,sizeof(((SmeLine2Rec*)NULL)->smeLine2.line_width),XtOffsetOf(SmeLine2Rec,smeLine2.line_width),XtRImmediate,(XtPointer)1 },
#line 5 "SmeLine2.widget"
{XtNstipple,XtCStipple,XtRPixmap,sizeof(((SmeLine2Rec*)NULL)->smeLine2.stipple),XtOffsetOf(SmeLine2Rec,smeLine2.stipple),XtRImmediate,(XtPointer)XtUnspecifiedPixmap },
#line 6 "SmeLine2.widget"
{XtNforeground,XtCForeground,XtRPixel,sizeof(((SmeLine2Rec*)NULL)->smeLine2.foreground),XtOffsetOf(SmeLine2Rec,smeLine2.foreground),XtRImmediate,(XtPointer)0 },
};

SmeLine2ClassRec smeLine2ClassRec = {
{ /* core_class part */
/* superclass   	*/  (WidgetClass) &smeClassRec,
/* class_name   	*/  "SmeLine2",
/* widget_size  	*/  sizeof(SmeLine2Rec),
/* class_initialize 	*/  NULL,
/* class_part_initialize*/  _resolve_inheritance,
/* class_inited 	*/  FALSE,
/* initialize   	*/  initialize,
/* initialize_hook 	*/  NULL,
/* realize      	*/  XtInheritRealize,
/* actions      	*/  NULL,
/* num_actions  	*/  0,
/* resources    	*/  resources,
/* num_resources 	*/  3,
/* xrm_class    	*/  NULLQUARK,
/* compres_motion 	*/  False ,
/* compress_exposure 	*/  FALSE ,
/* compress_enterleave 	*/  False ,
/* visible_interest 	*/  False ,
/* destroy      	*/  destroy,
/* resize       	*/  XtInheritResize,
/* expose       	*/  expose,
/* set_values   	*/  set_values,
/* set_values_hook 	*/  NULL,
/* set_values_almost 	*/  XtInheritSetValuesAlmost,
/* get_values+hook 	*/  NULL,
/* accept_focus 	*/  XtInheritAcceptFocus,
/* version      	*/  XtVersion,
/* callback_private 	*/  NULL,
/* tm_table      	*/  XtInheritTranslations,
/* query_geometry 	*/  XtInheritQueryGeometry,
/* display_acceleator 	*/  XtInheritDisplayAccelerator,
/* extension    	*/  NULL 
},
{ /* Sme_class part */
XtInherit_highlight,
XtInherit_unhighlight,
XtInherit_notify,
},
{ /* SmeLine2_class part */
 /* dummy */  0
},
};
WidgetClass smeLine2WidgetClass = (WidgetClass) &smeLine2ClassRec;
static void _resolve_inheritance(class)
WidgetClass class;
{
  SmeLine2WidgetClass c __attribute__((unused)) = (SmeLine2WidgetClass) class;
  SmeLine2WidgetClass super __attribute__((unused));
  if (class == smeLine2WidgetClass) return;
  super = (SmeLine2WidgetClass)class->core_class.superclass;
}
#line 17 "SmeLine2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 17 "SmeLine2.widget"
static void initialize(Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 17 "SmeLine2.widget"
static void initialize(request,self,args,num_args)Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 18 "SmeLine2.widget"
{
   if (((SmeLine2Widget)self)->core.height == 0) ((SmeLine2Widget)self)->core.height = ((SmeLine2Widget)self)->smeLine2.line_width;
   CreateGC(self);
}
#line 23 "SmeLine2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 23 "SmeLine2.widget"
static void destroy(Widget self)
#else
#line 23 "SmeLine2.widget"
static void destroy(self)Widget self;
#endif
#line 24 "SmeLine2.widget"
{
    DestroyGC(self);
}
#line 28 "SmeLine2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 28 "SmeLine2.widget"
static Boolean  set_values(Widget  old,Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 28 "SmeLine2.widget"
static Boolean  set_values(old,request,self,args,num_args)Widget  old;Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 29 "SmeLine2.widget"
{
    if (((SmeLine2Widget)self)->smeLine2.line_width != ((SmeLine2Widget)old)->smeLine2.line_width &&
        ((SmeLine2Widget)self)->smeLine2.stipple != ((SmeLine2Widget)old)->smeLine2.stipple) {
        DestroyGC(old);
        CreateGC(self);
        return (True);
    }

    return (False);
}
#line 41 "SmeLine2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 41 "SmeLine2.widget"
static void expose(Widget self,XEvent * event,Region  region)
#else
#line 41 "SmeLine2.widget"
static void expose(self,event,region)Widget self;XEvent * event;Region  region;
#endif
#line 42 "SmeLine2.widget"
{
     int y = ((SmeLine2Widget)self)->core.y  + ( ((int)((SmeLine2Widget)self)->core.height - ((SmeLine2Widget)self)->smeLine2.line_width) >> 1 );

        if (((SmeLine2Widget)self)->smeLine2.stipple != XtUnspecifiedPixmap)
                XSetTSOrigin(XtDisplayOfObject(self), ((SmeLine2Widget)self)->smeLine2.gc, 0, y);

        XFillRectangle(XtDisplayOfObject(self), XtWindowOfObject(self),
                   ((SmeLine2Widget)self)->smeLine2.gc, ((SmeLine2Widget)self)->core.x, y,
                   ((SmeLine2Widget)self)->core.width, ((SmeLine2Widget)self)->smeLine2.line_width );
}
#line 12 "SmeLine2.widget"
#line 13 "SmeLine2.widget"
#line 14 "SmeLine2.widget"
