/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_KAROED_H
#define XTCW_KAROED_H
#include <xtcw/Wheel.h>
_XFUNCPROTOBEGIN
typedef enum {
  KEDIT_INSERT = 0,
  KEDIT_REMOVE,
  KEDIT_SPLIT,
  KEDIT_JOIN,
  KEDIT_PASTE,
  KEDIT_REPLACE,
  KEDIT_LOAD
} edit_kind;

void  karoEd_writeln(
#if NeedFunctionPrototypes
Widget ,char *
#endif
);
char * karoEd_get_text(
#if NeedFunctionPrototypes
Widget 
#endif
);
#ifndef XtNlocked
#define XtNlocked "locked"
#endif
#ifndef XtCLocked
#define XtCLocked "Locked"
#endif
#ifndef XtRBool
#define XtRBool "Bool"
#endif

#ifndef XtNlines
#define XtNlines "lines"
#endif
#ifndef XtCLines
#define XtCLines "Lines"
#endif
#ifndef XtRStringMArray
#define XtRStringMArray "StringMArray"
#endif

#ifndef XtNmin_lines
#define XtNmin_lines "min_lines"
#endif
#ifndef XtCMin_lines
#define XtCMin_lines "Min_lines"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNgrid_width
#define XtNgrid_width "grid_width"
#endif
#ifndef XtCGrid_width
#define XtCGrid_width "Grid_width"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNgrid_height
#define XtNgrid_height "grid_height"
#endif
#ifndef XtCGrid_height
#define XtCGrid_height "Grid_height"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNauto_resize
#define XtNauto_resize "auto_resize"
#endif
#ifndef XtCAuto_resize
#define XtCAuto_resize "Auto_resize"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNfileForm
#define XtNfileForm "fileForm"
#endif
#ifndef XtCFileForm
#define XtCFileForm "FileForm"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

typedef struct _KaroEdClassRec *KaroEdWidgetClass;
typedef struct _KaroEdRec *KaroEdWidget;
externalref WidgetClass karoEdWidgetClass;
_XFUNCPROTOEND
#endif /* XTCW_KAROED_H */
