/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_CLIPVIEWP_H
#define XTCW_CLIPVIEWP_H
#include <xtcw/WheelP.h>
#include <xtcw/ClipView.h>
_XFUNCPROTOBEGIN

typedef struct {
/* methods */
/* class variables */
Atom  XA_UTF8_STRING;
} ClipViewClassPart;

typedef struct _ClipViewClassRec {
CoreClassPart core_class;
WheelClassPart wheel_class;
ClipViewClassPart clipView_class;
} ClipViewClassRec;

typedef struct {
/* resources */
String  text;
int  cornerRoundPercent;
int  timer;
/* private state */
XftDraw * draw;
Pixmap  pixmap;
GC  gc_copy;
int  prefered_width;
int  prefered_height;
int  mk_display;
XtIntervalId  tmr;
} ClipViewPart;

typedef struct _ClipViewRec {
CorePart core;
WheelPart wheel;
ClipViewPart clipView;
} ClipViewRec;

externalref ClipViewClassRec clipViewClassRec;

_XFUNCPROTOEND
#endif /* XTCW_CLIPVIEWP_H */
