/* Generated by wbuild from "Slider4.w"
** (generator version $Revision: 3.0 $ of $Date: 95/08/30 17:50:38 $)
*/
#ifndef _XfwfSlider4_H_
#define _XfwfSlider4_H_
#include <Xfwf/Slider2.h>
_XFUNCPROTOBEGIN
#ifndef XtNsashColor
#define XtNsashColor "sashColor"
#endif
#ifndef XtCSashColor
#define XtCSashColor "SashColor"
#endif
#ifndef XtRColor
#define XtRColor "Color"
#endif

#ifndef XtNsashPixmap
#define XtNsashPixmap "sashPixmap"
#endif
#ifndef XtCSashPixmap
#define XtCSashPixmap "SashPixmap"
#endif
#ifndef XtRPixmap
#define XtRPixmap "Pixmap"
#endif

#ifndef XtNsashFrameType
#define XtNsashFrameType "sashFrameType"
#endif
#ifndef XtCSashFrameType
#define XtCSashFrameType "SashFrameType"
#endif
#ifndef XtRFrameType
#define XtRFrameType "FrameType"
#endif

#ifndef XtNsashFrameWidth
#define XtNsashFrameWidth "sashFrameWidth"
#endif
#ifndef XtCSashFrameWidth
#define XtCSashFrameWidth "SashFrameWidth"
#endif
#ifndef XtRDimension
#define XtRDimension "Dimension"
#endif

typedef struct _XfwfSlider4ClassRec *XfwfSlider4WidgetClass;
typedef struct _XfwfSlider4Rec *XfwfSlider4Widget;
externalref WidgetClass xfwfSlider4WidgetClass;
_XFUNCPROTOEND
#endif /*_XfwfSlider4_H_*/
