/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_WTEXT2_H
#define XTCW_WTEXT2_H
#include <xtcw/Wheel.h>
_XFUNCPROTOBEGIN
#ifndef XtNlabel
#define XtNlabel "label"
#endif
#ifndef XtCLabel
#define XtCLabel "Label"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNcornerRoundPercent
#define XtNcornerRoundPercent "cornerRoundPercent"
#endif
#ifndef XtCCornerRoundPercent
#define XtCCornerRoundPercent "CornerRoundPercent"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNtimer
#define XtNtimer "timer"
#endif
#ifndef XtCTimer
#define XtCTimer "Timer"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

typedef struct _Wtext2ClassRec *Wtext2WidgetClass;
typedef struct _Wtext2Rec *Wtext2Widget;
externalref WidgetClass wtext2WidgetClass;
_XFUNCPROTOEND
#endif /* XTCW_WTEXT2_H */
