.TH "Slider2T" "1" "28 Aug 1992" "Version 3.0" "Free Widget Foundation"
.SH NAME
Slider2T \- Test program for the XfwfSlider2 widget
.SH DESCRIPTION
.PP
The program opens a window with a large, insensitive slider on the
left, a small slider in the bottom right corner and a label in he top
right corner. When the small thumb is dragged with the mouse, the
large one is moved proportionally also. Clicking the mouse next to the
thumb will cause both thumbs to jump in that direction. The label
shows the current position.
.SH AUTHOR
.sp
.nf
Bert Bos <bert@let.rug.nl>
Alfa-informatica, Rijksuniversiteit Groningen,
Groningen,
The Netherlands
.fi





