/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_WDEMO2_H
#define XTCW_WDEMO2_H
#include <X11/Core.h>
_XFUNCPROTOBEGIN
#ifndef XtNxftFont
#define XtNxftFont "xftFont"
#endif
#ifndef XtCXFtFont
#define XtCXFtFont "XFtFont"
#endif
#ifndef XtRXftFont
#define XtRXftFont "XftFont"
#endif

#ifndef XtNforeground
#define XtNforeground "foreground"
#endif
#ifndef XtCForeground
#define XtCForeground "Foreground"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNlabel
#define XtNlabel "label"
#endif
#ifndef XtCLabel
#define XtCLabel "Label"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

typedef struct _Wdemo2ClassRec *Wdemo2WidgetClass;
typedef struct _Wdemo2Rec *Wdemo2Widget;
externalref WidgetClass wdemo2WidgetClass;
_XFUNCPROTOEND
#endif /* XTCW_WDEMO2_H */
