/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_WDEMO3_H
#define XTCW_WDEMO3_H
#include <xtcw/Wlabel.h>
_XFUNCPROTOBEGIN
typedef struct _Wdemo3ClassRec *Wdemo3WidgetClass;
typedef struct _Wdemo3Rec *Wdemo3Widget;
externalref WidgetClass wdemo3WidgetClass;
_XFUNCPROTOEND
#endif /* XTCW_WDEMO3_H */
