/* Generated by wbuild from "Rows.w"
** (generator version $Revision: 3.0 $ of $Date: 95/08/30 17:50:38 $)
*/
#include <X11/IntrinsicP.h>
#include <X11/StringDefs.h>
#include <Xfwf/RowsP.h>
static void _resolve_inheritance(
#if NeedFunctionPrototypes
WidgetClass
#endif
);
#line 34 "Rows.w"
static void change_managed(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 43 "Rows.w"
static void layout(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 86 "Rows.w"
static XtGeometryResult  geometry_manager(
#if NeedFunctionPrototypes
Widget ,XtWidgetGeometry *,XtWidgetGeometry *
#endif
);
#line 111 "Rows.w"
static void resize(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 121 "Rows.w"
static Boolean  set_values(
#if NeedFunctionPrototypes
Widget ,Widget ,Widget,ArgList ,Cardinal *
#endif
);

static XtResource resources[] = {
#line 19 "Rows.w"
{XtNalignTop,XtCAlignTop,XtRBoolean,sizeof(((XfwfRowsRec*)NULL)->xfwfRows.alignTop),XtOffsetOf(XfwfRowsRec,xfwfRows.alignTop),XtRImmediate,(XtPointer)True },
#line 25 "Rows.w"
{XtNframeType,XtCFrameType,XtRFrameType,sizeof(((XfwfRowsRec*)NULL)->xfwfFrame.frameType),XtOffsetOf(XfwfRowsRec,xfwfFrame.frameType),XtRImmediate,(XtPointer)XfwfSunken },
#line 26 "Rows.w"
{XtNframeWidth,XtCFrameWidth,XtRDimension,sizeof(((XfwfRowsRec*)NULL)->xfwfFrame.frameWidth),XtOffsetOf(XfwfRowsRec,xfwfFrame.frameWidth),XtRImmediate,(XtPointer)2 },
};

XfwfRowsClassRec xfwfRowsClassRec = {
{ /* core_class part */
/* superclass   	*/  (WidgetClass) &xfwfBoardClassRec,
/* class_name   	*/  "XfwfRows",
/* widget_size  	*/  sizeof(XfwfRowsRec),
/* class_initialize 	*/  NULL,
/* class_part_initialize*/  _resolve_inheritance,
/* class_inited 	*/  FALSE,
/* initialize   	*/  NULL,
/* initialize_hook 	*/  NULL,
/* realize      	*/  XtInheritRealize,
/* actions      	*/  NULL,
/* num_actions  	*/  0,
/* resources    	*/  resources,
/* num_resources 	*/  3,
/* xrm_class    	*/  NULLQUARK,
/* compres_motion 	*/  True ,
/* compress_exposure 	*/  XtExposeCompressMultiple ,
/* compress_enterleave 	*/  True ,
/* visible_interest 	*/  TRUE ,
/* destroy      	*/  NULL,
/* resize       	*/  resize,
/* expose       	*/  XtInheritExpose,
/* set_values   	*/  set_values,
/* set_values_hook 	*/  NULL,
/* set_values_almost 	*/  XtInheritSetValuesAlmost,
/* get_values+hook 	*/  NULL,
/* accept_focus 	*/  XtInheritAcceptFocus,
/* version      	*/  XtVersion,
/* callback_private 	*/  NULL,
/* tm_table      	*/  NULL,
/* query_geometry 	*/  XtInheritQueryGeometry,
/* display_acceleator 	*/  XtInheritDisplayAccelerator,
/* extension    	*/  NULL 
},
{ /* composite_class part */
geometry_manager,
change_managed,
XtInheritInsertChild,
XtInheritDeleteChild,
NULL
},
{ /* XfwfCommon_class part */
XtInherit_compute_inside,
XtInherit_total_frame_width,
XtInherit_highlight_border,
XtInherit_unhighlight_border,
XtInherit_would_accept_focus,
XtInherit_traverse,
XtInherit_lighter_color,
XtInherit_darker_color,
/* traversal_trans */  NULL ,
},
{ /* XfwfFrame_class part */
 /* dummy */  0
},
{ /* XfwfBoard_class part */
XtInherit_set_abs_location,
},
{ /* XfwfRows_class part */
layout,
},
};
WidgetClass xfwfRowsWidgetClass = (WidgetClass) &xfwfRowsClassRec;
static void _resolve_inheritance(class)
WidgetClass class;
{
  XfwfRowsWidgetClass c = (XfwfRowsWidgetClass) class;
  XfwfRowsWidgetClass super;
  static CompositeClassExtensionRec extension_rec = {
    NULL, NULLQUARK, XtCompositeExtensionVersion,
    sizeof(CompositeClassExtensionRec), True};
  CompositeClassExtensionRec *ext;
  ext = (XtPointer)XtMalloc(sizeof(*ext));
  *ext = extension_rec;
  ext->next_extension = c->composite_class.extension;
  c->composite_class.extension = ext;
  if (class == xfwfRowsWidgetClass) return;
  super = (XfwfRowsWidgetClass)class->core_class.superclass;
  if (c->xfwfRows_class.layout == XtInherit_layout)
    c->xfwfRows_class.layout = super->xfwfRows_class.layout;
}
#line 34 "Rows.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 34 "Rows.w"
static void change_managed(Widget self)
#else
#line 34 "Rows.w"
static void change_managed(self)Widget self;
#endif
#line 35 "Rows.w"
{
    ((XfwfRowsWidgetClass)self->core.widget_class)->xfwfRows_class.layout(self);
}
#line 43 "Rows.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 43 "Rows.w"
static void layout(Widget self)
#else
#line 43 "Rows.w"
static void layout(self)Widget self;
#endif
#line 44 "Rows.w"
{
    Position top, left, x, y;
    Dimension width, height, w, maxht;
    int i, j;
    Widget child;

    ((XfwfRowsWidgetClass)self->core.widget_class)->xfwfCommon_class.compute_inside(self, &left, &top, &width, &height);
    y = top;
    i = 0;
    while (i < ((XfwfRowsWidget)self)->composite.num_children) {
	child = ((XfwfRowsWidget)self)->composite.children[i];
	w = ((XfwfRowsWidget)child)->core.width;			/* Accumulated width */
	maxht = ((XfwfRowsWidget)child)->core.height;			/* Max. height in this row */
	j = i + 1;
	do {
	    if (j >= ((XfwfRowsWidget)self)->composite.num_children) break;
	    child = ((XfwfRowsWidget)self)->composite.children[j];
	    if (w + ((XfwfRowsWidget)child)->core.width > width) break;
	    w += ((XfwfRowsWidget)child)->core.width;
	    if (((XfwfRowsWidget)child)->core.height > maxht) maxht = ((XfwfRowsWidget)child)->core.height;
	    j++;
	} while (1);
	for (x = left; i < j; i++) {
	    child = ((XfwfRowsWidget)self)->composite.children[i];
	    if (((XfwfRowsWidget)self)->xfwfRows.alignTop)
		XtMoveWidget(child, x, y);
	    else
		XtMoveWidget(child, x, y + maxht - ((XfwfRowsWidget)child)->core.height);
	    x += ((XfwfRowsWidget)child)->core.width;
	}
	y += maxht;
    }
}
#line 86 "Rows.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 167 "Rows.w"
static XtGeometryResult  geometry_manager(Widget  child,XtWidgetGeometry * request,XtWidgetGeometry * reply)
#else
#line 167 "Rows.w"
static XtGeometryResult  geometry_manager(child,request,reply)Widget  child;XtWidgetGeometry * request;XtWidgetGeometry * reply;
#endif
{ Widget self = XtParent(child); {
    Dimension newwd, newht, newbd;

    if (request->request_mode & (CWX | CWY)) return XtGeometryNo;
    if (request->request_mode & XtCWQueryOnly) return XtGeometryYes;

    newwd = request->request_mode & CWWidth ? request->width : ((XfwfRowsWidget)child)->core.width;
    newht = request->request_mode & CWHeight ? request->height : ((XfwfRowsWidget)child)->core.height;
    newbd = request->request_mode & CWBorderWidth
	? request->border_width : ((XfwfRowsWidget)child)->core.border_width;

    if (newwd == ((XfwfRowsWidget)child)->core.width && newht == ((XfwfRowsWidget)child)->core.height
	&& newbd == ((XfwfRowsWidget)child)->core.border_width) return XtGeometryNo;

    XtResizeWidget(child, newwd, newht, newbd);
    ((XfwfRowsWidgetClass)self->core.widget_class)->xfwfRows_class.layout(self);
    return XtGeometryDone;
}
}
#line 111 "Rows.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 111 "Rows.w"
static void resize(Widget self)
#else
#line 111 "Rows.w"
static void resize(self)Widget self;
#endif
#line 112 "Rows.w"
{
    ((XfwfRowsWidgetClass)self->core.widget_class)->xfwfRows_class.layout(self);
}
#line 121 "Rows.w"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 121 "Rows.w"
static Boolean  set_values(Widget  old,Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 121 "Rows.w"
static Boolean  set_values(old,request,self,args,num_args)Widget  old;Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 122 "Rows.w"
{
    Boolean need_layout = False;
    Boolean need_redisplay = False;

    if (((XfwfRowsWidget)old)->xfwfRows.alignTop != ((XfwfRowsWidget)self)->xfwfRows.alignTop) {
	need_layout = True;
    }
    if (need_layout) {
	((XfwfRowsWidgetClass)self->core.widget_class)->xfwfRows_class.layout(self);
	need_redisplay = True;
    }
    return need_redisplay;
}
