/* Generated by wbuild
 * (generator version 3.3)
 */
#include <X11/IntrinsicP.h>
#include <X11/StringDefs.h>
#line 53 "Repeatgb.widget"
#include <X11/Xatom.h>
#line 54 "Repeatgb.widget"
#include <X11/Xft/Xft.h>
#line 55 "Repeatgb.widget"
#include "converters-xft.h"
#line 56 "Repeatgb.widget"
#include "converters.h"
#line 57 "Repeatgb.widget"
#include <X11/Xmu/Converters.h>
#line 58 "Repeatgb.widget"
#include "mls.h"
#line 59 "Repeatgb.widget"
#include "xutil.h"
#line 60 "Repeatgb.widget"
#include <X11/Xaw/Command.h>
#line 61 "Repeatgb.widget"
#include "xtcw/Wlabel.h"
#line 62 "Repeatgb.widget"
#include "repeatergb-tool.h"
#include <xtcw/RepeatgbP.h>
static void _resolve_inheritance(
#if NeedFunctionPrototypes
WidgetClass
#endif
);
#line 14 "Repeatgb.widget"
static void realize(
#if NeedFunctionPrototypes
Widget,XtValueMask *,XSetWindowAttributes *
#endif
);
#line 25 "Repeatgb.widget"
static void add_widgets(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 25 "Repeatgb.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 25 "Repeatgb.widget"
static void add_widgets(Widget self)
#else
#line 25 "Repeatgb.widget"
static void add_widgets(self)Widget self;
#endif
#line 26 "Repeatgb.widget"
{
  XTFUNC();
/*
	Widget btn;
  btn = XtVaCreateManagedWidget( "txt", wlabelWidgetClass, $,
                                  "gridy", 0,
                                  "gridx", 1,
                                  "fill", 3,
                                  "weighty", 10,
                                  "weightx", 70,
				  "gridWidth", 1,
				  "gridHeight", 1,
				  "label", "@s;Hello World",
				  "borderWidth", 0,
				  "gravity", CenterGravity,
				  XtVaTypedArg, "xftFont", XtRString, "Sans-45", strlen("Sans-45") + 1,			  
				 
                                  NULL );
*/

  repgb_parse( self, ((RepeatgbWidget)self)->repeatgb.args, ((RepeatgbWidget)self)->repeatgb.count );
}

static XtResource resources[] = {
#line 6 "Repeatgb.widget"
{XtNsensor,XtCSensor,XtRString,sizeof(((RepeatgbRec*)NULL)->repeatgb.sensor),XtOffsetOf(RepeatgbRec,repeatgb.sensor),XtRString,(XtPointer)"Repeatgb-DEFAULT-SENSOR"},
#line 7 "Repeatgb.widget"
{XtNcount,XtCCount,XtRString,sizeof(((RepeatgbRec*)NULL)->repeatgb.count),XtOffsetOf(RepeatgbRec,repeatgb.count),XtRString,(XtPointer)"Repeatgb-DEFAULT-COUNT"},
#line 8 "Repeatgb.widget"
{XtNargs,XtCArgs,XtRString,sizeof(((RepeatgbRec*)NULL)->repeatgb.args),XtOffsetOf(RepeatgbRec,repeatgb.args),XtRString,(XtPointer)"Repeatgb-DEFAULT-ARGS"},
};

RepeatgbClassRec repeatgbClassRec = {
{ /* core_class part */
/* superclass   	*/  (WidgetClass) &gridboxClassRec,
/* class_name   	*/  "Repeatgb",
/* widget_size  	*/  sizeof(RepeatgbRec),
/* class_initialize 	*/  NULL,
/* class_part_initialize*/  _resolve_inheritance,
/* class_inited 	*/  FALSE,
/* initialize   	*/  NULL,
/* initialize_hook 	*/  NULL,
/* realize      	*/  realize,
/* actions      	*/  NULL,
/* num_actions  	*/  0,
/* resources    	*/  resources,
/* num_resources 	*/  3,
/* xrm_class    	*/  NULLQUARK,
/* compres_motion 	*/  False ,
/* compress_exposure 	*/  FALSE ,
/* compress_enterleave 	*/  False ,
/* visible_interest 	*/  False ,
/* destroy      	*/  NULL,
/* resize       	*/  XtInheritResize,
/* expose       	*/  XtInheritExpose,
/* set_values   	*/  NULL,
/* set_values_hook 	*/  NULL,
/* set_values_almost 	*/  XtInheritSetValuesAlmost,
/* get_values+hook 	*/  NULL,
/* accept_focus 	*/  XtInheritAcceptFocus,
/* version      	*/  XtVersion,
/* callback_private 	*/  NULL,
/* tm_table      	*/  XtInheritTranslations,
/* query_geometry 	*/  XtInheritQueryGeometry,
/* display_acceleator 	*/  XtInheritDisplayAccelerator,
/* extension    	*/  NULL 
},
{ /* composite_class part */
XtInheritGeometryManager,
XtInheritChangeManaged,
XtInheritInsertChild,
XtInheritDeleteChild,
NULL
},
{ /* constraint_class part */
/* constraint_resources     */  NULL,
/* num_constraint_resources */  0,
/* constraint_size          */  sizeof(RepeatgbConstraintRec),
/* constraint_initialize    */  NULL,
/* constraint_destroy       */  NULL,
/* constraint_set_values    */  NULL,
/* constraint_extension     */  NULL 
},
{ /* Gridbox_class part */
 /* dummy */  0
},
{ /* Repeatgb_class part */
 /* dummy */  0
},
};
WidgetClass repeatgbWidgetClass = (WidgetClass) &repeatgbClassRec;
static void _resolve_inheritance(class)
WidgetClass class;
{
  RepeatgbWidgetClass c __attribute__((unused)) = (RepeatgbWidgetClass) class;
  RepeatgbWidgetClass super __attribute__((unused));
  static CompositeClassExtensionRec extension_rec = {
    NULL, NULLQUARK, XtCompositeExtensionVersion,
    sizeof(CompositeClassExtensionRec), True};
  CompositeClassExtensionRec *ext;
  ext = (XtPointer)XtMalloc(sizeof(*ext));
  *ext = extension_rec;
  ext->next_extension = c->composite_class.extension;
  c->composite_class.extension = ext;
  if (class == repeatgbWidgetClass) return;
  super = (RepeatgbWidgetClass)class->core_class.superclass;
}
#line 14 "Repeatgb.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 14 "Repeatgb.widget"
static void realize(Widget self,XtValueMask * mask,XSetWindowAttributes * attributes)
#else
#line 14 "Repeatgb.widget"
static void realize(self,mask,attributes)Widget self;XtValueMask * mask;XSetWindowAttributes * attributes;
#endif
#line 15 "Repeatgb.widget"
{
    XTFUNC();
    XtVaSetValues( self, "borderWidth", 0, NULL );
    gridboxClassRec.core_class.realize(self,mask,attributes);
    add_widgets(self);
   
}
