/* Generated by wbuild from "Alert.w"
** (generator version $Revision: 3.0 $ of $Date: 95/08/30 17:50:38 $)
*/
#ifndef _XfwfAlert_H_
#define _XfwfAlert_H_
#include <X11/Shell.h>
_XFUNCPROTOBEGIN
#define max(a, b) ((a )>(b )?(a ):(b ))


#define min(a, b) ((a )<(b )?(a ):(b ))


int  XfwfDialog(
#if NeedFunctionPrototypes
String ,Widget ,String ,String ,String 
#endif
);
#ifndef XtNicon
#define XtNicon "icon"
#endif
#ifndef XtCIcon
#define XtCIcon "Icon"
#endif
#ifndef XtRIcon
#define XtRIcon "Icon"
#endif

#ifndef XtNmessage
#define XtNmessage "message"
#endif
#ifndef XtCMessage
#define XtCMessage "Message"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNbuttons
#define XtNbuttons "buttons"
#endif
#ifndef XtCButtons
#define XtCButtons "Buttons"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNlastChoice
#define XtNlastChoice "lastChoice"
#endif
#ifndef XtCLastChoice
#define XtCLastChoice "LastChoice"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNcallback
#define XtNcallback "callback"
#endif
#ifndef XtCCallback
#define XtCCallback "Callback"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

typedef struct _XfwfAlertClassRec *XfwfAlertWidgetClass;
typedef struct _XfwfAlertRec *XfwfAlertWidget;
externalref WidgetClass xfwfAlertWidgetClass;
_XFUNCPROTOEND
#endif /*_XfwfAlert_H_*/
