/* Generated by wbuild from "OptButton.w"
** (generator version $Revision: 3.0 $ of $Date: 95/08/30 17:50:38 $)
*/
#ifndef _XfwfOptionButton_H_
#define _XfwfOptionButton_H_
#include <Xfwf/PullDown.h>
_XFUNCPROTOBEGIN
typedef struct _XfwfOptionButtonClassRec *XfwfOptionButtonWidgetClass;
typedef struct _XfwfOptionButtonRec *XfwfOptionButtonWidget;
externalref WidgetClass xfwfOptionButtonWidgetClass;
_XFUNCPROTOEND
#endif /*_XfwfOptionButton_H_*/
