/* Generated by wbuild
 * (generator version 3.3)
 */
#include <X11/IntrinsicP.h>
#include <X11/StringDefs.h>
#line 84 "MessageBox.widget"
#include <X11/Xatom.h>
#line 85 "MessageBox.widget"
#include <X11/Xft/Xft.h>
#line 86 "MessageBox.widget"
#include "converters-xft.h"
#line 87 "MessageBox.widget"
#include "converters.h"
#line 88 "MessageBox.widget"
#include <X11/Xmu/Converters.h>
#line 89 "MessageBox.widget"
#include "mls.h"
#line 90 "MessageBox.widget"
#include "xutil.h"
#line 91 "MessageBox.widget"
#include <X11/Xaw/Command.h>
#line 92 "MessageBox.widget"
#include "xtcw/Wbutton.h"
#line 93 "MessageBox.widget"
#include "xtcw/IconSVG.h"
#line 94 "MessageBox.widget"
#include "xtcw/Wtext.h"
#include <xtcw/MessageBoxP.h>
static void _resolve_inheritance(
#if NeedFunctionPrototypes
WidgetClass
#endif
);
#line 13 "MessageBox.widget"
static void realize(
#if NeedFunctionPrototypes
Widget,XtValueMask *,XSetWindowAttributes *
#endif
);
#line 24 "MessageBox.widget"
static void add_widgets(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 76 "MessageBox.widget"
static void btn_close_cb(
#if NeedFunctionPrototypes
Widget ,Widget,void *
#endif
);
#line 24 "MessageBox.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 24 "MessageBox.widget"
static void add_widgets(Widget self)
#else
#line 24 "MessageBox.widget"
static void add_widgets(self)Widget self;
#endif
#line 25 "MessageBox.widget"
{
  XTFUNC();

  Widget btn;
  btn = XtVaCreateManagedWidget( "txt", wtextWidgetClass, self,
                                  "gridy", 0,
                                  "gridx", 1,
                                  "fill", 3,
                                  "weighty", 10,
                                  "weightx", 70,
				  "gridWidth", 1,
				  "gridHeight", 1,
				  "label", "@s;Hello World",
				   "borderWidth", 0,
				   "gravity", CenterGravity,
                                  NULL );



  btn = XtVaCreateManagedWidget( "icon", iconSVGWidgetClass, self,
                                  "gridy", 0,
                                  "gridx", 0,
                                  "fill", 0,
                                  "weighty", 1,
                                  "weightx", 1,
				  "gridWidth", 1,
				  "gridHeight", 1,
				  "filename", "question.svg",
				  "borderWidth", 0,
	XtVaTypedArg, "forced_width", XtRString, "1cm", 4,
	XtVaTypedArg, "forced_height", XtRString, "1cm", 4,	
                                  NULL );


  btn = XtVaCreateManagedWidget( "Button", wbuttonWidgetClass, self,
                                  "gridy", 1,
                                  "gridx", 0,
                                  "fill", 1,
                                  "weighty", 0,
                                  "weightx", 1,
				                  "gridWidth", 2,
				                  "gridHeight", 1,
				  "label", "Hello World",
                                  NULL );

   XtAddCallback(btn, "callback",(XtCallbackProc) btn_close_cb, self );


}
#line 76 "MessageBox.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 76 "MessageBox.widget"
static void btn_close_cb(Widget  w,Widget self,void * d)
#else
#line 76 "MessageBox.widget"
static void btn_close_cb(w,self,d)Widget  w;Widget self;void * d;
#endif
#line 77 "MessageBox.widget"
{
    XTFUNC();
    XtCallCallbackList( self, ((MessageBoxWidget)self)->messageBox.callback, NULL );
}

static XtResource resources[] = {
#line 6 "MessageBox.widget"
{XtNcallback,XtCCallback,XtRCallback,sizeof(((MessageBoxRec*)NULL)->messageBox.callback),XtOffsetOf(MessageBoxRec,messageBox.callback),XtRImmediate,(XtPointer)NULL },
};

MessageBoxClassRec messageBoxClassRec = {
{ /* core_class part */
/* superclass   	*/  (WidgetClass) &gridboxClassRec,
/* class_name   	*/  "MessageBox",
/* widget_size  	*/  sizeof(MessageBoxRec),
/* class_initialize 	*/  NULL,
/* class_part_initialize*/  _resolve_inheritance,
/* class_inited 	*/  FALSE,
/* initialize   	*/  NULL,
/* initialize_hook 	*/  NULL,
/* realize      	*/  realize,
/* actions      	*/  NULL,
/* num_actions  	*/  0,
/* resources    	*/  resources,
/* num_resources 	*/  1,
/* xrm_class    	*/  NULLQUARK,
/* compres_motion 	*/  False ,
/* compress_exposure 	*/  FALSE ,
/* compress_enterleave 	*/  False ,
/* visible_interest 	*/  False ,
/* destroy      	*/  NULL,
/* resize       	*/  XtInheritResize,
/* expose       	*/  XtInheritExpose,
/* set_values   	*/  NULL,
/* set_values_hook 	*/  NULL,
/* set_values_almost 	*/  XtInheritSetValuesAlmost,
/* get_values+hook 	*/  NULL,
/* accept_focus 	*/  XtInheritAcceptFocus,
/* version      	*/  XtVersion,
/* callback_private 	*/  NULL,
/* tm_table      	*/  XtInheritTranslations,
/* query_geometry 	*/  XtInheritQueryGeometry,
/* display_acceleator 	*/  XtInheritDisplayAccelerator,
/* extension    	*/  NULL 
},
{ /* composite_class part */
XtInheritGeometryManager,
XtInheritChangeManaged,
XtInheritInsertChild,
XtInheritDeleteChild,
NULL
},
{ /* constraint_class part */
/* constraint_resources     */  NULL,
/* num_constraint_resources */  0,
/* constraint_size          */  sizeof(MessageBoxConstraintRec),
/* constraint_initialize    */  NULL,
/* constraint_destroy       */  NULL,
/* constraint_set_values    */  NULL,
/* constraint_extension     */  NULL 
},
{ /* Gridbox_class part */
 /* dummy */  0
},
{ /* MessageBox_class part */
 /* dummy */  0
},
};
WidgetClass messageBoxWidgetClass = (WidgetClass) &messageBoxClassRec;
static void _resolve_inheritance(class)
WidgetClass class;
{
  MessageBoxWidgetClass c __attribute__((unused)) = (MessageBoxWidgetClass) class;
  MessageBoxWidgetClass super __attribute__((unused));
  static CompositeClassExtensionRec extension_rec = {
    NULL, NULLQUARK, XtCompositeExtensionVersion,
    sizeof(CompositeClassExtensionRec), True};
  CompositeClassExtensionRec *ext;
  ext = (XtPointer)XtMalloc(sizeof(*ext));
  *ext = extension_rec;
  ext->next_extension = c->composite_class.extension;
  c->composite_class.extension = ext;
  if (class == messageBoxWidgetClass) return;
  super = (MessageBoxWidgetClass)class->core_class.superclass;
}
#line 13 "MessageBox.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 13 "MessageBox.widget"
static void realize(Widget self,XtValueMask * mask,XSetWindowAttributes * attributes)
#else
#line 13 "MessageBox.widget"
static void realize(self,mask,attributes)Widget self;XtValueMask * mask;XSetWindowAttributes * attributes;
#endif
#line 14 "MessageBox.widget"
{
    XTFUNC();
    XtVaSetValues( self, "borderWidth", 0, NULL );
    gridboxClassRec.core_class.realize(self,mask,attributes);
    add_widgets(self);
}
