/* Generated by wbuild
 * (generator version 3.3)
 */
#include <X11/IntrinsicP.h>
#include <X11/StringDefs.h>
#line 165 "ScrolledCanvas.widget"
#include <X11/Xatom.h>
#line 166 "ScrolledCanvas.widget"
#include <X11/Xft/Xft.h>
#line 167 "ScrolledCanvas.widget"
#include "converters-xft.h"
#line 168 "ScrolledCanvas.widget"
#include "converters.h"
#line 169 "ScrolledCanvas.widget"
#include <X11/Xmu/Converters.h>
#line 170 "ScrolledCanvas.widget"
#include "mls.h"
#line 171 "ScrolledCanvas.widget"
#include "xutil.h"
#line 172 "ScrolledCanvas.widget"
#include <X11/Xaw/Command.h>
#line 173 "ScrolledCanvas.widget"
#include "xtcw/HSlider.h"
#line 174 "ScrolledCanvas.widget"
#include "xtcw/VSlider.h"
#line 175 "ScrolledCanvas.widget"
#include "xtcw/Canvas.h"
#include <xtcw/ScrolledCanvasP.h>
#line 119 "ScrolledCanvas.widget"
static void sc_motion(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 149 "ScrolledCanvas.widget"
static void redraw(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 155 "ScrolledCanvas.widget"
static void zoom(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);

static XtActionsRec actionsList[] = {
{"sc_motion", sc_motion},
{"redraw", redraw},
{"zoom", zoom},
};

static char defaultTranslations[] = "\
<Btn1Motion>: sc_motion() \n\
<Btn1Up>: sc_motion_end() \n\
";
static void _resolve_inheritance(
#if NeedFunctionPrototypes
WidgetClass
#endif
);
#line 24 "ScrolledCanvas.widget"
static void realize(
#if NeedFunctionPrototypes
Widget,XtValueMask *,XSetWindowAttributes *
#endif
);
#line 35 "ScrolledCanvas.widget"
static void add_widgets(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 81 "ScrolledCanvas.widget"
static void update_slider_cb(
#if NeedFunctionPrototypes
Widget ,Widget,void *
#endif
);
#line 91 "ScrolledCanvas.widget"
static void sliderx_cb(
#if NeedFunctionPrototypes
Widget ,Widget,void *
#endif
);
#line 99 "ScrolledCanvas.widget"
static void slidery_cb(
#if NeedFunctionPrototypes
Widget ,Widget,void *
#endif
);
#line 107 "ScrolledCanvas.widget"
static void movexy(
#if NeedFunctionPrototypes
Widget,int ,int 
#endif
);
#line 35 "ScrolledCanvas.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 35 "ScrolledCanvas.widget"
static void add_widgets(Widget self)
#else
#line 35 "ScrolledCanvas.widget"
static void add_widgets(self)Widget self;
#endif
#line 36 "ScrolledCanvas.widget"
{
	 ((ScrolledCanvasWidget)self)->scrolledCanvas.slv = XtVaCreateManagedWidget( "sliderV", vSliderWidgetClass, self,
                                  "gridy", 0,
                                  "gridx", 1,
                                  "fill", 2,
                                  "weighty", 10,
                                  "weightx", 0,
				  "gridWidth", 1,
				  "gridHeight", 1,
                                  "width", ((ScrolledCanvasWidget)self)->scrolledCanvas.slwidth,
                                  NULL );

     XtAddCallback(((ScrolledCanvasWidget)self)->scrolledCanvas.slv, "callback",(XtCallbackProc) slidery_cb, self );

     ((ScrolledCanvasWidget)self)->scrolledCanvas.can = XtVaCreateManagedWidget( "canvas", canvasWidgetClass, self,
                                  "gridy", 0,
                                  "gridx", 0,
                                  "fill", 3,
                                  "weighty", 10,
                                  "weightx", 10,
                                  NULL );

     XtAddCallback(((ScrolledCanvasWidget)self)->scrolledCanvas.can, "callback", (XtCallbackProc) update_slider_cb, self );


	 ((ScrolledCanvasWidget)self)->scrolledCanvas.slh = XtVaCreateManagedWidget( "sliderH", hSliderWidgetClass, self,
	 	                  "gridy", 1,
                          "gridx", 0,
                          "fill", 1,
                          "height", ((ScrolledCanvasWidget)self)->scrolledCanvas.slwidth,
                                  "weighty", 0,
                                  "weightx", 0,
                            NULL );

     XtAddCallback(((ScrolledCanvasWidget)self)->scrolledCanvas.slh, "callback",(XtCallbackProc) sliderx_cb, self );

     ((ScrolledCanvasWidget)self)->scrolledCanvas.priv = canvas_get_priv(((ScrolledCanvasWidget)self)->scrolledCanvas.can);
     ((ScrolledCanvasWidget)self)->scrolledCanvas.priv->world_width  = ((ScrolledCanvasWidget)self)->scrolledCanvas.world_width;
     ((ScrolledCanvasWidget)self)->scrolledCanvas.priv->world_height = ((ScrolledCanvasWidget)self)->scrolledCanvas.world_height;
}
#line 81 "ScrolledCanvas.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 81 "ScrolledCanvas.widget"
static void update_slider_cb(Widget  w,Widget self,void * d)
#else
#line 81 "ScrolledCanvas.widget"
static void update_slider_cb(w,self,d)Widget  w;Widget self;void * d;
#endif
#line 82 "ScrolledCanvas.widget"
{
    unsigned frac;
    frac = ((ScrolledCanvasWidget)self)->scrolledCanvas.priv->win_height * 1000000UL / ((ScrolledCanvasWidget)self)->scrolledCanvas.world_height;
    XtVaSetValues( ((ScrolledCanvasWidget)self)->scrolledCanvas.slv, "frac", frac, NULL );

    frac =  ((ScrolledCanvasWidget)self)->scrolledCanvas.priv->win_width * 1000000UL / ((ScrolledCanvasWidget)self)->scrolledCanvas.world_width;
    XtVaSetValues( ((ScrolledCanvasWidget)self)->scrolledCanvas.slh, "frac", frac, NULL );
}
#line 91 "ScrolledCanvas.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 91 "ScrolledCanvas.widget"
static void sliderx_cb(Widget  w,Widget self,void * d)
#else
#line 91 "ScrolledCanvas.widget"
static void sliderx_cb(w,self,d)Widget  w;Widget self;void * d;
#endif
#line 92 "ScrolledCanvas.widget"
{
    XTFUNC();
    ((ScrolledCanvasWidget)self)->scrolledCanvas.priv->sl_posx = (intptr_t) d;
    self=((ScrolledCanvasWidget)self)->scrolledCanvas.can;
    ((ScrolledCanvasWidgetClass)self->core.widget_class)->core_class.expose(self,NULL,NULL); 
}
#line 99 "ScrolledCanvas.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 99 "ScrolledCanvas.widget"
static void slidery_cb(Widget  w,Widget self,void * d)
#else
#line 99 "ScrolledCanvas.widget"
static void slidery_cb(w,self,d)Widget  w;Widget self;void * d;
#endif
#line 100 "ScrolledCanvas.widget"
{
    XTFUNC();
    ((ScrolledCanvasWidget)self)->scrolledCanvas.priv->sl_posy = (intptr_t) d;
    self=((ScrolledCanvasWidget)self)->scrolledCanvas.can;
    ((ScrolledCanvasWidgetClass)self->core.widget_class)->core_class.expose(self,NULL,NULL);
}
#line 107 "ScrolledCanvas.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 107 "ScrolledCanvas.widget"
static void movexy(Widget self,int  x,int  y)
#else
#line 107 "ScrolledCanvas.widget"
static void movexy(self,x,y)Widget self;int  x;int  y;
#endif
#line 108 "ScrolledCanvas.widget"
{
	/* move VSlider y-pixel u/d */
	/* move HSlider x-pixel l/r */
	/* update $priv->>sl_posy */
	/* update $priv->>sl_posx */	
	/* move Canvas x/y -pixel -> just redraw */	
}

static XtResource resources[] = {
#line 5 "ScrolledCanvas.widget"
{XtNslwidth,XtCSlwidth,XtRDistance,sizeof(((ScrolledCanvasRec*)NULL)->scrolledCanvas.slwidth),XtOffsetOf(ScrolledCanvasRec,scrolledCanvas.slwidth),XtRString,(XtPointer)"3mm"},
#line 6 "ScrolledCanvas.widget"
{XtNworld_width,XtCWorld_width,XtRUint,sizeof(((ScrolledCanvasRec*)NULL)->scrolledCanvas.world_width),XtOffsetOf(ScrolledCanvasRec,scrolledCanvas.world_width),XtRImmediate,(XtPointer)10000 },
#line 7 "ScrolledCanvas.widget"
{XtNworld_height,XtCWorld_height,XtRUint,sizeof(((ScrolledCanvasRec*)NULL)->scrolledCanvas.world_height),XtOffsetOf(ScrolledCanvasRec,scrolledCanvas.world_height),XtRImmediate,(XtPointer)10000 },
#line 8 "ScrolledCanvas.widget"
{XtNdrag_last_x,XtCDrag_last_x,XtRInt,sizeof(((ScrolledCanvasRec*)NULL)->scrolledCanvas.drag_last_x),XtOffsetOf(ScrolledCanvasRec,scrolledCanvas.drag_last_x),XtRImmediate,(XtPointer)0 },
#line 9 "ScrolledCanvas.widget"
{XtNdrag_last_y,XtCDrag_last_y,XtRInt,sizeof(((ScrolledCanvasRec*)NULL)->scrolledCanvas.drag_last_y),XtOffsetOf(ScrolledCanvasRec,scrolledCanvas.drag_last_y),XtRImmediate,(XtPointer)0 },
#line 10 "ScrolledCanvas.widget"
{XtNdrag_time,XtCDrag_time,XtRUlong,sizeof(((ScrolledCanvasRec*)NULL)->scrolledCanvas.drag_time),XtOffsetOf(ScrolledCanvasRec,scrolledCanvas.drag_time),XtRImmediate,(XtPointer)0 },
};

ScrolledCanvasClassRec scrolledCanvasClassRec = {
{ /* core_class part */
/* superclass   	*/  (WidgetClass) &gridboxClassRec,
/* class_name   	*/  "ScrolledCanvas",
/* widget_size  	*/  sizeof(ScrolledCanvasRec),
/* class_initialize 	*/  NULL,
/* class_part_initialize*/  _resolve_inheritance,
/* class_inited 	*/  FALSE,
/* initialize   	*/  NULL,
/* initialize_hook 	*/  NULL,
/* realize      	*/  realize,
/* actions      	*/  actionsList,
/* num_actions  	*/  3,
/* resources    	*/  resources,
/* num_resources 	*/  6,
/* xrm_class    	*/  NULLQUARK,
/* compres_motion 	*/  False ,
/* compress_exposure 	*/  FALSE ,
/* compress_enterleave 	*/  False ,
/* visible_interest 	*/  False ,
/* destroy      	*/  NULL,
/* resize       	*/  XtInheritResize,
/* expose       	*/  XtInheritExpose,
/* set_values   	*/  NULL,
/* set_values_hook 	*/  NULL,
/* set_values_almost 	*/  XtInheritSetValuesAlmost,
/* get_values+hook 	*/  NULL,
/* accept_focus 	*/  XtInheritAcceptFocus,
/* version      	*/  XtVersion,
/* callback_private 	*/  NULL,
/* tm_table      	*/  defaultTranslations,
/* query_geometry 	*/  XtInheritQueryGeometry,
/* display_acceleator 	*/  XtInheritDisplayAccelerator,
/* extension    	*/  NULL 
},
{ /* composite_class part */
XtInheritGeometryManager,
XtInheritChangeManaged,
XtInheritInsertChild,
XtInheritDeleteChild,
NULL
},
{ /* constraint_class part */
/* constraint_resources     */  NULL,
/* num_constraint_resources */  0,
/* constraint_size          */  sizeof(ScrolledCanvasConstraintRec),
/* constraint_initialize    */  NULL,
/* constraint_destroy       */  NULL,
/* constraint_set_values    */  NULL,
/* constraint_extension     */  NULL 
},
{ /* Gridbox_class part */
 /* dummy */  0
},
{ /* ScrolledCanvas_class part */
 /* dummy */  0
},
};
WidgetClass scrolledCanvasWidgetClass = (WidgetClass) &scrolledCanvasClassRec;
/*ARGSUSED*/
#line 119 "ScrolledCanvas.widget"
static void sc_motion(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
	int x = event->xbutton.x;
	int y = event->xbutton.y;
	int lineno;
	ulong t = (ulong ) event->xbutton.time;
	if( ((ScrolledCanvasWidget)self)->scrolledCanvas.drag_time == 0 ) goto restart_drag;

	/* drag startete vor über einer sekunde, seitdem keine änderung */
	/* darum: vergessen und neu starten */
	if( ((ScrolledCanvasWidget)self)->scrolledCanvas.drag_time + 1000 < t ) goto restart_drag;
	((ScrolledCanvasWidget)self)->scrolledCanvas.drag_time = t;

	if( y == ((ScrolledCanvasWidget)self)->scrolledCanvas.drag_last_y &&  x == ((ScrolledCanvasWidget)self)->scrolledCanvas.drag_last_x )
	  return; /* drag in progress */	

	int move_y = (((ScrolledCanvasWidget)self)->scrolledCanvas.drag_last_y - y);
	int move_x = (((ScrolledCanvasWidget)self)->scrolledCanvas.drag_last_x - x);
	((ScrolledCanvasWidget)self)->scrolledCanvas.drag_last_y = y;
        ((ScrolledCanvasWidget)self)->scrolledCanvas.drag_last_x = x;
	movexy( self, move_x, move_y );

  restart_drag:
	((ScrolledCanvasWidget)self)->scrolledCanvas.drag_last_y = event->xbutton.y;
	((ScrolledCanvasWidget)self)->scrolledCanvas.drag_last_x = event->xbutton.x;
	((ScrolledCanvasWidget)self)->scrolledCanvas.drag_time = t;
}

/*ARGSUSED*/
#line 149 "ScrolledCanvas.widget"
static void redraw(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    self=((ScrolledCanvasWidget)self)->scrolledCanvas.can;
    ((ScrolledCanvasWidgetClass)self->core.widget_class)->core_class.expose(self,NULL,NULL);	
}

/*ARGSUSED*/
#line 155 "ScrolledCanvas.widget"
static void zoom(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
  XtCallActionProc( ((ScrolledCanvasWidget)self)->scrolledCanvas.can, "zoom", NULL, params, * num_params );	
}

static void _resolve_inheritance(class)
WidgetClass class;
{
  ScrolledCanvasWidgetClass c __attribute__((unused)) = (ScrolledCanvasWidgetClass) class;
  ScrolledCanvasWidgetClass super __attribute__((unused));
  static CompositeClassExtensionRec extension_rec = {
    NULL, NULLQUARK, XtCompositeExtensionVersion,
    sizeof(CompositeClassExtensionRec), True};
  CompositeClassExtensionRec *ext;
  ext = (XtPointer)XtMalloc(sizeof(*ext));
  *ext = extension_rec;
  ext->next_extension = c->composite_class.extension;
  c->composite_class.extension = ext;
  if (class == scrolledCanvasWidgetClass) return;
  super = (ScrolledCanvasWidgetClass)class->core_class.superclass;
}
#line 24 "ScrolledCanvas.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 24 "ScrolledCanvas.widget"
static void realize(Widget self,XtValueMask * mask,XSetWindowAttributes * attributes)
#else
#line 24 "ScrolledCanvas.widget"
static void realize(self,mask,attributes)Widget self;XtValueMask * mask;XSetWindowAttributes * attributes;
#endif
#line 25 "ScrolledCanvas.widget"
{
    XTFUNC();
    gridboxClassRec.core_class.realize(self,mask,attributes);
    add_widgets(self);

}
