/* Generated by wbuild
 * (generator version 3.3)
 */
#include <X11/IntrinsicP.h>
#include <X11/StringDefs.h>
#line 772 "WeditMV.widget"
#include <assert.h>
#line 773 "WeditMV.widget"
#include <X11/Intrinsic.h>
#line 774 "WeditMV.widget"
#include <X11/Xatom.h>
#line 775 "WeditMV.widget"
#include <X11/Xmu/Converters.h>
#line 776 "WeditMV.widget"
#include <X11/Xft/Xft.h>
#line 777 "WeditMV.widget"
#include <X11/Xaw/XawImP.h>
#line 778 "WeditMV.widget"
#include "converters.h"
#line 779 "WeditMV.widget"
#include "xutil.h"
#line 780 "WeditMV.widget"
#include "mls.h"
#line 781 "WeditMV.widget"
#include "font.h"
#line 782 "WeditMV.widget"
#include "micro_vars.h"
#line 783 "WeditMV.widget"
#include "svar2.h"
#line 784 "WeditMV.widget"
#include "var5.h"
#line 785 "WeditMV.widget"
#include "opts.h"
#include <xtcw/WeditMVP.h>
#line 665 "WeditMV.widget"
static void CallOnEnter(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 672 "WeditMV.widget"
static void SetKeyboardFocus(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 687 "WeditMV.widget"
static void focus_in(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 693 "WeditMV.widget"
static void focus_out(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 699 "WeditMV.widget"
static void info(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 704 "WeditMV.widget"
static void backward_char(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 710 "WeditMV.widget"
static void forward_char(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 716 "WeditMV.widget"
static void insert_char(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 730 "WeditMV.widget"
static void remove_char(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 736 "WeditMV.widget"
static void set_cursor(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 755 "WeditMV.widget"
static void insert_selection(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 763 "WeditMV.widget"
static void notify(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);

static XtActionsRec actionsList[] = {
{"CallOnEnter", CallOnEnter},
{"SetKeyboardFocus", SetKeyboardFocus},
{"focus_in", focus_in},
{"focus_out", focus_out},
{"info", info},
{"backward_char", backward_char},
{"forward_char", forward_char},
{"insert_char", insert_char},
{"remove_char", remove_char},
{"set_cursor", set_cursor},
{"insert_selection", insert_selection},
{"notify", notify},
};

static char defaultTranslations[] = "\
<Key>Right: forward_char() \n\
<Key>Left: backward_char() \n\
<Key>Delete: remove_char() \n\
<Key>BackSpace: backward_char() remove_char() \n\
<Ctrl>x: info() \n\
<Ctrl>v: insert_selection() \n\
<Btn1Down>: set_cursor() SetKeyboardFocus() \n\
<Key>Return: CallOnEnter() notify() \n\
<Key>: insert_char() \n\
<FocusIn>: focus_in() \n\
<FocusOut>: focus_out() \n\
";
static void _resolve_inheritance(
#if NeedFunctionPrototypes
WidgetClass
#endif
);
#line 82 "WeditMV.widget"
static void initialize(
#if NeedFunctionPrototypes
Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 117 "WeditMV.widget"
static void destroy(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 127 "WeditMV.widget"
static Boolean  set_values(
#if NeedFunctionPrototypes
Widget ,Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 140 "WeditMV.widget"
static void get_values_hook(
#if NeedFunctionPrototypes
Widget,ArgList ,Cardinal *
#endif
);
#line 152 "WeditMV.widget"
static void expose(
#if NeedFunctionPrototypes
Widget,XEvent *,Region 
#endif
);
#line 160 "WeditMV.widget"
static void realize(
#if NeedFunctionPrototypes
Widget,XtValueMask *,XSetWindowAttributes *
#endif
);
#line 167 "WeditMV.widget"
static void resize(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 172 "WeditMV.widget"
static Boolean  accept_focus(
#if NeedFunctionPrototypes
Widget,Time *
#endif
);
#line 179 "WeditMV.widget"
static XtGeometryResult  query_geometry(
#if NeedFunctionPrototypes
Widget,XtWidgetGeometry *,XtWidgetGeometry *
#endif
);
#line 194 "WeditMV.widget"
static void resize_widget(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 221 "WeditMV.widget"
static void clear_pixmap(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 227 "WeditMV.widget"
static void draw_text_on_pixmap(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 233 "WeditMV.widget"
static void draw_pixmap_on_window(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 240 "WeditMV.widget"
static XftGlyphFontSpec * get_glyph_spec(
#if NeedFunctionPrototypes
Widget,int 
#endif
);
#line 246 "WeditMV.widget"
static void draw_cursor(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 260 "WeditMV.widget"
static void dump(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 270 "WeditMV.widget"
static void paint(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 296 "WeditMV.widget"
static void cursor_toggle(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 302 "WeditMV.widget"
static void cursor_undraw(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 307 "WeditMV.widget"
static void cursor_show(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 313 "WeditMV.widget"
static void cursor_xdraw(
#if NeedFunctionPrototypes
Widget,XRectangle *
#endif
);
#line 322 "WeditMV.widget"
static void calculate_prefered_size(
#if NeedFunctionPrototypes
Widget,int *,int *
#endif
);
#line 329 "WeditMV.widget"
static void calculate_size(
#if NeedFunctionPrototypes
Widget,int *,int *
#endif
);
#line 336 "WeditMV.widget"
static void copy_str(
#if NeedFunctionPrototypes
Widget,char *
#endif
);
#line 346 "WeditMV.widget"
static void reinit(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 356 "WeditMV.widget"
static void make_resize_request(
#if NeedFunctionPrototypes
Widget,int ,int 
#endif
);
#line 364 "WeditMV.widget"
static void alloc_colors(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 387 "WeditMV.widget"
static void free_colors(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 400 "WeditMV.widget"
static void draw_glyphs_spec(
#if NeedFunctionPrototypes
Widget,int ,int 
#endif
);
#line 417 "WeditMV.widget"
static void draw_glyphs(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 436 "WeditMV.widget"
static void unicode_to_glyphspec(
#if NeedFunctionPrototypes
Widget,uint ,XftGlyphFontSpec *,int *,int *,int *
#endif
);
#line 466 "WeditMV.widget"
static void str_to_glyphlist(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 492 "WeditMV.widget"
static int  char_offset(
#if NeedFunctionPrototypes
Widget,int 
#endif
);
#line 503 "WeditMV.widget"
static void insert_char_at_cursor(
#if NeedFunctionPrototypes
Widget,char *,int 
#endif
);
#line 512 "WeditMV.widget"
static void remove_char_at_cursor(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 524 "WeditMV.widget"
static char  scroll_left(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 534 "WeditMV.widget"
static char  scroll_right(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 549 "WeditMV.widget"
static int  px_left_offset(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 557 "WeditMV.widget"
static int  px_char(
#if NeedFunctionPrototypes
Widget,int 
#endif
);
#line 567 "WeditMV.widget"
static int  screen_px(
#if NeedFunctionPrototypes
Widget,int 
#endif
);
#line 579 "WeditMV.widget"
static void cursor_right(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 597 "WeditMV.widget"
static void cursor_left(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 612 "WeditMV.widget"
static void RequestSelection(
#if NeedFunctionPrototypes
Widget,XtPointer ,Atom *,Atom *,XtPointer ,unsigned  long *,int *
#endif
);
#line 627 "WeditMV.widget"
static char * get_text_buffer(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 638 "WeditMV.widget"
static void update_svar(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 650 "WeditMV.widget"
static void update_mvar(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 194 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 194 "WeditMV.widget"
static void resize_widget(Widget self)
#else
#line 194 "WeditMV.widget"
static void resize_widget(self)Widget self;
#endif
#line 195 "WeditMV.widget"
{
        /*
        int w;
	if( $cornerRoundPercent >0 && $cornerRoundPercent < 100 ) {
	    w = Min($height,$width);
	    w = w * $cornerRoundPercent / 100;
	    XmuReshapeWidget( $, XmuShapeRoundedRectangle, w, w );
	}
        */

    if( ((WeditMVWidget)self)->weditMV.pix.data ) { XFreePixmap( XtDisplay(self), ((WeditMVWidget)self)->weditMV.pix.data ); }
    ((WeditMVWidget)self)->weditMV.pix.data = XtCreatePixmap(self,((WeditMVWidget)self)->core.width,((WeditMVWidget)self)->weditMV.txt.height);
    ((WeditMVWidget)self)->weditMV.pix.r.width = ((WeditMVWidget)self)->core.width; ((WeditMVWidget)self)->weditMV.pix.r.height = ((WeditMVWidget)self)->weditMV.txt.height;

    ((WeditMVWidget)self)->weditMV.pix.r.x = 0;  ((WeditMVWidget)self)->weditMV.pix.r.y = (((WeditMVWidget)self)->core.height - ((WeditMVWidget)self)->weditMV.txt.height) / 2;
    if( ! ((WeditMVWidget)self)->weditMV.draw ) {
        ((WeditMVWidget)self)->weditMV.draw = XtXftDrawCreate(self,((WeditMVWidget)self)->weditMV.pix.data);
    }
    else {
        XftDrawChange(((WeditMVWidget)self)->weditMV.draw,((WeditMVWidget)self)->weditMV.pix.data);
    }

    ((WeditMVWidget)self)->weditMV.left_char_offset = 0;
    ((WeditMVWidget)self)->weditMV.crsr_pos = 0;
}
#line 221 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 221 "WeditMV.widget"
static void clear_pixmap(Widget self)
#else
#line 221 "WeditMV.widget"
static void clear_pixmap(self)Widget self;
#endif
#line 222 "WeditMV.widget"
{
   XFillRectangle(XtDisplay(self),((WeditMVWidget)self)->weditMV.pix.data,
                       ((WeditMVWidget)self)->weditMV.gc[BG], 0,0, ((WeditMVWidget)self)->weditMV.pix.r.width, ((WeditMVWidget)self)->weditMV.pix.r.height );
}
#line 227 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 227 "WeditMV.widget"
static void draw_text_on_pixmap(Widget self)
#else
#line 227 "WeditMV.widget"
static void draw_text_on_pixmap(self)Widget self;
#endif
#line 228 "WeditMV.widget"
{
    /* str_to_glyphlist($); */
    draw_glyphs(self);
}
#line 233 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 233 "WeditMV.widget"
static void draw_pixmap_on_window(Widget self)
#else
#line 233 "WeditMV.widget"
static void draw_pixmap_on_window(self)Widget self;
#endif
#line 234 "WeditMV.widget"
{
        XtCopyArea(self, ((WeditMVWidget)self)->weditMV.pix.data, XtWindow(self),
                   0,0, ((WeditMVWidget)self)->weditMV.pix.r.width, ((WeditMVWidget)self)->weditMV.pix.r.height, /* src */
                   ((WeditMVWidget)self)->weditMV.pix.r.x, ((WeditMVWidget)self)->weditMV.pix.r.y );             /* dest */
}
#line 240 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 240 "WeditMV.widget"
static XftGlyphFontSpec * get_glyph_spec(Widget self,int  p)
#else
#line 240 "WeditMV.widget"
static XftGlyphFontSpec * get_glyph_spec(self,p)Widget self;int  p;
#endif
#line 241 "WeditMV.widget"
{
        return mls(((WeditMVWidget)self)->weditMV.glyph_m, p);
}
#line 246 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 246 "WeditMV.widget"
static void draw_cursor(Widget self)
#else
#line 246 "WeditMV.widget"
static void draw_cursor(self)Widget self;
#endif
#line 247 "WeditMV.widget"
{
        XRectangle r;
        if( ((WeditMVWidget)self)->weditMV.crsr_pos >= m_len(((WeditMVWidget)self)->weditMV.glyph_m) )
            ((WeditMVWidget)self)->weditMV.crsr_pos=m_len(((WeditMVWidget)self)->weditMV.glyph_m)-1;

        r.width = INT(((WeditMVWidget)self)->weditMV.glyph_xoff_m,((WeditMVWidget)self)->weditMV.crsr_pos);
        r.x = screen_px(self, ((WeditMVWidget)self)->weditMV.crsr_pos) + ((WeditMVWidget)self)->weditMV.pix.r.x;
        r.y = ((WeditMVWidget)self)->weditMV.pix.r.y;
        r.height = ((WeditMVWidget)self)->weditMV.xftFont->height;
        cursor_xdraw( self, &r );
}
#line 260 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 260 "WeditMV.widget"
static void dump(Widget self)
#else
#line 260 "WeditMV.widget"
static void dump(self)Widget self;
#endif
#line 261 "WeditMV.widget"
{
    int i; for(i=0;i< m_len(((WeditMVWidget)self)->weditMV.str_m)-1; i++)
               printf("%x ", (unsigned char) CHAR(((WeditMVWidget)self)->weditMV.str_m, i) );
    putc(10,stdout);
    fwrite( m_buf(((WeditMVWidget)self)->weditMV.str_m), m_len(((WeditMVWidget)self)->weditMV.str_m), 1, stdout );
    printf("Left:%d Crsr:%d\n", ((WeditMVWidget)self)->weditMV.left_char_offset, ((WeditMVWidget)self)->weditMV.crsr_pos );
}
#line 270 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 270 "WeditMV.widget"
static void paint(Widget self)
#else
#line 270 "WeditMV.widget"
static void paint(self)Widget self;
#endif
#line 271 "WeditMV.widget"
{
	TRACE(8, "-- %s:%s", XtName(self), "WeditMV" );
        clear_pixmap(self);
        draw_text_on_pixmap(self);
        draw_pixmap_on_window(self);
	if( ((WeditMVWidget)self)->weditMV.crsr_on ) {
	    ((WeditMVWidget)self)->weditMV.crsr_on=0;
            draw_cursor(self);
	}	
        ((WeditMVWidget)self)->weditMV.dirty = 0;

	// send buffer handle to application
	mv_write( ((WeditMVWidget)self)->weditMV.textBuffer, ((WeditMVWidget)self)->weditMV.str_m );

	// copy buffer to svar and call svar write callbacks
	update_svar(self);
	svar_write_callbacks(((WeditMVWidget)self)->weditMV.key_svar);

	update_mvar(self);
	XtCallCallbackList( self, ((WeditMVWidget)self)->weditMV.onChanged, NULL );
	TRACE(1, "widget %s sent to %d", ((WeditMVWidget)self)->core.name, ((WeditMVWidget)self)->weditMV.textBuffer );
}
#line 296 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 296 "WeditMV.widget"
static void cursor_toggle(Widget self)
#else
#line 296 "WeditMV.widget"
static void cursor_toggle(self)Widget self;
#endif
#line 297 "WeditMV.widget"
{
        ((WeditMVWidget)self)->weditMV.crsr_on ^= 1;
        XtFillRectangle(self, ((WeditMVWidget)self)->weditMV.gc[CRSR], & ((WeditMVWidget)self)->weditMV.crsr_rect );
}
#line 302 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 302 "WeditMV.widget"
static void cursor_undraw(Widget self)
#else
#line 302 "WeditMV.widget"
static void cursor_undraw(self)Widget self;
#endif
#line 303 "WeditMV.widget"
{
    if( ((WeditMVWidget)self)->weditMV.crsr_on ) cursor_toggle(self);
}
#line 307 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 307 "WeditMV.widget"
static void cursor_show(Widget self)
#else
#line 307 "WeditMV.widget"
static void cursor_show(self)Widget self;
#endif
#line 308 "WeditMV.widget"
{
    if(! ((WeditMVWidget)self)->weditMV.crsr_on ) cursor_toggle(self);
}
#line 313 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 313 "WeditMV.widget"
static void cursor_xdraw(Widget self,XRectangle * r)
#else
#line 313 "WeditMV.widget"
static void cursor_xdraw(self,r)Widget self;XRectangle * r;
#endif
#line 314 "WeditMV.widget"
{
    cursor_undraw(self);
    ((WeditMVWidget)self)->weditMV.crsr_rect = *r;
    cursor_toggle(self);
}
#line 322 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 322 "WeditMV.widget"
static void calculate_prefered_size(Widget self,int * w,int * h)
#else
#line 322 "WeditMV.widget"
static void calculate_prefered_size(self,w,h)Widget self;int * w;int * h;
#endif
#line 323 "WeditMV.widget"
{
  (*h) = ((WeditMVWidget)self)->weditMV.xftFont->height; /* $xftFont->ascent + $xftFont->descent+2; */
  (*w) = ((WeditMVWidget)self)->weditMV.txt.width;
  if( *w == 0 || *w > 18000 ) *w = 50;      
}
#line 329 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 329 "WeditMV.widget"
static void calculate_size(Widget self,int * w,int * h)
#else
#line 329 "WeditMV.widget"
static void calculate_size(self,w,h)Widget self;int * w;int * h;
#endif
#line 330 "WeditMV.widget"
{
    *w = ((WeditMVWidget)self)->weditMV.txt.width;
    *h = ((WeditMVWidget)self)->weditMV.txt.height;
    /*    xft_calc_string_size($, $xftFont, $label, w, h ); */
}
#line 336 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 336 "WeditMV.widget"
static void copy_str(Widget self,char * s)
#else
#line 336 "WeditMV.widget"
static void copy_str(self,s)Widget self;char * s;
#endif
#line 337 "WeditMV.widget"
{
        m_clear( ((WeditMVWidget)self)->weditMV.str_m );
        m_write( ((WeditMVWidget)self)->weditMV.str_m, 0, s, strlen(s) );
        m_putc( ((WeditMVWidget)self)->weditMV.str_m, '.' );
        str_to_glyphlist(self);
        ((WeditMVWidget)self)->weditMV.dirty = 1;
}
#line 346 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 346 "WeditMV.widget"
static void reinit(Widget self)
#else
#line 346 "WeditMV.widget"
static void reinit(self)Widget self;
#endif
#line 347 "WeditMV.widget"
{
        free_colors(self);
        alloc_colors(self);

        int w,h;
        calculate_prefered_size(self,&w,&h);
        make_resize_request(self,w,h);
}
#line 356 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 356 "WeditMV.widget"
static void make_resize_request(Widget self,int  w,int  h)
#else
#line 356 "WeditMV.widget"
static void make_resize_request(self,w,h)Widget self;int  w;int  h;
#endif
#line 357 "WeditMV.widget"
{
        Dimension w_out, h_out;
        if( ((WeditMVWidget)self)->core.width == w && ((WeditMVWidget)self)->core.height == h ) return;
        if( XtMakeResizeRequest(self,w,h, &w_out, &h_out ) ==
            XtGeometryAlmost ) XtMakeResizeRequest(self,w_out,h_out,NULL,NULL );
}
#line 364 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 364 "WeditMV.widget"
static void alloc_colors(Widget self)
#else
#line 364 "WeditMV.widget"
static void alloc_colors(self)Widget self;
#endif
#line 365 "WeditMV.widget"
{

  XGCValues     values = {
  		foreground: ((WeditMVWidget)self)->core.background_pixel,
  		graphics_exposures: False,
                line_width: ((WeditMVWidget)self)->weditMV.lineWidth };
  uint          mask = GCForeground | GCGraphicsExposures |  GCLineWidth;
  ((WeditMVWidget)self)->weditMV.gc[BG] = XtGetGC(self, mask, &values);
  values.foreground = ((WeditMVWidget)self)->weditMV.foreground;
  ((WeditMVWidget)self)->weditMV.gc[FG] = XtGetGC(self,mask,&values);

  mask = GCForeground | GCBackground | GCFunction;
  values.foreground = ((WeditMVWidget)self)->weditMV.cursorColor ^ ((WeditMVWidget)self)->core.background_pixel;
  values.background = ((WeditMVWidget)self)->core.background_pixel;
  values.function = GXxor;
  ((WeditMVWidget)self)->weditMV.gc[CRSR] = XtGetGC(self, mask, &values);

  xft_color_alloc( self, ((WeditMVWidget)self)->core.background_pixel, ((WeditMVWidget)self)->weditMV.xcol+BG );
  xft_color_alloc( self, ((WeditMVWidget)self)->weditMV.foreground,       ((WeditMVWidget)self)->weditMV.xcol+FG );
  xft_color_alloc( self, ((WeditMVWidget)self)->weditMV.cursorColor,      ((WeditMVWidget)self)->weditMV.xcol+CRSR );
}
#line 387 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 387 "WeditMV.widget"
static void free_colors(Widget self)
#else
#line 387 "WeditMV.widget"
static void free_colors(self)Widget self;
#endif
#line 388 "WeditMV.widget"
{
        int i;
        Display *dpy = XtDisplay(self);
        for(i=0;i<2;i++) {
                XtReleaseGC(self,((WeditMVWidget)self)->weditMV.gc[i]);
                XftColorFree(dpy, DefaultVisual(dpy, DefaultScreen(dpy)),
		 None, ((WeditMVWidget)self)->weditMV.xcol+i);
        }
}
#line 400 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 400 "WeditMV.widget"
static void draw_glyphs_spec(Widget self,int  start,int  stop)
#else
#line 400 "WeditMV.widget"
static void draw_glyphs_spec(self,start,stop)Widget self;int  start;int  stop;
#endif
#line 401 "WeditMV.widget"
{
    int i, xa = 0;
    if( start < 0 ) start = 0;
    if( stop > m_len(((WeditMVWidget)self)->weditMV.glyph_m) ) stop = m_len(((WeditMVWidget)self)->weditMV.glyph_m)-1;
    if( stop < start ) return;

    for( i=start; i <= stop; i++ ) {
        get_glyph_spec(self,i)->x = xa;
        xa += INT(((WeditMVWidget)self)->weditMV.glyph_xoff_m,i);
    }

    XftDrawGlyphFontSpec( ((WeditMVWidget)self)->weditMV.draw, ((WeditMVWidget)self)->weditMV.xcol + FG,
                          mls(((WeditMVWidget)self)->weditMV.glyph_m, start), stop-start +1 );
}
#line 417 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 417 "WeditMV.widget"
static void draw_glyphs(Widget self)
#else
#line 417 "WeditMV.widget"
static void draw_glyphs(self)Widget self;
#endif
#line 418 "WeditMV.widget"
{
    if( ((WeditMVWidget)self)->weditMV.dirty_str ) str_to_glyphlist(self);

    int nglyphs = m_len(((WeditMVWidget)self)->weditMV.glyph_m) -1;

    int width = ((WeditMVWidget)self)->weditMV.pix.r.width;
    int p = ((WeditMVWidget)self)->weditMV.left_char_offset;
    while( p < nglyphs ) {
        width -= INT(((WeditMVWidget)self)->weditMV.glyph_xoff_m,p);
        if( width < 0 ) break;
        p++;
    }

    draw_glyphs_spec(self, ((WeditMVWidget)self)->weditMV.left_char_offset, p-1 );
}
#line 436 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 436 "WeditMV.widget"
static void unicode_to_glyphspec(Widget self,uint  unicode,XftGlyphFontSpec * specs,int * xp,int * yp,int * xOff)
#else
#line 436 "WeditMV.widget"
static void unicode_to_glyphspec(self,unicode,specs,xp,yp,xOff)Widget self;uint  unicode;XftGlyphFontSpec * specs;int * xp;int * yp;int * xOff;
#endif
#line 437 "WeditMV.widget"
{
    Display *dpy = XtDisplay(self);
    static FT_UInt glyph_fallback = 0;
    FT_UInt glyphindex;
    XGlyphInfo extents;
    XftFont *fnt = ((WeditMVWidget)self)->weditMV.xftFont;

    if( !glyph_fallback )
        glyph_fallback = XftCharIndex(dpy,fnt, '#' );

    fnt = font_unicode_find(((WeditMVWidget)self)->weditMV.fontName, unicode,(int*) &glyphindex );
    if(!glyphindex) {
             fnt=((WeditMVWidget)self)->weditMV.xftFont;
             glyphindex = glyph_fallback;
    }
    XftGlyphExtents( dpy, fnt, &glyphindex, 1, &extents );
    specs->font = fnt;
    specs->glyph = glyphindex;
    specs->x = *xp;
    specs->y = *yp;
    *xp += extents.xOff;
    *yp += extents.yOff;
    *xOff = extents.xOff;
}
#line 466 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 466 "WeditMV.widget"
static void str_to_glyphlist(Widget self)
#else
#line 466 "WeditMV.widget"
static void str_to_glyphlist(self)Widget self;
#endif
#line 467 "WeditMV.widget"
{
    int unicode;
    int p;
    int xp,yp;
    yp = ((WeditMVWidget)self)->weditMV.xftFont->ascent;
    xp = 0;

    m_clear( ((WeditMVWidget)self)->weditMV.glyph_m );
    m_clear( ((WeditMVWidget)self)->weditMV.glyph_xoff_m );
    p=0;
    while( (unicode = m_utf8char(((WeditMVWidget)self)->weditMV.str_m, &p)) != -1 )
        {
            unicode_to_glyphspec( self, unicode, m_add(((WeditMVWidget)self)->weditMV.glyph_m), &xp, &yp,
                                  m_add(((WeditMVWidget)self)->weditMV.glyph_xoff_m) );
        }

    ((WeditMVWidget)self)->weditMV.txt.x = 0;
    ((WeditMVWidget)self)->weditMV.txt.y = 0;
    ((WeditMVWidget)self)->weditMV.txt.width  = xp;
    ((WeditMVWidget)self)->weditMV.txt.height = ((WeditMVWidget)self)->weditMV.xftFont->ascent + ((WeditMVWidget)self)->weditMV.xftFont->descent+2;

    ((WeditMVWidget)self)->weditMV.dirty = 1;         /* ggf. update der bildschirmausgabe */
    ((WeditMVWidget)self)->weditMV.dirty_str = 0;     /* glyphlist ist aktualisiert */
}
#line 492 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 492 "WeditMV.widget"
static int  char_offset(Widget self,int  index)
#else
#line 492 "WeditMV.widget"
static int  char_offset(self,index)Widget self;int  index;
#endif
#line 493 "WeditMV.widget"
{
    int i,p1=0;
    for(i=0;i<index;i++)
        m_utf8char( ((WeditMVWidget)self)->weditMV.str_m, &p1 );
    return p1;
}
#line 503 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 503 "WeditMV.widget"
static void insert_char_at_cursor(Widget self,char * buf,int  len)
#else
#line 503 "WeditMV.widget"
static void insert_char_at_cursor(self,buf,len)Widget self;char * buf;int  len;
#endif
#line 504 "WeditMV.widget"
{
    int p = char_offset(self,((WeditMVWidget)self)->weditMV.crsr_pos);
    m_ins( ((WeditMVWidget)self)->weditMV.str_m, p, len );
    m_write( ((WeditMVWidget)self)->weditMV.str_m, p, buf, len );
    str_to_glyphlist(self);
    ((WeditMVWidget)self)->weditMV.dirty = 1;
}
#line 512 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 512 "WeditMV.widget"
static void remove_char_at_cursor(Widget self)
#else
#line 512 "WeditMV.widget"
static void remove_char_at_cursor(self)Widget self;
#endif
#line 513 "WeditMV.widget"
{
    int p1=0, p2=0;
    if( ((WeditMVWidget)self)->weditMV.crsr_pos >= m_len(((WeditMVWidget)self)->weditMV.glyph_m)-1 ) return;
    m_del( ((WeditMVWidget)self)->weditMV.glyph_m, ((WeditMVWidget)self)->weditMV.crsr_pos );
    m_del( ((WeditMVWidget)self)->weditMV.glyph_xoff_m, ((WeditMVWidget)self)->weditMV.crsr_pos );
    p1 = char_offset(self,((WeditMVWidget)self)->weditMV.crsr_pos);
    p2=p1; m_utf8char( ((WeditMVWidget)self)->weditMV.str_m, &p2 );
    m_remove( ((WeditMVWidget)self)->weditMV.str_m, p1, p2-p1 );
    ((WeditMVWidget)self)->weditMV.dirty     = 1;
}
#line 524 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 524 "WeditMV.widget"
static char  scroll_left(Widget self)
#else
#line 524 "WeditMV.widget"
static char  scroll_left(self)Widget self;
#endif
#line 525 "WeditMV.widget"
{
    if( ((WeditMVWidget)self)->weditMV.left_char_offset < m_len(((WeditMVWidget)self)->weditMV.glyph_m)-1 ) {
        ((WeditMVWidget)self)->weditMV.left_char_offset++;
        ((WeditMVWidget)self)->weditMV.dirty = 1;
        return 0;
    }
    return -1;
}
#line 534 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 534 "WeditMV.widget"
static char  scroll_right(Widget self)
#else
#line 534 "WeditMV.widget"
static char  scroll_right(self)Widget self;
#endif
#line 535 "WeditMV.widget"
{
    if( ((WeditMVWidget)self)->weditMV.left_char_offset <= 0 ) return -1;
    ((WeditMVWidget)self)->weditMV.left_char_offset--;
    ((WeditMVWidget)self)->weditMV.dirty = 1;
    return 0;
}
#line 549 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 549 "WeditMV.widget"
static int  px_left_offset(Widget self)
#else
#line 549 "WeditMV.widget"
static int  px_left_offset(self)Widget self;
#endif
#line 550 "WeditMV.widget"
{
    return px_char(self,((WeditMVWidget)self)->weditMV.left_char_offset);
}
#line 557 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 557 "WeditMV.widget"
static int  px_char(Widget self,int  index)
#else
#line 557 "WeditMV.widget"
static int  px_char(self,index)Widget self;int  index;
#endif
#line 558 "WeditMV.widget"
{
    int x=0,i;
    for(i=0;i<index;i++)
        x+= INT(((WeditMVWidget)self)->weditMV.glyph_xoff_m, i);
    return x;
}
#line 567 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 567 "WeditMV.widget"
static int  screen_px(Widget self,int  index)
#else
#line 567 "WeditMV.widget"
static int  screen_px(self,index)Widget self;int  index;
#endif
#line 568 "WeditMV.widget"
{
    return px_char(self,index) - px_left_offset(self);
}
#line 579 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 579 "WeditMV.widget"
static void cursor_right(Widget self)
#else
#line 579 "WeditMV.widget"
static void cursor_right(self)Widget self;
#endif
#line 580 "WeditMV.widget"
{
    int xa = 0;
    if( ((WeditMVWidget)self)->weditMV.crsr_pos >= m_len( ((WeditMVWidget)self)->weditMV.glyph_m ) -1 ) return;

    ((WeditMVWidget)self)->weditMV.crsr_pos++;
    /* das zeichen unter dem cursor sollte komplett sichtbar sein */
    while(1) {
        xa = screen_px(self, ((WeditMVWidget)self)->weditMV.crsr_pos );
        xa += INT(((WeditMVWidget)self)->weditMV.glyph_xoff_m,((WeditMVWidget)self)->weditMV.crsr_pos);
        if( xa <= ((WeditMVWidget)self)->weditMV.pix.r.width ) break;
        if( scroll_left(self) ) break;
    }
}
#line 597 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 597 "WeditMV.widget"
static void cursor_left(Widget self)
#else
#line 597 "WeditMV.widget"
static void cursor_left(self)Widget self;
#endif
#line 598 "WeditMV.widget"
{
    int xa;
    if( ((WeditMVWidget)self)->weditMV.crsr_pos <= 0 ) return;

    ((WeditMVWidget)self)->weditMV.crsr_pos--;
    while(1) {
      xa = screen_px(self, ((WeditMVWidget)self)->weditMV.crsr_pos );
      if( xa >= 0 ) break;
      if( scroll_right(self) ) break;
    }
}
#line 612 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 612 "WeditMV.widget"
static void RequestSelection(Widget self,XtPointer  client,Atom * selection,Atom * type,XtPointer  value,unsigned  long * length,int * format)
#else
#line 612 "WeditMV.widget"
static void RequestSelection(self,client,selection,type,value,length,format)Widget self;XtPointer  client;Atom * selection;Atom * type;XtPointer  value;unsigned  long * length;int * format;
#endif
#line 613 "WeditMV.widget"
{
    char *s = value;
    int len = *length;
    if( is_empty(s) || len <= 0 ) return;
    insert_char_at_cursor(self,s,len);
    while( utf8char(&s) != -1 ) cursor_right(self);
    paint(self);
}
#line 627 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 627 "WeditMV.widget"
static char * get_text_buffer(Widget self)
#else
#line 627 "WeditMV.widget"
static char * get_text_buffer(self)Widget self;
#endif
#line 628 "WeditMV.widget"
{
	int l = m_len(((WeditMVWidget)self)->weditMV.str_m);
        m_write(((WeditMVWidget)self)->weditMV.label_m, 0, m_buf(((WeditMVWidget)self)->weditMV.str_m), l );
        CHAR(((WeditMVWidget)self)->weditMV.label_m, l-1)=0;
	m_setlen(((WeditMVWidget)self)->weditMV.label_m,l);
	return m_buf(((WeditMVWidget)self)->weditMV.label_m);
}
#line 638 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 638 "WeditMV.widget"
static void update_svar(Widget self)
#else
#line 638 "WeditMV.widget"
static void update_svar(self)Widget self;
#endif
#line 639 "WeditMV.widget"
{
	int *v = svar_value(((WeditMVWidget)self)->weditMV.key_svar);
	char *str = get_text_buffer(self);
	*v = append_mstring_array(*v,0, str, XtName(self),
	     NULL );
	TRACE(1, "svar: %d value=%d", ((WeditMVWidget)self)->weditMV.key_svar, *v );

}
#line 650 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 650 "WeditMV.widget"
static void update_mvar(Widget self)
#else
#line 650 "WeditMV.widget"
static void update_mvar(self)Widget self;
#endif
#line 651 "WeditMV.widget"
{
	char *str = get_text_buffer(self);
	mvar_put_string( ((WeditMVWidget)self)->weditMV.mvar, str, 0 );
	// mvar_call_callbacks( v, 0 );
}

static XtResource resources[] = {
#line 27 "WeditMV.widget"
{XtNfontName,XtCFontName,XtRString,sizeof(((WeditMVRec*)NULL)->weditMV.fontName),XtOffsetOf(WeditMVRec,weditMV.fontName),XtRString,(XtPointer)"Source Code Pro-22"},
#line 28 "WeditMV.widget"
{XtNforeground,XtCForeground,XtRPixel,sizeof(((WeditMVRec*)NULL)->weditMV.foreground),XtOffsetOf(WeditMVRec,weditMV.foreground),XtRImmediate,(XtPointer)XtDefaultForeground },
#line 29 "WeditMV.widget"
{XtNcursorColor,XtCCursorColor,XtRPixel,sizeof(((WeditMVRec*)NULL)->weditMV.cursorColor),XtOffsetOf(WeditMVRec,weditMV.cursorColor),XtRImmediate,(XtPointer)XtDefaultForeground },
#line 30 "WeditMV.widget"
{XtNlineWidth,XtCLineWidth,XtRInt,sizeof(((WeditMVRec*)NULL)->weditMV.lineWidth),XtOffsetOf(WeditMVRec,weditMV.lineWidth),XtRImmediate,(XtPointer)1 },
#line 31 "WeditMV.widget"
{XtNcornerRoundPercent,XtCCornerRoundPercent,XtRInt,sizeof(((WeditMVRec*)NULL)->weditMV.cornerRoundPercent),XtOffsetOf(WeditMVRec,weditMV.cornerRoundPercent),XtRImmediate,(XtPointer)20 },
#line 32 "WeditMV.widget"
{XtNcallback,XtCCallback,XtRCallback,sizeof(((WeditMVRec*)NULL)->weditMV.callback),XtOffsetOf(WeditMVRec,weditMV.callback),XtRImmediate,(XtPointer)NULL },
#line 34 "WeditMV.widget"
{XtNlabel,XtCLabel,XtRString,sizeof(((WeditMVRec*)NULL)->weditMV.label),XtOffsetOf(WeditMVRec,weditMV.label),XtRImmediate,(XtPointer)NULL },
#line 35 "WeditMV.widget"
{XtNtextBuffer,XtCTextBuffer,XtRQVar,sizeof(((WeditMVRec*)NULL)->weditMV.textBuffer),XtOffsetOf(WeditMVRec,weditMV.textBuffer),XtRString,(XtPointer)"defaultEditBuffer"},
#line 36 "WeditMV.widget"
{XtNsvar,XtCSvar,XtRString,sizeof(((WeditMVRec*)NULL)->weditMV.svar),XtOffsetOf(WeditMVRec,weditMV.svar),XtRString,(XtPointer)"defaultEditBuffer"},
#line 37 "WeditMV.widget"
{XtNvar5,XtCVar5,XtRString,sizeof(((WeditMVRec*)NULL)->weditMV.var5),XtOffsetOf(WeditMVRec,weditMV.var5),XtRString,(XtPointer)"defaultEditBuffer"},
#line 43 "WeditMV.widget"
{XtNonEnter,XtCOnEnter,XtRCallback,sizeof(((WeditMVRec*)NULL)->weditMV.onEnter),XtOffsetOf(WeditMVRec,weditMV.onEnter),XtRImmediate,(XtPointer)NULL },
#line 44 "WeditMV.widget"
{XtNonChanged,XtCOnChanged,XtRCallback,sizeof(((WeditMVRec*)NULL)->weditMV.onChanged),XtOffsetOf(WeditMVRec,weditMV.onChanged),XtRImmediate,(XtPointer)NULL },
};

WeditMVClassRec weditMVClassRec = {
{ /* core_class part */
/* superclass   	*/  (WidgetClass) &coreClassRec,
/* class_name   	*/  "WeditMV",
/* widget_size  	*/  sizeof(WeditMVRec),
/* class_initialize 	*/  NULL,
/* class_part_initialize*/  _resolve_inheritance,
/* class_inited 	*/  FALSE,
/* initialize   	*/  initialize,
/* initialize_hook 	*/  NULL,
/* realize      	*/  realize,
/* actions      	*/  actionsList,
/* num_actions  	*/  12,
/* resources    	*/  resources,
/* num_resources 	*/  12,
/* xrm_class    	*/  NULLQUARK,
/* compres_motion 	*/  False ,
/* compress_exposure 	*/  FALSE ,
/* compress_enterleave 	*/  False ,
/* visible_interest 	*/  False ,
/* destroy      	*/  destroy,
/* resize       	*/  resize,
/* expose       	*/  expose,
/* set_values   	*/  set_values,
/* set_values_hook 	*/  NULL,
/* set_values_almost 	*/  XtInheritSetValuesAlmost,
/* get_values+hook 	*/  get_values_hook,
/* accept_focus 	*/  accept_focus,
/* version      	*/  XtVersion,
/* callback_private 	*/  NULL,
/* tm_table      	*/  defaultTranslations,
/* query_geometry 	*/  query_geometry,
/* display_acceleator 	*/  XtInheritDisplayAccelerator,
/* extension    	*/  NULL 
},
{ /* WeditMV_class part */
/* XA_UTF8_STRING */  0 ,
},
};
WidgetClass weditMVWidgetClass = (WidgetClass) &weditMVClassRec;
/*ARGSUSED*/
#line 665 "WeditMV.widget"
static void CallOnEnter(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
	XtCallCallbackList( self, ((WeditMVWidget)self)->weditMV.onEnter, NULL );
}

/*ARGSUSED*/
#line 672 "WeditMV.widget"
static void SetKeyboardFocus(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    TRACE(2,"try to set keyboard focus");
    Widget shell, parent;

    shell = parent = self;
    while (parent) {
        if (XtIsShell(shell = parent))
            break;
        parent = XtParent(parent);
    }
    
    XtSetKeyboardFocus(shell, self);
}

/*ARGSUSED*/
#line 687 "WeditMV.widget"
static void focus_in(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
	TRACE(2, "WeditMV %s got focus", XtName(self));
	draw_cursor(self);
}

/*ARGSUSED*/
#line 693 "WeditMV.widget"
static void focus_out(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
	TRACE(2, "WeditMV %s lost focus", XtName(self));
	cursor_undraw(self);
}

/*ARGSUSED*/
#line 699 "WeditMV.widget"
static void info(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    dump(self);
}

/*ARGSUSED*/
#line 704 "WeditMV.widget"
static void backward_char(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    cursor_left(self);
    if( ((WeditMVWidget)self)->weditMV.dirty ) paint(self); else draw_cursor(self);
}

/*ARGSUSED*/
#line 710 "WeditMV.widget"
static void forward_char(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    cursor_right(self);
    if( ((WeditMVWidget)self)->weditMV.dirty ) paint(self); else draw_cursor(self);
}

/*ARGSUSED*/
#line 716 "WeditMV.widget"
static void insert_char(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    int len;
    unsigned char buf[32];
    KeySym key_sim;

    len = _XawLookupString(self,(XKeyEvent *) event, (char*)buf,sizeof buf, &key_sim );
    if (len <= 0) return;

    insert_char_at_cursor(self, (char*)buf, len );
    cursor_right(self);
    paint(self);
}

/*ARGSUSED*/
#line 730 "WeditMV.widget"
static void remove_char(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    remove_char_at_cursor(self);
    paint(self);
}

/*ARGSUSED*/
#line 736 "WeditMV.widget"
static void set_cursor(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    int x = event->xbutton.x;
    int y = event->xbutton.y;
    x -= ((WeditMVWidget)self)->weditMV.pix.r.x;
    y -= ((WeditMVWidget)self)->weditMV.pix.r.y;
    int p = ((WeditMVWidget)self)->weditMV.left_char_offset;
    int pix = 0;
    do {
        pix += INT(((WeditMVWidget)self)->weditMV.glyph_xoff_m, p);
        if( x < pix ) break;
        p++;
    } while( p < (m_len(((WeditMVWidget)self)->weditMV.glyph_xoff_m)-1) );
    ((WeditMVWidget)self)->weditMV.crsr_pos = p;
    draw_cursor(self);
}

/*ARGSUSED*/
#line 755 "WeditMV.widget"
static void insert_selection(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    XtGetSelectionValue(self, XA_PRIMARY, ((WeditMVWidgetClass)self->core.widget_class)->weditMV_class.XA_UTF8_STRING,
                        RequestSelection,
                        NULL, 0 );
}

/*ARGSUSED*/
#line 763 "WeditMV.widget"
static void notify(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
	
	XtCallCallbackList( self, ((WeditMVWidget)self)->weditMV.callback, event );
}

static void _resolve_inheritance(class)
WidgetClass class;
{
  WeditMVWidgetClass c __attribute__((unused)) = (WeditMVWidgetClass) class;
  WeditMVWidgetClass super __attribute__((unused));
  if (class == weditMVWidgetClass) return;
  super = (WeditMVWidgetClass)class->core_class.superclass;
}
#line 82 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 82 "WeditMV.widget"
static void initialize(Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 82 "WeditMV.widget"
static void initialize(request,self,args,num_args)Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 83 "WeditMV.widget"
{
  Display *dpy = XtDisplay(self);
 /*
     $xftFont = 0;
  */
 ((WeditMVWidget)self)->weditMV.draw = 0;
 // ((WeditMVWidget)self)->weditMV.xftFont = XftFontOpenName( dpy, DefaultScreen(dpy), ((WeditMVWidget)self)->weditMV.fontName );
  ((WeditMVWidget)self)->weditMV.xftFont = font_load(dpy, DefaultScreen(dpy), ((WeditMVWidget)self)->weditMV.fontName );
  int w=10,h=10;
  alloc_colors(self);
  if(! ((WeditMVWidget)self)->weditMV.label ) ((WeditMVWidget)self)->weditMV.label = "";
  ((WeditMVWidget)self)->weditMV.glyph_m = m_create( 50, sizeof(XftGlyphFontSpec) );
  ((WeditMVWidget)self)->weditMV.glyph_xoff_m = m_create( 50, sizeof(int) );
  ((WeditMVWidget)self)->weditMV.str_m  = m_create( 50, 1 );
  ((WeditMVWidget)self)->weditMV.label_m = m_create( 50, 1 );
  char *s = ((WeditMVWidget)self)->weditMV.label; 
  copy_str( self, s );
  // mv_onwrite( ((WeditMVWidget)self)->weditMV.textBuffer, (void*)do_update, self, 0 );
  TRACE(1,"%s using mvar %d", ((WeditMVWidget)self)->core.name, ((WeditMVWidget)self)->weditMV.textBuffer );

  str_to_glyphlist(self);
  if( ((WeditMVWidget)self)->core.width < w ) ((WeditMVWidget)self)->core.width = ((WeditMVWidget)self)->weditMV.txt.width;
  if( ((WeditMVWidget)self)->core.height < h) ((WeditMVWidget)self)->core.height = ((WeditMVWidget)self)->weditMV.txt.height;
  if(! ((WeditMVWidgetClass)self->core.widget_class)->weditMV_class.XA_UTF8_STRING )
      ((WeditMVWidgetClass)self->core.widget_class)->weditMV_class.XA_UTF8_STRING = XInternAtom(XtDisplay(self), "UTF8_STRING", True);

  /* svar support, with write callbacks on state change
     if the widget is redrawn the text is send to the svar
  */
  ((WeditMVWidget)self)->weditMV.key_svar = svar_lookup_str(((WeditMVWidget)self)->weditMV.svar, SVAR_MSTRING_ARRAY );
  ((WeditMVWidget)self)->weditMV.mvar = mvar_parse_string(((WeditMVWidget)self)->weditMV.var5, VAR_STRING );

}
#line 117 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 117 "WeditMV.widget"
static void destroy(Widget self)
#else
#line 117 "WeditMV.widget"
static void destroy(self)Widget self;
#endif
#line 118 "WeditMV.widget"
{
        free_colors(self);
        XftDrawDestroy( ((WeditMVWidget)self)->weditMV.draw );
        m_free(((WeditMVWidget)self)->weditMV.glyph_m);
        m_free(((WeditMVWidget)self)->weditMV.str_m);
        m_free(((WeditMVWidget)self)->weditMV.glyph_xoff_m);
        m_free(((WeditMVWidget)self)->weditMV.label_m);
}
#line 127 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 127 "WeditMV.widget"
static Boolean  set_values(Widget  old,Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 127 "WeditMV.widget"
static Boolean  set_values(old,request,self,args,num_args)Widget  old;Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 128 "WeditMV.widget"
{
    int i;
    for(i=0;i<*num_args;i++) {
        if( strcmp(args[i].name, "label" ) ==0 )
            {
                copy_str(self, ((WeditMVWidget)self)->weditMV.label );
            }
    }
    reinit(self);
    return True; /* call expose() to update widget */
}
#line 140 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 140 "WeditMV.widget"
static void get_values_hook(Widget self,ArgList  args,Cardinal * num_args)
#else
#line 140 "WeditMV.widget"
static void get_values_hook(self,args,num_args)Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 141 "WeditMV.widget"
{
    int i;
    for(i=0;i<*num_args;i++) {
        if( strcmp(args[i].name, "label" ) ==0 ) {
            *((char**)args[i].value) = get_text_buffer(self);
            return;
        }
    }
}
#line 152 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 152 "WeditMV.widget"
static void expose(Widget self,XEvent * event,Region  region)
#else
#line 152 "WeditMV.widget"
static void expose(self,event,region)Widget self;XEvent * event;Region  region;
#endif
#line 153 "WeditMV.widget"
{
  Display *dpy = XtDisplay(self);
  XClearWindow( dpy, XtWindow(self) );
  ((WeditMVWidget)self)->weditMV.crsr_on = 0; /* cursor not visible */
  paint(self);
}
#line 160 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 160 "WeditMV.widget"
static void realize(Widget self,XtValueMask * mask,XSetWindowAttributes * attributes)
#else
#line 160 "WeditMV.widget"
static void realize(self,mask,attributes)Widget self;XtValueMask * mask;XSetWindowAttributes * attributes;
#endif
#line 161 "WeditMV.widget"
{
	XtCreateWindow(self, (unsigned int) InputOutput,
        		  (Visual *) CopyFromParent, *mask, attributes);
  	resize_widget(self);
}
#line 167 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 167 "WeditMV.widget"
static void resize(Widget self)
#else
#line 167 "WeditMV.widget"
static void resize(self)Widget self;
#endif
#line 168 "WeditMV.widget"
{
    if (XtIsRealized(self)) resize_widget(self);
}
#line 172 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 172 "WeditMV.widget"
static Boolean  accept_focus(Widget self,Time * time)
#else
#line 172 "WeditMV.widget"
static Boolean  accept_focus(self,time)Widget self;Time * time;
#endif
#line 173 "WeditMV.widget"
{
	TRACE(2,"Class WeditMV: %s: ", XtName(self) );
	return True;
}
#line 179 "WeditMV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 179 "WeditMV.widget"
static XtGeometryResult  query_geometry(Widget self,XtWidgetGeometry * request,XtWidgetGeometry * reply)
#else
#line 179 "WeditMV.widget"
static XtGeometryResult  query_geometry(self,request,reply)Widget self;XtWidgetGeometry * request;XtWidgetGeometry * reply;
#endif
#line 180 "WeditMV.widget"
{
    int w,h;
    reply->request_mode = CWX | CWY | CWWidth | CWHeight;
    reply->x=0; reply->y=0;
    w = reply->width =  ((WeditMVWidget)self)->weditMV.txt.width;
    h = reply->height = ((WeditMVWidget)self)->weditMV.txt.height;
    TRACE(2, "%s: our prefered size is %dx%d", XtName(self),
                  w,h );
    return XtGeometryAlmost;
}
