#!/bin/bash

gen_header()
{
echo "/* generated by widreg.sh */"
echo "#ifndef ${OUT^^}_H"
echo "#define ${OUT^^}_H"
echo "#include <X11/IntrinsicP.h>"
echo "#include \"WcCreateP.h\""
for a in ${names[@]}
do
    echo "#include <xtcw/$a.h>"
    if ! [ -f "$INC/$a.h" ]
    then
	echo error "$INC/$a.h" 
    fi
done

echo "void widreg(XtAppContext app);"

echo "#endif"
}

gen_code()
{
echo "/* generated by widreg.sh */"
echo "#include \"$SRC/${OUT}.h\""
echo "#include \"WcCreateP.h\""

echo "void widreg(XtAppContext app) {"
for a in ${names[@]}
do
    echo "WcRegisterClassPtr(app, \"$a\", ${a,}WidgetClass );"
done
echo "}"
}


src=(*.widget)
names=(${src[@]%%.widget})
#base=(${src[@]%%.widget})
#names=(${base[@]##src/})

OUT=widreg
INC=xtcw
SRC=.

gen_header >$SRC/$OUT.h
gen_code   >$SRC/$OUT.c
