/* Generated by wbuild from "Entry.w"
** (generator version $Revision: 3.0 $ of $Date: 95/08/30 17:50:38 $)
*/
#ifndef _XfwfEntry_H_
#define _XfwfEntry_H_
#include <Xfwf/Board.h>
_XFUNCPROTOBEGIN
void  XfwfEntryClear(
#if NeedFunctionPrototypes
Widget
#endif
);
#ifndef XtNtext
#define XtNtext "text"
#endif
#ifndef XtCText
#define XtCText "Text"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNvalid
#define XtNvalid "valid"
#endif
#ifndef XtCValid
#define XtCValid "Valid"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNmax
#define XtNmax "max"
#endif
#ifndef XtCMax
#define XtCMax "Max"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNecho
#define XtNecho "echo"
#endif
#ifndef XtCEcho
#define XtCEcho "Echo"
#endif
#ifndef XtRBoolean
#define XtRBoolean "Boolean"
#endif

#ifndef XtNactivate
#define XtNactivate "activate"
#endif
#ifndef XtCActivate
#define XtCActivate "Activate"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

#ifndef XtNfont
#define XtNfont "font"
#endif
#ifndef XtCFont
#define XtCFont "Font"
#endif
#ifndef XtRFontStruct
#define XtRFontStruct "FontStruct"
#endif

#ifndef XtNforeground
#define XtNforeground "foreground"
#endif
#ifndef XtCForeground
#define XtCForeground "Foreground"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

typedef struct _XfwfEntryClassRec *XfwfEntryWidgetClass;
typedef struct _XfwfEntryRec *XfwfEntryWidget;
externalref WidgetClass xfwfEntryWidgetClass;
_XFUNCPROTOEND
#endif /*_XfwfEntry_H_*/
