const char *syntax_xt =
"Most X programs attempt to use the same names for command line options and arguments.\n"
"All applications written with the X Toolkit Intrinsics automatically accept the following options:\n"
"\n"
"-display display\n"
"	This option specifies the name of the X server to use.\n"
"\n"
"-geometry geometry\n"
"	This option specifies the initial size and location of the window.\n"
"\n"
"-bg color, -background color\n"
"	Either option specifies the color to use for the window background.\n"
"\n"
"-bd color, -bordercolor color\n"
"	Either option specifies the color to use for the window border.\n"
"\n"
"-bw number, -borderwidth number\n"
"	Either option specifies the width in pixels of the window border.\n"
"\n"
"-fg color, -foreground color\n"
"	Either option specifies the color to use for text or graphics.\n"
"\n"
"-fn font, -font font\n"
"	Either option specifies the font to use for displaying text.\n"
"\n"
"-iconic\n"
"	This option indicates that the user would prefer that the application's windows initially\n"
"        not be visible as if the windows had be immediately iconified by the user.\n"
"        Window managers may choose not to honor the application's request.\n"
"\n"
"-name\n"
"	This option specifies the name under which resources for the application should be found.\n"
"        This option is useful in shell aliases to distinguish between invocations of an application,\n"
"        without resorting to creating links to alter the executable file name.\n"
"\n"
"-rv, -reverse\n"
"	Either option indicates that the program should simulate reverse video if possible,\n"
"        often by swapping the foreground and background colors.\n"
"        Not all programs honor this or implement it correctly. It is usually only used on monochrome displays.\n"
"\n"
"+rv\n"
"	This option indicates that the program should not simulate reverse video.\n"
"        This is used to override any defaults since reverse video doesn't always work properly.\n"
"\n"
"-selectionTimeout\n"
"	This option specifies the timeout in milliseconds within which two communicating\n"
"        applications must respond to one another for a selection request.\n"
"\n"
"-synchronous\n"
"	This option indicates that requests to the X server should be sent synchronously,\n"
"        instead of asynchronously. Since Xlib normally buffers requests to the server,\n"
"        errors do not necessarily get reported immediately after they occur.\n"
"        This option turns off the buffering so that the application can be debugged.\n"
"        It should never be used with a working program.\n"
"\n"
"-title string\n"
"	This option specifies the title to be used for this window. This information is sometimes\n"
"        used by a window manager to provide some sort of header identifying the window.\n"
"\n"
"-xnllanguage language[_territory][.codeset]\n"
"	This option specifies the language, territory, and codeset for use in\n"
"        resolving resource and other filenames.\n"
"\n"
"-xrm resourcestring\n"
"	This option specifies a resource name and value to override any defaults.\n"
"        It is also very useful for setting resources that don't have explicit command line arguments.\n"
"\n"
"\n"
"*wclInitResFile <filenames>\n"
"*WclResFiles <filenames>\n"
"	List of files to be loaded into resource db.\n"
"\n"
"*wclTraceResFiles\n"
"        Trace loading of files by Wcl to stderr.\n"
"\n"
"*wcTrace\n"
"        Enable debug output to stderr.\n"
"\n"
"-ResFile <files>\n"
"-rf <files>\n"
"	List of files to be loaded into resource db. ONLY command line\n"
"\n"
"-Trace\n"
"-tr\n"
"-trtd\n"
"-trtx\n"
"-trrf\n"
"        Trace loading of files by Wcl to stderr.\n"
"\n"
"-Warnings\n"
"        Show warnings on stderr\n"
"\n"
"WclResFiles			List of files to be loaded into resource db.\n"
"WclInitResFile                  ONLY set by command line.\n"
"WclTraceResFiles		Trace loading of files by Wcl to stderr.\n"
"WclErrorDatabaseFile		File with overrides for Wcl warning messages.\n"
"WclWidgetResourceFiles          Files with widget resources not reported by\n"
"				XtGetConstraintResourceList() nor by\n"
"				XtGetResourceList(). ** not yet implemented **\n"
"WclTemplateFiles		List of files with templates.\n"
"WclTraceTemplateDef		Trace definition of templates to stderr.\n"
"WclVerboseWarnings		Some warnings are supressed normally, but this\n"
"				resource causes Wcl to act like ANSI C and\n"
"				give somewhat informative but usually annoying\n"
"				messages.\n"
"WclDynamicLibs                  List of full pathnames of libraries which\n"
"				can be named using -lName shorthand in\n"
"				WcDynamicAction(), WcDynamicCallback(), and in\n"
"				the new (Wcl 2.02) callback and method syntax.\n"
"WclSlowTightNames		Default: False.  Causes WcFullNameToWidget()\n"
"				to use the same algorithm as used by the Athena\n"
"				string-to-widget converter for widget names\n"
"				starting with '*' - specifically, the reference\n"
"				widget is moved up in the widget tree, parent\n"
"				by parent, with a call to XtNameToWidget()\n"
"				at each parent, until the top of the tree is\n"
"				reached.  This is slower than the default\n"
"				algorithm which tries the reference widget,\n"
"				then the root of the widget tree containing\n"
"				the reference widget.\n"
"WclAppClassName                 If non-null, then this name will be used as\n"
"				the class name for all widgets created using\n"
"				WcCreateRoot().\n"
;
