/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_WLISTSCROLL_H
#define XTCW_WLISTSCROLL_H
#include <xtcw/Gridbox.h>
_XFUNCPROTOBEGIN
#ifndef XtNslwidth
#define XtNslwidth "slwidth"
#endif
#ifndef XtCSlwidth
#define XtCSlwidth "Slwidth"
#endif
#ifndef XtRDistance
#define XtRDistance "Distance"
#endif

#ifndef XtNlines
#define XtNlines "lines"
#endif
#ifndef XtCLines
#define XtCLines "Lines"
#endif
#ifndef XtRStringMArray
#define XtRStringMArray "StringMArray"
#endif

typedef struct _WlistScrollClassRec *WlistScrollWidgetClass;
typedef struct _WlistScrollRec *WlistScrollWidget;
externalref WidgetClass wlistScrollWidgetClass;
_XFUNCPROTOEND
#endif /* XTCW_WLISTSCROLL_H */
