/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_WLS_H
#define XTCW_WLS_H
#include <xtcw/Gridbox.h>
_XFUNCPROTOBEGIN
#ifndef XtNlst
#define XtNlst "lst"
#endif
#ifndef XtCLst
#define XtCLst "Lst"
#endif
#ifndef XtRStringMArray
#define XtRStringMArray "StringMArray"
#endif

#ifndef XtNsvar
#define XtNsvar "svar"
#endif
#ifndef XtCSvar
#define XtCSvar "Svar"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNvalue
#define XtNvalue "value"
#endif
#ifndef XtCValue
#define XtCValue "Value"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNcallback
#define XtNcallback "callback"
#endif
#ifndef XtCCallback
#define XtCCallback "Callback"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

#ifndef XtNforced_width
#define XtNforced_width "forced_width"
#endif
#ifndef XtCForced_width
#define XtCForced_width "Forced_width"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNforced_height
#define XtNforced_height "forced_height"
#endif
#ifndef XtCForced_height
#define XtCForced_height "Forced_height"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

typedef struct _WlsClassRec *WlsWidgetClass;
typedef struct _WlsRec *WlsWidget;
externalref WidgetClass wlsWidgetClass;
_XFUNCPROTOEND
#endif /* XTCW_WLS_H */
