/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_WOPTIONP_H
#define XTCW_WOPTIONP_H
#include <xtcw/WlabelP.h>
#include <xtcw/Woption.h>
_XFUNCPROTOBEGIN

typedef struct {
/* methods */
/* class variables */
int dummy;
} WoptionClassPart;

typedef struct _WoptionClassRec {
CoreClassPart core_class;
WheelClassPart wheel_class;
WlabelClassPart wlabel_class;
WoptionClassPart woption_class;
} WoptionClassRec;

typedef struct {
/* resources */
String  group;
String  value;
String  var5;
int  act;
/* private state */
int  key_group;
int  key_svar;
} WoptionPart;

typedef struct _WoptionRec {
CorePart core;
WheelPart wheel;
WlabelPart wlabel;
WoptionPart woption;
} WoptionRec;

externalref WoptionClassRec woptionClassRec;

_XFUNCPROTOEND
#endif /* XTCW_WOPTIONP_H */
