/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_WSQLCOMBO_H
#define XTCW_WSQLCOMBO_H
#include <xtcw/Wcombo.h>
_XFUNCPROTOBEGIN
#ifndef XtNsqlcombo_cb
#define XtNsqlcombo_cb "sqlcombo_cb"
#endif
#ifndef XtCSqlcombo_cb
#define XtCSqlcombo_cb "Sqlcombo_cb"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

#ifndef XtNsql_query_str
#define XtNsql_query_str "sql_query_str"
#endif
#ifndef XtCSql_query_str
#define XtCSql_query_str "Sql_query_str"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNsql_disp_field
#define XtNsql_disp_field "sql_disp_field"
#endif
#ifndef XtCSql_disp_field
#define XtCSql_disp_field "Sql_disp_field"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNsql_key_field
#define XtNsql_key_field "sql_key_field"
#endif
#ifndef XtCSql_key_field
#define XtCSql_key_field "Sql_key_field"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNsql_result
#define XtNsql_result "sql_result"
#endif
#ifndef XtCSql_result
#define XtCSql_result "Sql_result"
#endif
#ifndef XtRArrayChar
#define XtRArrayChar "ArrayChar"
#endif

#ifndef XtNsql_host
#define XtNsql_host "sql_host"
#endif
#ifndef XtCSql_host
#define XtCSql_host "Sql_host"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNsql_user
#define XtNsql_user "sql_user"
#endif
#ifndef XtCSql_user
#define XtCSql_user "Sql_user"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNsql_pwd
#define XtNsql_pwd "sql_pwd"
#endif
#ifndef XtCSql_pwd
#define XtCSql_pwd "Sql_pwd"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNsql_db
#define XtNsql_db "sql_db"
#endif
#ifndef XtCSql_db
#define XtCSql_db "Sql_db"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

typedef struct _WsqlcomboClassRec *WsqlcomboWidgetClass;
typedef struct _WsqlcomboRec *WsqlcomboWidget;
externalref WidgetClass wsqlcomboWidgetClass;
_XFUNCPROTOEND
#endif /* XTCW_WSQLCOMBO_H */
