/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_WSWITCHP_H
#define XTCW_WSWITCHP_H
#include <xtcw/WlabelP.h>
#include <xtcw/Wswitch.h>
_XFUNCPROTOBEGIN

typedef struct {
/* methods */
/* class variables */
int dummy;
} WswitchClassPart;

typedef struct _WswitchClassRec {
CoreClassPart core_class;
WheelClassPart wheel_class;
WlabelClassPart wlabel_class;
WswitchClassPart wswitch_class;
} WswitchClassRec;

typedef struct {
/* resources */
String  value_off;
String  value_on;
String  label_off;
String  label_on;
Distance  sizex;
int  key_svar;
int  act;
/* private state */
} WswitchPart;

typedef struct _WswitchRec {
CorePart core;
WheelPart wheel;
WlabelPart wlabel;
WswitchPart wswitch;
} WswitchRec;

externalref WswitchClassRec wswitchClassRec;

_XFUNCPROTOEND
#endif /* XTCW_WSWITCHP_H */
