/* Generated by wbuild
 * (generator version 3.3)
 */
#include <X11/IntrinsicP.h>
#include <X11/StringDefs.h>
#line 116 "SelectReq.widget"
#include <X11/Xatom.h>
#line 117 "SelectReq.widget"
#include <X11/Xft/Xft.h>
#line 118 "SelectReq.widget"
#include "converters-xft.h"
#line 119 "SelectReq.widget"
#include <X11/Xmu/Converters.h>
#line 120 "SelectReq.widget"
#include "xtcw/Wlabel.h"
#line 121 "SelectReq.widget"
#include "xtcw/Wlist4.h"
#line 122 "SelectReq.widget"
#include "xtcw/Wbutton.h"
#line 123 "SelectReq.widget"
#include "mls.h"
#line 124 "SelectReq.widget"
#include "xutil.h"
#include <xtcw/SelectReqP.h>
static void _resolve_inheritance(
#if NeedFunctionPrototypes
WidgetClass
#endif
);
#line 16 "SelectReq.widget"
static void initialize(
#if NeedFunctionPrototypes
Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 23 "SelectReq.widget"
static void destroy(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 38 "SelectReq.widget"
static void prepare_list(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 52 "SelectReq.widget"
static void add_widgets(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 89 "SelectReq.widget"
static void notify_cb(
#if NeedFunctionPrototypes
Widget ,Widget,void *
#endif
);
#line 101 "SelectReq.widget"
static void ok_cb(
#if NeedFunctionPrototypes
Widget ,Widget,void *
#endif
);
#line 107 "SelectReq.widget"
static void abbruch_cb(
#if NeedFunctionPrototypes
Widget ,Widget,void *
#endif
);
#line 38 "SelectReq.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 38 "SelectReq.widget"
static void prepare_list(Widget self)
#else
#line 38 "SelectReq.widget"
static void prepare_list(self)Widget self;
#endif
#line 39 "SelectReq.widget"
{
    ((SelectReqWidget)self)->selectReq.selection=-1;
    ((SelectReqWidget)self)->selectReq.extern_lines = ((SelectReqWidget)self)->selectReq.lines;
    if( ((SelectReqWidget)self)->selectReq.lines ) return;
    
    ((SelectReqWidget)self)->selectReq.lines = m_create(100,sizeof(char*));
    for(int i = 0;i<100;i++) {
	char *a;
	asprintf(&a,"%d hello world", i);
	m_put( ((SelectReqWidget)self)->selectReq.lines, &a);
    }	
}
#line 52 "SelectReq.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 52 "SelectReq.widget"
static void add_widgets(Widget self)
#else
#line 52 "SelectReq.widget"
static void add_widgets(self)Widget self;
#endif
#line 53 "SelectReq.widget"
{

	Widget w;
	w = XtVaCreateManagedWidget( "a", wbuttonWidgetClass, self,
				  "label", "Abbruch",
				  "gridy", 1,
				  "gridx", 0,
				  "fill", 1,
				  "weighty", 0,
				  NULL );
	XtAddCallback(w, "callback",(XtCallbackProc) abbruch_cb, self );
	
	w = XtVaCreateManagedWidget( "b", wbuttonWidgetClass, self,
				  "label", "OK",
				  "gridy", 1,
				  "gridx", 1,
				  "fill", 1,
  				  "weighty", 0,	
				  NULL );
	XtAddCallback(w, "callback",(XtCallbackProc) ok_cb, self );
	
	w = ((SelectReqWidget)self)->selectReq.wl = XtVaCreateManagedWidget( "c", wlist4WidgetClass, self,
				  "label", "3test",
				  "gridy", 0,
				  "gridx", 0,
				  "gridWidth", 2,
				  "tableStrs", ((SelectReqWidget)self)->selectReq.lines,
				  "height", 500,
				  "width", 500,
				  NULL );				  
        XtAddCallback(w, "notify",(XtCallbackProc) notify_cb, self );	

	TRACE(1, "line count: %d", m_len(((SelectReqWidget)self)->selectReq.lines) );
}
#line 89 "SelectReq.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 89 "SelectReq.widget"
static void notify_cb(Widget  w,Widget self,void * d)
#else
#line 89 "SelectReq.widget"
static void notify_cb(w,self,d)Widget  w;Widget self;void * d;
#endif
#line 90 "SelectReq.widget"
{
	TRACE(1,"notify");
	int lineno = (intptr_t)d;
	printf("%d %s\n", lineno, STR(((SelectReqWidget)self)->selectReq.lines,lineno) );
	if( ((SelectReqWidget)self)->selectReq.selection >= 0 )
	    wlist4_set_line_state( ((SelectReqWidget)self)->selectReq.wl, ((SelectReqWidget)self)->selectReq.selection, 0 );
	((SelectReqWidget)self)->selectReq.selection=lineno;
        wlist4_set_line_state( ((SelectReqWidget)self)->selectReq.wl, lineno, 1 );
}
#line 101 "SelectReq.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 101 "SelectReq.widget"
static void ok_cb(Widget  w,Widget self,void * d)
#else
#line 101 "SelectReq.widget"
static void ok_cb(w,self,d)Widget  w;Widget self;void * d;
#endif
#line 102 "SelectReq.widget"
{
	XtCallCallbackList( self, ((SelectReqWidget)self)->selectReq.callback, (void*)(intptr_t)((SelectReqWidget)self)->selectReq.selection );
}
#line 107 "SelectReq.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 107 "SelectReq.widget"
static void abbruch_cb(Widget  w,Widget self,void * d)
#else
#line 107 "SelectReq.widget"
static void abbruch_cb(w,self,d)Widget  w;Widget self;void * d;
#endif
#line 108 "SelectReq.widget"
{
	XtCallCallbackList( self, ((SelectReqWidget)self)->selectReq.callback, (void*)-1 );
}

static XtResource resources[] = {
#line 7 "SelectReq.widget"
{XtNlines,XtCLines,XtRInt,sizeof(((SelectReqRec*)NULL)->selectReq.lines),XtOffsetOf(SelectReqRec,selectReq.lines),XtRImmediate,(XtPointer)0 },
#line 8 "SelectReq.widget"
{XtNcallback,XtCCallback,XtRCallback,sizeof(((SelectReqRec*)NULL)->selectReq.callback),XtOffsetOf(SelectReqRec,selectReq.callback),XtRImmediate,(XtPointer)NULL },
};

SelectReqClassRec selectReqClassRec = {
{ /* core_class part */
/* superclass   	*/  (WidgetClass) &gridboxClassRec,
/* class_name   	*/  "SelectReq",
/* widget_size  	*/  sizeof(SelectReqRec),
/* class_initialize 	*/  NULL,
/* class_part_initialize*/  _resolve_inheritance,
/* class_inited 	*/  FALSE,
/* initialize   	*/  initialize,
/* initialize_hook 	*/  NULL,
/* realize      	*/  XtInheritRealize,
/* actions      	*/  NULL,
/* num_actions  	*/  0,
/* resources    	*/  resources,
/* num_resources 	*/  2,
/* xrm_class    	*/  NULLQUARK,
/* compres_motion 	*/  False ,
/* compress_exposure 	*/  TRUE ,
/* compress_enterleave 	*/  False ,
/* visible_interest 	*/  False ,
/* destroy      	*/  destroy,
/* resize       	*/  XtInheritResize,
/* expose       	*/  XtInheritExpose,
/* set_values   	*/  NULL,
/* set_values_hook 	*/  NULL,
/* set_values_almost 	*/  XtInheritSetValuesAlmost,
/* get_values+hook 	*/  NULL,
/* accept_focus 	*/  XtInheritAcceptFocus,
/* version      	*/  XtVersion,
/* callback_private 	*/  NULL,
/* tm_table      	*/  XtInheritTranslations,
/* query_geometry 	*/  XtInheritQueryGeometry,
/* display_acceleator 	*/  XtInheritDisplayAccelerator,
/* extension    	*/  NULL 
},
{ /* composite_class part */
XtInheritGeometryManager,
XtInheritChangeManaged,
XtInheritInsertChild,
XtInheritDeleteChild,
NULL
},
{ /* constraint_class part */
/* constraint_resources     */  NULL,
/* num_constraint_resources */  0,
/* constraint_size          */  sizeof(SelectReqConstraintRec),
/* constraint_initialize    */  NULL,
/* constraint_destroy       */  NULL,
/* constraint_set_values    */  NULL,
/* constraint_extension     */  NULL 
},
{ /* Gridbox_class part */
 /* dummy */  0
},
{ /* SelectReq_class part */
 /* dummy */  0
},
};
WidgetClass selectReqWidgetClass = (WidgetClass) &selectReqClassRec;
static void _resolve_inheritance(class)
WidgetClass class;
{
  SelectReqWidgetClass c __attribute__((unused)) = (SelectReqWidgetClass) class;
  SelectReqWidgetClass super __attribute__((unused));
  static CompositeClassExtensionRec extension_rec = {
    NULL, NULLQUARK, XtCompositeExtensionVersion,
    sizeof(CompositeClassExtensionRec), True};
  CompositeClassExtensionRec *ext;
  ext = (XtPointer)XtMalloc(sizeof(*ext));
  *ext = extension_rec;
  ext->next_extension = c->composite_class.extension;
  c->composite_class.extension = ext;
  if (class == selectReqWidgetClass) return;
  super = (SelectReqWidgetClass)class->core_class.superclass;
}
#line 16 "SelectReq.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 16 "SelectReq.widget"
static void initialize(Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 16 "SelectReq.widget"
static void initialize(request,self,args,num_args)Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 17 "SelectReq.widget"
{
    TRACE(1, "SelectReq: %s", ((SelectReqWidget)self)->core.name);
    prepare_list(self);
    add_widgets(self);
}
#line 23 "SelectReq.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 23 "SelectReq.widget"
static void destroy(Widget self)
#else
#line 23 "SelectReq.widget"
static void destroy(self)Widget self;
#endif
#line 24 "SelectReq.widget"
{
	if( ((SelectReqWidget)self)->selectReq.extern_lines == 0 ) {
	    m_free_strings(((SelectReqWidget)self)->selectReq.lines,0);
	    ((SelectReqWidget)self)->selectReq.lines=0;
	}
}
