/* Generated by wbuild
 * (generator version 3.3)
 */
#include <X11/IntrinsicP.h>
#include <X11/StringDefs.h>
#line 214 "Wcombo.widget"
#include "mls.h"
#line 215 "Wcombo.widget"
#include "converters.h"
#line 216 "Wcombo.widget"
#include <X11/Shell.h>
#line 217 "Wcombo.widget"
#include <X11/Xatom.h>
#line 218 "Wcombo.widget"
#include <X11/Xft/Xft.h>
#line 219 "Wcombo.widget"
#include "converters-xft.h"
#line 220 "Wcombo.widget"
#include <X11/Xmu/Converters.h>
#line 221 "Wcombo.widget"
#include <X11/Xaw/XawImP.h>
#line 222 "Wcombo.widget"
#include <X11/Xaw/XawImP.h>
#line 223 "Wcombo.widget"
#include <X11/Xft/Xft.h>
#line 224 "Wcombo.widget"
#include <X11/Xmu/Converters.h>
#line 225 "Wcombo.widget"
#include "xutil.h"
#line 226 "Wcombo.widget"
#include "xtcw/Wls.h"
#include <xtcw/WcomboP.h>
#line 138 "Wcombo.widget"
static void SetKeyboardFocus(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 154 "Wcombo.widget"
static void set_cursor(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 161 "Wcombo.widget"
static void insert_char(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 176 "Wcombo.widget"
static void remove_char(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 191 "Wcombo.widget"
static void focus_in(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 196 "Wcombo.widget"
static void focus_out(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 203 "Wcombo.widget"
static void notify(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);

static XtActionsRec actionsList[] = {
{"SetKeyboardFocus", SetKeyboardFocus},
{"set_cursor", set_cursor},
{"insert_char", insert_char},
{"remove_char", remove_char},
{"focus_in", focus_in},
{"focus_out", focus_out},
{"notify", notify},
};

static char defaultTranslations[] = "\
<Btn1Down>: set_cursor() SetKeyboardFocus() \n\
<Key>Return: notify() \n\
<Key>BackSpace: remove_char() \n\
<Key>: insert_char() \n\
<FocusIn>: focus_in() \n\
<FocusOut>: focus_out() \n\
";
static void _resolve_inheritance(
#if NeedFunctionPrototypes
WidgetClass
#endif
);
#line 39 "Wcombo.widget"
static void initialize(
#if NeedFunctionPrototypes
Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 49 "Wcombo.widget"
static void destroy(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 58 "Wcombo.widget"
static void open_popup(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 91 "Wcombo.widget"
static void update_filter(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 111 "Wcombo.widget"
static void item_selected_cb(
#if NeedFunctionPrototypes
Widget ,Widget,void *
#endif
);
#line 127 "Wcombo.widget"
static void popdown_shell_notify_client(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 58 "Wcombo.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 58 "Wcombo.widget"
static void open_popup(Widget self)
#else
#line 58 "Wcombo.widget"
static void open_popup(self)Widget self;
#endif
#line 59 "Wcombo.widget"
{
    if( ((WcomboWidget)self)->wcombo.entry_mode ) return;

    if( ! ((WcomboWidget)self)->wcombo.shell ) {
	    ((WcomboWidget)self)->wcombo.shell = XtCreatePopupShell ( "combo_shell", overrideShellWidgetClass,
                                  self, NULL, 0 );
    	    ((WcomboWidget)self)->wcombo.listbox = XtVaCreateManagedWidget ( "combo-scrollbox", wlsWidgetClass,
				       ((WcomboWidget)self)->wcombo.shell, NULL );
	    XtAddCallback(((WcomboWidget)self)->wcombo.listbox, "callback", (XtCallbackProc)item_selected_cb, self );
	    
	    XtRealizeWidget(((WcomboWidget)self)->wcombo.shell);
	    static Atom wm_delete_window;
    	    wm_delete_window = XInternAtom(XtDisplay(self), "WM_DELETE_WINDOW",
                                   False);
    	    (void) XSetWMProtocols (XtDisplay(self), XtWindow(((WcomboWidget)self)->wcombo.shell),
                            &wm_delete_window, 1);
	    
	}

	Position root_x, root_y;
	XtTranslateCoords(self, 0, ((WcomboWidget)self)->core.height + ((WcomboWidget)self)->core.border_width, &root_x, &root_y);
	XtVaSetValues(((WcomboWidget)self)->wcombo.shell, "x", (int) root_x, "y", (int) root_y, NULL );
	XtResizeWidget(((WcomboWidget)self)->wcombo.shell, ((WcomboWidget)self)->core.width, ((WcomboWidget)self)->wcombo.lines_height * ((WcomboWidget)self)->wheel.xftFont->height, 0 );
	m_clear(((WcomboWidget)self)->wcombo.filter);
	((WcomboWidget)self)->wcombo.selection=-1;
	update_filter(self);

	XtPopup(((WcomboWidget)self)->wcombo.shell, XtGrabNone);
	((WcomboWidget)self)->wcombo.entry_mode=1;
}
#line 91 "Wcombo.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 91 "Wcombo.widget"
static void update_filter(Widget self)
#else
#line 91 "Wcombo.widget"
static void update_filter(self)Widget self;
#endif
#line 92 "Wcombo.widget"
{
    fwrite( m_buf(((WcomboWidget)self)->wcombo.filter), m_len(((WcomboWidget)self)->wcombo.filter),1,stdout); putchar(10);
    m_putc(((WcomboWidget)self)->wcombo.filter,0); m_pop(((WcomboWidget)self)->wcombo.filter);
    XtVaSetValues(self, "label", m_str(((WcomboWidget)self)->wcombo.filter), NULL );

    m_clear(((WcomboWidget)self)->wcombo.f_lst); m_clear(((WcomboWidget)self)->wcombo.k_lst);
    char **sp;
    int p;
    int n = m_len(((WcomboWidget)self)->wcombo.filter);
    m_foreach(((WcomboWidget)self)->wcombo.lst,p,sp) {
	if( strncasecmp( *sp, m_str(((WcomboWidget)self)->wcombo.filter), n ) == 0 ) {
	    m_put( ((WcomboWidget)self)->wcombo.f_lst, sp ); /* filtered list */
	    m_put( ((WcomboWidget)self)->wcombo.k_lst, &p );  /* indicies */
	 }
    }

    XtVaSetValues(((WcomboWidget)self)->wcombo.listbox, "lst", ((WcomboWidget)self)->wcombo.f_lst, NULL );    
}
#line 111 "Wcombo.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 111 "Wcombo.widget"
static void item_selected_cb(Widget  dummy,Widget self,void * class_data)
#else
#line 111 "Wcombo.widget"
static void item_selected_cb(dummy,self,class_data)Widget  dummy;Widget self;void * class_data;
#endif
#line 112 "Wcombo.widget"
{
        int n = m_len(((WcomboWidget)self)->wcombo.f_lst);
	int p = (intptr_t) class_data;
    	TRACE(2,"p=%d", p);

	if( p >= 0 && p < n ) {
	    ((WcomboWidget)self)->wcombo.selection=INT(((WcomboWidget)self)->wcombo.k_lst,p );
	    TRACE(2,"Wcombo:%s - sel:%d real_sel:%d", XtName(self), p, ((WcomboWidget)self)->wcombo.selection );
	    char *s = STR( ((WcomboWidget)self)->wcombo.f_lst, p );
	    XtVaSetValues(self, "label", s, NULL );
	}
	else ((WcomboWidget)self)->wcombo.selection=-1;
	popdown_shell_notify_client(self);
}
#line 127 "Wcombo.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 127 "Wcombo.widget"
static void popdown_shell_notify_client(Widget self)
#else
#line 127 "Wcombo.widget"
static void popdown_shell_notify_client(self)Widget self;
#endif
#line 128 "Wcombo.widget"
{
	XtPopdown(((WcomboWidget)self)->wcombo.shell);
	((WcomboWidget)self)->wcombo.entry_mode=0;
	XtCallCallbackList( self, ((WcomboWidget)self)->wcombo.combo_cb, (XtPointer) (intptr_t) ((WcomboWidget)self)->wcombo.selection );
}

static XtResource resources[] = {
#line 12 "Wcombo.widget"
{XtNcombo_cb,XtCCombo_cb,XtRCallback,sizeof(((WcomboRec*)NULL)->wcombo.combo_cb),XtOffsetOf(WcomboRec,wcombo.combo_cb),XtRImmediate,(XtPointer)NULL },
#line 13 "Wcombo.widget"
{XtNlst,XtCLst,XtRStringMArray,sizeof(((WcomboRec*)NULL)->wcombo.lst),XtOffsetOf(WcomboRec,wcombo.lst),XtRString,(XtPointer)"A,B,C"},
#line 14 "Wcombo.widget"
{XtNselection,XtCSelection,XtRInt,sizeof(((WcomboRec*)NULL)->wcombo.selection),XtOffsetOf(WcomboRec,wcombo.selection),XtRImmediate,(XtPointer)-1 },
#line 15 "Wcombo.widget"
{XtNlines_height,XtCLines_height,XtRInt,sizeof(((WcomboRec*)NULL)->wcombo.lines_height),XtOffsetOf(WcomboRec,wcombo.lines_height),XtRImmediate,(XtPointer)10 },
};

WcomboClassRec wcomboClassRec = {
{ /* core_class part */
/* superclass   	*/  (WidgetClass) &wlabelClassRec,
/* class_name   	*/  "Wcombo",
/* widget_size  	*/  sizeof(WcomboRec),
/* class_initialize 	*/  NULL,
/* class_part_initialize*/  _resolve_inheritance,
/* class_inited 	*/  FALSE,
/* initialize   	*/  initialize,
/* initialize_hook 	*/  NULL,
/* realize      	*/  XtInheritRealize,
/* actions      	*/  actionsList,
/* num_actions  	*/  7,
/* resources    	*/  resources,
/* num_resources 	*/  4,
/* xrm_class    	*/  NULLQUARK,
/* compres_motion 	*/  False ,
/* compress_exposure 	*/  TRUE ,
/* compress_enterleave 	*/  False ,
/* visible_interest 	*/  False ,
/* destroy      	*/  destroy,
/* resize       	*/  XtInheritResize,
/* expose       	*/  XtInheritExpose,
/* set_values   	*/  NULL,
/* set_values_hook 	*/  NULL,
/* set_values_almost 	*/  XtInheritSetValuesAlmost,
/* get_values+hook 	*/  NULL,
/* accept_focus 	*/  XtInheritAcceptFocus,
/* version      	*/  XtVersion,
/* callback_private 	*/  NULL,
/* tm_table      	*/  defaultTranslations,
/* query_geometry 	*/  XtInheritQueryGeometry,
/* display_acceleator 	*/  XtInheritDisplayAccelerator,
/* extension    	*/  NULL 
},
{ /* Wheel_class part */
XtInherit_exec_command,
XtInherit_sig_recv,
},
{ /* Wlabel_class part */
XtInherit_cache_hit,
},
{ /* Wcombo_class part */
 /* dummy */  0
},
};
WidgetClass wcomboWidgetClass = (WidgetClass) &wcomboClassRec;
/*ARGSUSED*/
#line 138 "Wcombo.widget"
static void SetKeyboardFocus(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    TRACE(2,"try to set keyboard focus");
    Widget shell, parent;

    shell = parent = self;
    while (parent) {
        if (XtIsShell(shell = parent))
            break;
        parent = XtParent(parent);
    }
    
    XtSetKeyboardFocus(shell, self);
}

/*ARGSUSED*/
#line 154 "Wcombo.widget"
static void set_cursor(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
	if( ((WcomboWidget)self)->wcombo.entry_mode ) return;
	TRACE(2,"open");
	open_popup(self);
}

/*ARGSUSED*/
#line 161 "Wcombo.widget"
static void insert_char(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    if( ! ((WcomboWidget)self)->wcombo.entry_mode ) return;
    int len;
    unsigned char buf[32];
    KeySym key_sim;

    len = _XawLookupString(self,(XKeyEvent *) event, (char*)buf,sizeof buf, &key_sim );
    if (len <= 0) return;
    TRACE(2,"ins %d %d", *buf, len);
    m_write( ((WcomboWidget)self)->wcombo.filter, m_len(((WcomboWidget)self)->wcombo.filter), buf, len );
    update_filter(self);
    
}

/*ARGSUSED*/
#line 176 "Wcombo.widget"
static void remove_char(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
	if( ! ((WcomboWidget)self)->wcombo.entry_mode ) return;
	unsigned char ch;
	TRACE(2,"del");
	while( m_len(((WcomboWidget)self)->wcombo.filter) ) {
	   ch = *(unsigned char*)m_pop(((WcomboWidget)self)->wcombo.filter);
	   TRACE(2,"%x", ch );
	   if(  ((ch & 0xC0) != 0x80)  ) break;
	   /* loop while we see utf-8 continuation bytes */
	} 
    	update_filter(self); 

}

/*ARGSUSED*/
#line 191 "Wcombo.widget"
static void focus_in(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
	TRACE(2, "Wcombo %s got focus", XtName(self));
}

/*ARGSUSED*/
#line 196 "Wcombo.widget"
static void focus_out(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
	TRACE(2, "Wcombo %s lost focus", XtName(self));
	XtPopdown(((WcomboWidget)self)->wcombo.shell);
	((WcomboWidget)self)->wcombo.entry_mode=0;
}

/*ARGSUSED*/
#line 203 "Wcombo.widget"
static void notify(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
	TRACE(2, "Wcombo %s notify: entry_mode %d", XtName(self), ((WcomboWidget)self)->wcombo.entry_mode );
	if( ! ((WcomboWidget)self)->wcombo.entry_mode ) return;
	item_selected_cb(NULL, self, (XtPointer)0 );
	
	
}

static void _resolve_inheritance(class)
WidgetClass class;
{
  WcomboWidgetClass c __attribute__((unused)) = (WcomboWidgetClass) class;
  WcomboWidgetClass super __attribute__((unused));
  if (class == wcomboWidgetClass) return;
  super = (WcomboWidgetClass)class->core_class.superclass;
}
#line 39 "Wcombo.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 39 "Wcombo.widget"
static void initialize(Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 39 "Wcombo.widget"
static void initialize(request,self,args,num_args)Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 40 "Wcombo.widget"
{
    TRACE(2, "init %s", XtName(self) );
	((WcomboWidget)self)->wcombo.shell = 0;
	((WcomboWidget)self)->wcombo.entry_mode=0;
	((WcomboWidget)self)->wcombo.filter = m_create(200,1);
	((WcomboWidget)self)->wcombo.f_lst = m_create(100,sizeof(char*) );
	((WcomboWidget)self)->wcombo.k_lst = m_create(100,sizeof(int) );
}
#line 49 "Wcombo.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 49 "Wcombo.widget"
static void destroy(Widget self)
#else
#line 49 "Wcombo.widget"
static void destroy(self)Widget self;
#endif
#line 50 "Wcombo.widget"
{
	m_free( ((WcomboWidget)self)->wcombo.filter );
	m_free( ((WcomboWidget)self)->wcombo.f_lst  );
	m_free( ((WcomboWidget)self)->wcombo.k_lst  ); 
}
