/* Generated by wbuild
 * (generator version 3.3)
 */
#include <X11/IntrinsicP.h>
#include <X11/StringDefs.h>
#line 88 "WlistScroll.widget"
#include <X11/Xatom.h>
#line 89 "WlistScroll.widget"
#include <X11/Xft/Xft.h>
#line 90 "WlistScroll.widget"
#include "converters-xft.h"
#line 91 "WlistScroll.widget"
#include "converters.h"
#line 92 "WlistScroll.widget"
#include <X11/Xmu/Converters.h>
#line 93 "WlistScroll.widget"
#include "xtcw/Wlabel.h"
#line 94 "WlistScroll.widget"
#include "xtcw/Wlist4.h"
#line 95 "WlistScroll.widget"
#include "xtcw/Wbutton.h"
#line 96 "WlistScroll.widget"
#include "mls.h"
#line 97 "WlistScroll.widget"
#include "xutil.h"
#line 98 "WlistScroll.widget"
#include <X11/Xaw/Command.h>
#include <xtcw/WlistScrollP.h>
static void _resolve_inheritance(
#if NeedFunctionPrototypes
WidgetClass
#endif
);
#line 14 "WlistScroll.widget"
static void initialize(
#if NeedFunctionPrototypes
Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 54 "WlistScroll.widget"
static void resize(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 65 "WlistScroll.widget"
static void slider_cb(
#if NeedFunctionPrototypes
Widget ,Widget,void *
#endif
);
#line 71 "WlistScroll.widget"
static void notify_cb(
#if NeedFunctionPrototypes
Widget ,Widget,void *
#endif
);
#line 65 "WlistScroll.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 65 "WlistScroll.widget"
static void slider_cb(Widget  w,Widget self,void * d)
#else
#line 65 "WlistScroll.widget"
static void slider_cb(w,self,d)Widget  w;Widget self;void * d;
#endif
#line 66 "WlistScroll.widget"
{
	TRACE(9,"HELLO");
}
#line 71 "WlistScroll.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 71 "WlistScroll.widget"
static void notify_cb(Widget  w,Widget self,void * d)
#else
#line 71 "WlistScroll.widget"
static void notify_cb(w,self,d)Widget  w;Widget self;void * d;
#endif
#line 72 "WlistScroll.widget"
{
	TRACE(1,"notify");
	int lineno = (intptr_t)d;
	if( lineno >= m_len(((WlistScrollWidget)self)->wlistScroll.lines) ) lineno = 0;

	printf("%d %s\n", lineno, STR(((WlistScrollWidget)self)->wlistScroll.lines,lineno) );
	if( ((WlistScrollWidget)self)->wlistScroll.selection >= 0 )
	    wlist4_set_line_state( ((WlistScrollWidget)self)->wlistScroll.lb, ((WlistScrollWidget)self)->wlistScroll.selection, 0 );
	((WlistScrollWidget)self)->wlistScroll.selection=lineno;
        wlist4_set_line_state( ((WlistScrollWidget)self)->wlistScroll.lb, lineno, 1 );

  	 XtCallActionProc(((WlistScrollWidget)self)->wlistScroll.sl, "t1", NULL, NULL, 0 );
}

static XtResource resources[] = {
#line 5 "WlistScroll.widget"
{XtNslwidth,XtCSlwidth,XtRDistance,sizeof(((WlistScrollRec*)NULL)->wlistScroll.slwidth),XtOffsetOf(WlistScrollRec,wlistScroll.slwidth),XtRString,(XtPointer)"3mm"},
#line 6 "WlistScroll.widget"
{XtNlines,XtCLines,XtRStringMArray,sizeof(((WlistScrollRec*)NULL)->wlistScroll.lines),XtOffsetOf(WlistScrollRec,wlistScroll.lines),XtRString,(XtPointer)"a1,b2,c3,d4"},
};

WlistScrollClassRec wlistScrollClassRec = {
{ /* core_class part */
/* superclass   	*/  (WidgetClass) &gridboxClassRec,
/* class_name   	*/  "WlistScroll",
/* widget_size  	*/  sizeof(WlistScrollRec),
/* class_initialize 	*/  NULL,
/* class_part_initialize*/  _resolve_inheritance,
/* class_inited 	*/  FALSE,
/* initialize   	*/  initialize,
/* initialize_hook 	*/  NULL,
/* realize      	*/  XtInheritRealize,
/* actions      	*/  NULL,
/* num_actions  	*/  0,
/* resources    	*/  resources,
/* num_resources 	*/  2,
/* xrm_class    	*/  NULLQUARK,
/* compres_motion 	*/  False ,
/* compress_exposure 	*/  FALSE ,
/* compress_enterleave 	*/  False ,
/* visible_interest 	*/  False ,
/* destroy      	*/  NULL,
/* resize       	*/  resize,
/* expose       	*/  XtInheritExpose,
/* set_values   	*/  NULL,
/* set_values_hook 	*/  NULL,
/* set_values_almost 	*/  XtInheritSetValuesAlmost,
/* get_values+hook 	*/  NULL,
/* accept_focus 	*/  XtInheritAcceptFocus,
/* version      	*/  XtVersion,
/* callback_private 	*/  NULL,
/* tm_table      	*/  XtInheritTranslations,
/* query_geometry 	*/  XtInheritQueryGeometry,
/* display_acceleator 	*/  XtInheritDisplayAccelerator,
/* extension    	*/  NULL 
},
{ /* composite_class part */
XtInheritGeometryManager,
XtInheritChangeManaged,
XtInheritInsertChild,
XtInheritDeleteChild,
NULL
},
{ /* constraint_class part */
/* constraint_resources     */  NULL,
/* num_constraint_resources */  0,
/* constraint_size          */  sizeof(WlistScrollConstraintRec),
/* constraint_initialize    */  NULL,
/* constraint_destroy       */  NULL,
/* constraint_set_values    */  NULL,
/* constraint_extension     */  NULL 
},
{ /* Gridbox_class part */
 /* dummy */  0
},
{ /* WlistScroll_class part */
 /* dummy */  0
},
};
WidgetClass wlistScrollWidgetClass = (WidgetClass) &wlistScrollClassRec;
static void _resolve_inheritance(class)
WidgetClass class;
{
  WlistScrollWidgetClass c __attribute__((unused)) = (WlistScrollWidgetClass) class;
  WlistScrollWidgetClass super __attribute__((unused));
  static CompositeClassExtensionRec extension_rec = {
    NULL, NULLQUARK, XtCompositeExtensionVersion,
    sizeof(CompositeClassExtensionRec), True};
  CompositeClassExtensionRec *ext;
  ext = (XtPointer)XtMalloc(sizeof(*ext));
  *ext = extension_rec;
  ext->next_extension = c->composite_class.extension;
  c->composite_class.extension = ext;
  if (class == wlistScrollWidgetClass) return;
  super = (WlistScrollWidgetClass)class->core_class.superclass;
}
#line 14 "WlistScroll.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 14 "WlistScroll.widget"
static void initialize(Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 14 "WlistScroll.widget"
static void initialize(request,self,args,num_args)Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 15 "WlistScroll.widget"
{
	printf("Hello %d\n", trace_level);
	((WlistScrollWidget)self)->wlistScroll.sl = XtVaCreateManagedWidget( "button2", wbuttonWidgetClass, self,
                                  "gridy", 2,
                                  "gridx", 0,
                                  "fill", 2,
                                  "weighty", 1,
                                  "weightx", 0,
				  "gridWidth", 1,
				  "gridHeight", 1,
				  "width", ((WlistScrollWidget)self)->wlistScroll.slwidth,
                                  NULL );

         XtAddCallback(((WlistScrollWidget)self)->wlistScroll.sl, "callback",(XtCallbackProc)
	 slider_cb, self );

	 ((WlistScrollWidget)self)->wlistScroll.lb = XtVaCreateManagedWidget( "a", wbuttonWidgetClass, self,
                                  "gridy", 1,
                                  "gridx", 0,
                                  "fill", 3,
                                  "weighty", 1,
                                  "weightx", 1,
				  "tableStrs", ((WlistScrollWidget)self)->wlistScroll.lines,
                                  NULL );
        XtAddCallback(((WlistScrollWidget)self)->wlistScroll.lb, "notify",(XtCallbackProc) notify_cb, self );	


	 Widget w = XtVaCreateManagedWidget( "HelloWorld", wbuttonWidgetClass, self,
	 	                  "gridy", 0,
                                  "gridx", 0,
                                  "fill", 3,
                                  "weighty", 0,
                                  "weightx", 1,
                                  NULL );
				  
        XtAddCallback(w, "callback",(XtCallbackProc) slider_cb, self );	
	TRACE(1,"Init");
}
#line 54 "WlistScroll.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 54 "WlistScroll.widget"
static void resize(Widget self)
#else
#line 54 "WlistScroll.widget"
static void resize(self)Widget self;
#endif
#line 55 "WlistScroll.widget"
{
	TRACE(1,"");
}
