/* Generated by wbuild
 * (generator version 3.3)
 */
#include <X11/IntrinsicP.h>
#include <X11/StringDefs.h>
#line 167 "Wls.widget"
#include "converters.h"
#line 168 "Wls.widget"
#include "mls.h"
#line 169 "Wls.widget"
#include "xtcw/Wlist.h"
#line 170 "Wls.widget"
#include <xtcw/Wlabel.h>
#line 171 "Wls.widget"
#include "xtcw/Woptc.h"
#include <xtcw/WlsP.h>
static void _resolve_inheritance(
#if NeedFunctionPrototypes
WidgetClass
#endif
);
#line 19 "Wls.widget"
static void initialize(
#if NeedFunctionPrototypes
Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 28 "Wls.widget"
static void destroy(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 34 "Wls.widget"
static void expose(
#if NeedFunctionPrototypes
Widget,XEvent *,Region 
#endif
);
#line 40 "Wls.widget"
static Boolean  set_values(
#if NeedFunctionPrototypes
Widget ,Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 52 "Wls.widget"
static XtGeometryResult  query_geometry(
#if NeedFunctionPrototypes
Widget,XtWidgetGeometry *,XtWidgetGeometry *
#endif
);
#line 73 "Wls.widget"
static void adjust_slider_size(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 98 "Wls.widget"
static void do_layout(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 138 "Wls.widget"
static void list_select_cb(
#if NeedFunctionPrototypes
Widget ,Widget,void *
#endif
);
#line 144 "Wls.widget"
static void slider_changed_cb(
#if NeedFunctionPrototypes
Widget ,Widget,void *
#endif
);
#line 156 "Wls.widget"
static void list_changed_cb(
#if NeedFunctionPrototypes
Widget ,Widget,void *
#endif
);
#line 73 "Wls.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 73 "Wls.widget"
static void adjust_slider_size(Widget self)
#else
#line 73 "Wls.widget"
static void adjust_slider_size(self)Widget self;
#endif
#line 74 "Wls.widget"
{
	int line_max; /* anzahl zeilen */
	int list_height; /* sichtbarer bereich */
	int line_height; /* pixel zeile */
	int first_line; /* erste sichtbare zeile */
	XtVaGetValues(((WlsWidget)self)->wls.list,
		"line_max", &line_max,
		"list_height", &list_height,
		"line_height", &line_height,
		"top_y", &first_line,
		NULL );

	wls_set_slider_pos( ((WlsWidget)self)->wls.slider,
	  list_height,
	  line_max * line_height,
	  first_line
	);

	((WlsWidget)self)->wls.list_height = line_max * line_height;

	TRACE(9, "%d %d %d %d", line_max, list_height,line_height,first_line  );
}
#line 98 "Wls.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 98 "Wls.widget"
static void do_layout(Widget self)
#else
#line 98 "Wls.widget"
static void do_layout(self)Widget self;
#endif
#line 99 "Wls.widget"
{
	int act;
        Widget w;
        int i;
        char *grid = "gridx";
        for( i=0; i<((WlsWidget)self)->composite.num_children;i++ )
             XtDestroyWidget(((WlsWidget)self)->composite.children[0]);

	/* XtVaCreateManagedWidget( "combo-label",
                wlabelWidgetClass, $,
                "gridy", 1,
                "label", "hello-World",
		"gridWidth", 2,
                NULL ); */

	((WlsWidget)self)->wls.list = XtVaCreateManagedWidget( "combo-list",
                wlistWidgetClass, self,
                "gridx", 0,
                "label", "hello-World",
		"gridWidth", 1,
		"weightx", 100,
		"tableStrs", ((WlsWidget)self)->wls.lst,
		"height", 120,
                NULL );
		
	XtAddCallback(((WlsWidget)self)->wls.list, "updatecb", (XtCallbackProc)list_changed_cb, self );			    XtAddCallback(((WlsWidget)self)->wls.list, "notify", (XtCallbackProc)list_select_cb, self );

	 ((WlsWidget)self)->wls.slider=XtVaCreateManagedWidget( "combo-slider",
                woptcWidgetClass, self,
                "gridx", 1,
                "label", "h",
		"gridWidth", 1,
		"weightx", 0,
                NULL );

	XtAddCallback(((WlsWidget)self)->wls.slider, "callback", (XtCallbackProc)slider_changed_cb, self );
}
#line 138 "Wls.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 138 "Wls.widget"
static void list_select_cb(Widget  dummy,Widget self,void * class_data)
#else
#line 138 "Wls.widget"
static void list_select_cb(dummy,self,class_data)Widget  dummy;Widget self;void * class_data;
#endif
#line 139 "Wls.widget"
{
	TRACE(2,"");
	XtCallCallbackList( self, ((WlsWidget)self)->wls.callback, class_data );
}
#line 144 "Wls.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 144 "Wls.widget"
static void slider_changed_cb(Widget  sender,Widget self,void * class_data)
#else
#line 144 "Wls.widget"
static void slider_changed_cb(sender,self,class_data)Widget  sender;Widget self;void * class_data;
#endif
#line 145 "Wls.widget"
{
	if( ((WlsWidget)self)->wls.ignore_cb ) return;
	float new_pos = *(float *) class_data;
	TRACE(9, "list pos rel: %f", new_pos );

	new_pos = ((WlsWidget)self)->wls.list_height * 1.0 * new_pos;
	((WlsWidget)self)->wls.ignore_cb = 1;
	wlist_gotoxy(((WlsWidget)self)->wls.list,0, (int) new_pos );
	((WlsWidget)self)->wls.ignore_cb = 0;
}
#line 156 "Wls.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 156 "Wls.widget"
static void list_changed_cb(Widget  sender,Widget self,void * class_data)
#else
#line 156 "Wls.widget"
static void list_changed_cb(sender,self,class_data)Widget  sender;Widget self;void * class_data;
#endif
#line 157 "Wls.widget"
{
	if( ((WlsWidget)self)->wls.ignore_cb ) return;
	((WlsWidget)self)->wls.ignore_cb = 1;
	adjust_slider_size(self);
	((WlsWidget)self)->wls.ignore_cb = 0;
}

static XtResource resources[] = {
#line 5 "Wls.widget"
{XtNlst,XtCLst,XtRStringMArray,sizeof(((WlsRec*)NULL)->wls.lst),XtOffsetOf(WlsRec,wls.lst),XtRString,(XtPointer)"Hello,World,who,are,you,tell,me,you,could,speak,or,remain,silent,you,could,also,take,a,flight,to,miami"},
#line 6 "Wls.widget"
{XtNsvar,XtCSvar,XtRString,sizeof(((WlsRec*)NULL)->wls.svar),XtOffsetOf(WlsRec,wls.svar),XtRString,(XtPointer)"dummy"},
#line 7 "Wls.widget"
{XtNvalue,XtCValue,XtRString,sizeof(((WlsRec*)NULL)->wls.value),XtOffsetOf(WlsRec,wls.value),XtRString,(XtPointer)"dummy"},
#line 8 "Wls.widget"
{XtNcallback,XtCCallback,XtRCallback,sizeof(((WlsRec*)NULL)->wls.callback),XtOffsetOf(WlsRec,wls.callback),XtRImmediate,(XtPointer)NULL },
#line 9 "Wls.widget"
{XtNforced_width,XtCForced_width,XtRInt,sizeof(((WlsRec*)NULL)->wls.forced_width),XtOffsetOf(WlsRec,wls.forced_width),XtRImmediate,(XtPointer)100 },
#line 10 "Wls.widget"
{XtNforced_height,XtCForced_height,XtRInt,sizeof(((WlsRec*)NULL)->wls.forced_height),XtOffsetOf(WlsRec,wls.forced_height),XtRImmediate,(XtPointer)100 },
};

WlsClassRec wlsClassRec = {
{ /* core_class part */
/* superclass   	*/  (WidgetClass) &gridboxClassRec,
/* class_name   	*/  "Wls",
/* widget_size  	*/  sizeof(WlsRec),
/* class_initialize 	*/  NULL,
/* class_part_initialize*/  _resolve_inheritance,
/* class_inited 	*/  FALSE,
/* initialize   	*/  initialize,
/* initialize_hook 	*/  NULL,
/* realize      	*/  XtInheritRealize,
/* actions      	*/  NULL,
/* num_actions  	*/  0,
/* resources    	*/  resources,
/* num_resources 	*/  6,
/* xrm_class    	*/  NULLQUARK,
/* compres_motion 	*/  False ,
/* compress_exposure 	*/  FALSE ,
/* compress_enterleave 	*/  False ,
/* visible_interest 	*/  False ,
/* destroy      	*/  destroy,
/* resize       	*/  XtInheritResize,
/* expose       	*/  expose,
/* set_values   	*/  set_values,
/* set_values_hook 	*/  NULL,
/* set_values_almost 	*/  XtInheritSetValuesAlmost,
/* get_values+hook 	*/  NULL,
/* accept_focus 	*/  XtInheritAcceptFocus,
/* version      	*/  XtVersion,
/* callback_private 	*/  NULL,
/* tm_table      	*/  XtInheritTranslations,
/* query_geometry 	*/  query_geometry,
/* display_acceleator 	*/  XtInheritDisplayAccelerator,
/* extension    	*/  NULL 
},
{ /* composite_class part */
XtInheritGeometryManager,
XtInheritChangeManaged,
XtInheritInsertChild,
XtInheritDeleteChild,
NULL
},
{ /* constraint_class part */
/* constraint_resources     */  NULL,
/* num_constraint_resources */  0,
/* constraint_size          */  sizeof(WlsConstraintRec),
/* constraint_initialize    */  NULL,
/* constraint_destroy       */  NULL,
/* constraint_set_values    */  NULL,
/* constraint_extension     */  NULL 
},
{ /* Gridbox_class part */
 /* dummy */  0
},
{ /* Wls_class part */
 /* dummy */  0
},
};
WidgetClass wlsWidgetClass = (WidgetClass) &wlsClassRec;
static void _resolve_inheritance(class)
WidgetClass class;
{
  WlsWidgetClass c __attribute__((unused)) = (WlsWidgetClass) class;
  WlsWidgetClass super __attribute__((unused));
  static CompositeClassExtensionRec extension_rec = {
    NULL, NULLQUARK, XtCompositeExtensionVersion,
    sizeof(CompositeClassExtensionRec), True};
  CompositeClassExtensionRec *ext;
  ext = (XtPointer)XtMalloc(sizeof(*ext));
  *ext = extension_rec;
  ext->next_extension = c->composite_class.extension;
  c->composite_class.extension = ext;
  if (class == wlsWidgetClass) return;
  super = (WlsWidgetClass)class->core_class.superclass;
}
#line 19 "Wls.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 19 "Wls.widget"
static void initialize(Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 19 "Wls.widget"
static void initialize(request,self,args,num_args)Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 20 "Wls.widget"
{
	XtVaSetValues( self, "defaultDistance", 0,
	/* "borderWidth", 0, */
	NULL );
	
        do_layout(self);
}
#line 28 "Wls.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 28 "Wls.widget"
static void destroy(Widget self)
#else
#line 28 "Wls.widget"
static void destroy(self)Widget self;
#endif
#line 29 "Wls.widget"
{
	/* memleak intentionally */
	/* m_free_strings($lst,0); */
}
#line 34 "Wls.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 34 "Wls.widget"
static void expose(Widget self,XEvent * event,Region  region)
#else
#line 34 "Wls.widget"
static void expose(self,event,region)Widget self;XEvent * event;Region  region;
#endif
#line 35 "Wls.widget"
{
	adjust_slider_size(self);
	gridboxClassRec.core_class.expose(self,NULL,0);
}
#line 40 "Wls.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 40 "Wls.widget"
static Boolean  set_values(Widget  old,Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 40 "Wls.widget"
static Boolean  set_values(old,request,self,args,num_args)Widget  old;Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 41 "Wls.widget"
{
    int n = *num_args;
    int do_expose = 0;
    TRACE(2, "Wls widget %s", XtName(self) );
    while( n-- )  {
	if(strncmp( args[n].name, "lst",3 ) == 0 ) {
              XtVaSetValues( ((WlsWidget)self)->wls.list, "tableStrs", ((WlsWidget)self)->wls.lst, NULL );
        }
    }
}
#line 52 "Wls.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 52 "Wls.widget"
static XtGeometryResult  query_geometry(Widget self,XtWidgetGeometry * request,XtWidgetGeometry * reply)
#else
#line 52 "Wls.widget"
static XtGeometryResult  query_geometry(self,request,reply)Widget self;XtWidgetGeometry * request;XtWidgetGeometry * reply;
#endif
#line 53 "Wls.widget"
{
    reply->request_mode = CWX | CWY | CWWidth | CWHeight;
    reply->x=0; reply->y=0;
    reply->width  =  ((WlsWidget)self)->wls.forced_width;
    reply->height =  ((WlsWidget)self)->wls.forced_height;	

    TRACE(1, "Wls:%s: parent request is: %dx%d", XtName(self),
             request->width,
             request->width );

    TRACE(1, "Wls:%s: our prefered size is %dx%d", XtName(self),
                  ((WlsWidget)self)->wls.forced_width,
                  ((WlsWidget)self)->wls.forced_height );

    return XtGeometryAlmost;
}
