/* Generated by wbuild
 * (generator version 3.3)
 */
#include <X11/IntrinsicP.h>
#include <X11/StringDefs.h>
#line 115 "Woption.widget"
#include "opts.h"
#line 116 "Woption.widget"
#include "mls.h"
#line 117 "Woption.widget"
#include "svar2.h"
#line 118 "Woption.widget"
#include <X11/Xft/Xft.h>
#line 119 "Woption.widget"
#include "converters-xft.h"
#include <xtcw/WoptionP.h>
#line 66 "Woption.widget"
static void activate(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 74 "Woption.widget"
static void deactivate(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 82 "Woption.widget"
static void highlight(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 89 "Woption.widget"
static void reset(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 96 "Woption.widget"
static void notify(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);

static XtActionsRec actionsList[] = {
{"activate", activate},
{"deactivate", deactivate},
{"highlight", highlight},
{"reset", reset},
{"notify", notify},
};

static char defaultTranslations[] = "\
<EnterWindow>: highlight() \n\
<LeaveWindow>: reset() \n\
<BtnDown>: notify() \n\
";
static void _resolve_inheritance(
#if NeedFunctionPrototypes
WidgetClass
#endif
);
#line 30 "Woption.widget"
static void initialize(
#if NeedFunctionPrototypes
Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 45 "Woption.widget"
static int  exec_command(
#if NeedFunctionPrototypes
Widget,int ,int 
#endif
);
#line 107 "Woption.widget"
static void  init_svar_result(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 107 "Woption.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 107 "Woption.widget"
static void  init_svar_result(Widget self)
#else
#line 107 "Woption.widget"
static void  init_svar_result(self)Widget self;
#endif
#line 108 "Woption.widget"
{
	int *v = svar_value(((WoptionWidget)self)->woption.key_svar);
	*v = append_mstring_array(*v,0,
	       ((WoptionWidget)self)->woption.value, ((WoptionWidget)self)->wlabel.label, ((WoptionWidget)self)->woption.group, NULL );
}

static XtResource resources[] = {
#line 6 "Woption.widget"
{XtNgroup,XtCGroup,XtRString,sizeof(((WoptionRec*)NULL)->woption.group),XtOffsetOf(WoptionRec,woption.group),XtRString,(XtPointer)"dummy"},
#line 7 "Woption.widget"
{XtNvalue,XtCValue,XtRString,sizeof(((WoptionRec*)NULL)->woption.value),XtOffsetOf(WoptionRec,woption.value),XtRString,(XtPointer)"dummy"},
#line 8 "Woption.widget"
{XtNsvar,XtCSvar,XtRString,sizeof(((WoptionRec*)NULL)->woption.svar),XtOffsetOf(WoptionRec,woption.svar),XtRString,(XtPointer)"dummy"},
#line 9 "Woption.widget"
{XtNact,XtCAct,XtRInt,sizeof(((WoptionRec*)NULL)->woption.act),XtOffsetOf(WoptionRec,woption.act),XtRImmediate,(XtPointer)0 },
};

WoptionClassRec woptionClassRec = {
{ /* core_class part */
/* superclass   	*/  (WidgetClass) &wlabelClassRec,
/* class_name   	*/  "Woption",
/* widget_size  	*/  sizeof(WoptionRec),
/* class_initialize 	*/  NULL,
/* class_part_initialize*/  _resolve_inheritance,
/* class_inited 	*/  FALSE,
/* initialize   	*/  initialize,
/* initialize_hook 	*/  NULL,
/* realize      	*/  XtInheritRealize,
/* actions      	*/  actionsList,
/* num_actions  	*/  5,
/* resources    	*/  resources,
/* num_resources 	*/  4,
/* xrm_class    	*/  NULLQUARK,
/* compres_motion 	*/  False ,
/* compress_exposure 	*/  TRUE ,
/* compress_enterleave 	*/  False ,
/* visible_interest 	*/  False ,
/* destroy      	*/  NULL,
/* resize       	*/  XtInheritResize,
/* expose       	*/  XtInheritExpose,
/* set_values   	*/  NULL,
/* set_values_hook 	*/  NULL,
/* set_values_almost 	*/  XtInheritSetValuesAlmost,
/* get_values+hook 	*/  NULL,
/* accept_focus 	*/  XtInheritAcceptFocus,
/* version      	*/  XtVersion,
/* callback_private 	*/  NULL,
/* tm_table      	*/  defaultTranslations,
/* query_geometry 	*/  XtInheritQueryGeometry,
/* display_acceleator 	*/  XtInheritDisplayAccelerator,
/* extension    	*/  NULL 
},
{ /* Wheel_class part */
exec_command,
XtInherit_sig_recv,
},
{ /* Wlabel_class part */
XtInherit_cache_hit,
},
{ /* Woption_class part */
 /* dummy */  0
},
};
WidgetClass woptionWidgetClass = (WidgetClass) &woptionClassRec;
/*ARGSUSED*/
#line 66 "Woption.widget"
static void activate(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
	((WoptionWidget)self)->woption.act = 1;
  	/* if( $state == STATE_SELECTED ) return; */
  	((WoptionWidget)self)->wheel.state = STATE_ARMED;
  	((WoptionWidgetClass)self->core.widget_class)->core_class.expose(self,NULL,NULL);
}

/*ARGSUSED*/
#line 74 "Woption.widget"
static void deactivate(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
	((WoptionWidget)self)->woption.act = 0;
  	if( ((WoptionWidget)self)->wheel.state == STATE_SELECTED ) return;
  	((WoptionWidget)self)->wheel.state = STATE_NORMAL;
  	((WoptionWidgetClass)self->core.widget_class)->core_class.expose(self,NULL,NULL);
}

/*ARGSUSED*/
#line 82 "Woption.widget"
static void highlight(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
  if( ((WoptionWidget)self)->wheel.state == STATE_SELECTED ) return;
  ((WoptionWidget)self)->wheel.state = STATE_SELECTED;
  ((WoptionWidgetClass)self->core.widget_class)->core_class.expose(self,NULL,NULL);
}

/*ARGSUSED*/
#line 89 "Woption.widget"
static void reset(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
  if( ((WoptionWidget)self)->wheel.state == STATE_NORMAL ) return;
  ((WoptionWidget)self)->wheel.state = ((WoptionWidget)self)->woption.act ? STATE_ARMED : STATE_NORMAL;
  ((WoptionWidgetClass)self->core.widget_class)->core_class.expose(self,NULL,NULL);
}

/*ARGSUSED*/
#line 96 "Woption.widget"
static void notify(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
	change_active_widget(self,((WoptionWidget)self)->woption.key_group);
	init_svar_result(self);
	svar_write_callbacks(((WoptionWidget)self)->woption.key_svar);
	XtCallCallbackList( self, ((WoptionWidget)self)->wheel.callback, event );
}

static void _resolve_inheritance(class)
WidgetClass class;
{
  WoptionWidgetClass c __attribute__((unused)) = (WoptionWidgetClass) class;
  WoptionWidgetClass super __attribute__((unused));
  if (class == woptionWidgetClass) return;
  super = (WoptionWidgetClass)class->core_class.superclass;
}
#line 30 "Woption.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 30 "Woption.widget"
static void initialize(Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 30 "Woption.widget"
static void initialize(request,self,args,num_args)Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 31 "Woption.widget"
{
        TRACE(2,"Wbutton:%s focus group: %s", ((WoptionWidget)self)->core.name, ((WoptionWidget)self)->wheel.focus_group );
	((WoptionWidget)self)->woption.key_group = register_widget_group( self, ((WoptionWidget)self)->woption.group );	
	((WoptionWidget)self)->woption.key_svar  = svar_lookup_str(((WoptionWidget)self)->woption.svar, SVAR_MSTRING_ARRAY );

	 if( ((WoptionWidget)self)->woption.act ) {
	    TRACE(1,"Set Active: %s", XtName(self) );
	    ((WoptionWidget)self)->wheel.state = STATE_ARMED;
	    init_svar_result(self);
	    /* can be done with no widget interaction ! */
	    set_default_active_widget(self, ((WoptionWidget)self)->woption.key_group ); 
	 }
}
#line 45 "Woption.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 45 "Woption.widget"
static int  exec_command(Widget self,int  cmd,int  val)
#else
#line 45 "Woption.widget"
static int  exec_command(self,cmd,val)Widget self;int  cmd;int  val;
#endif
#line 46 "Woption.widget"
{
  Cardinal null;
  if( cmd == WHEEL_FIRE ) {
    if( ((WoptionWidget)self)->wheel.state == STATE_SELECTED ) { notify(self, NULL,NULL, &null ); return 1; }
  }
  
  return 0;
}
#line 16 "Woption.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 16 "Woption.widget"
String  woption_value(Widget self)
#else
#line 16 "Woption.widget"
String  woption_value(self)Widget self;
#endif
#line 17 "Woption.widget"
{
        return ((WoptionWidget)self)->woption.value;
}
#line 22 "Woption.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 22 "Woption.widget"
String  woption_active_value(Widget self)
#else
#line 22 "Woption.widget"
String  woption_active_value(self)Widget self;
#endif
#line 23 "Woption.widget"
{
        Widget w = get_active_widget(((WoptionWidget)self)->woption.group);
        return w ? woption_value(w) : "";
}
