/* Generated by wbuild
 * (generator version 3.3)
 */
#include <X11/IntrinsicP.h>
#include <X11/StringDefs.h>
#line 164 "Wsqlcombo.widget"
#include "mls.h"
#line 165 "Wsqlcombo.widget"
#include "m_mysql.h"
#line 166 "Wsqlcombo.widget"
#include "var5.h"
#line 167 "Wsqlcombo.widget"
#include "converters.h"
#line 168 "Wsqlcombo.widget"
#include <X11/Shell.h>
#line 169 "Wsqlcombo.widget"
#include <X11/Xatom.h>
#line 170 "Wsqlcombo.widget"
#include <X11/Xft/Xft.h>
#line 171 "Wsqlcombo.widget"
#include "converters-xft.h"
#line 172 "Wsqlcombo.widget"
#include <X11/Xmu/Converters.h>
#line 173 "Wsqlcombo.widget"
#include <X11/Xaw/XawImP.h>
#line 174 "Wsqlcombo.widget"
#include <X11/Xaw/XawImP.h>
#line 175 "Wsqlcombo.widget"
#include <X11/Xft/Xft.h>
#line 176 "Wsqlcombo.widget"
#include <X11/Xmu/Converters.h>
#line 177 "Wsqlcombo.widget"
#include "xutil.h"
#line 178 "Wsqlcombo.widget"
#include "xtcw/Wls.h"
#include <xtcw/WsqlcomboP.h>
#line 156 "Wsqlcombo.widget"
static void CallOnEnter(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);

static XtActionsRec actionsList[] = {
{"CallOnEnter", CallOnEnter},
};
static void _resolve_inheritance(
#if NeedFunctionPrototypes
WidgetClass
#endif
);
#line 23 "Wsqlcombo.widget"
static void initialize(
#if NeedFunctionPrototypes
Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 39 "Wsqlcombo.widget"
static Boolean  set_values(
#if NeedFunctionPrototypes
Widget ,Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 59 "Wsqlcombo.widget"
static void destroy(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 67 "Wsqlcombo.widget"
static void combo_cb(
#if NeedFunctionPrototypes
Widget ,Widget,void *
#endif
);
#line 84 "Wsqlcombo.widget"
static void show_translation(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 95 "Wsqlcombo.widget"
static void update_list(
#if NeedFunctionPrototypes
int ,char *,int ,int 
#endif
);
#line 108 "Wsqlcombo.widget"
static void update_listbox(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 130 "Wsqlcombo.widget"
static void sql_query(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 142 "Wsqlcombo.widget"
static int  simple_query(
#if NeedFunctionPrototypes
char *,char *,char *,char *,int ,char *
#endif
);
#line 67 "Wsqlcombo.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 67 "Wsqlcombo.widget"
static void combo_cb(Widget  dummy,Widget self,void * class_data)
#else
#line 67 "Wsqlcombo.widget"
static void combo_cb(dummy,self,class_data)Widget  dummy;Widget self;void * class_data;
#endif
#line 68 "Wsqlcombo.widget"
{
	char *key;
	intptr_t selection =   (intptr_t) class_data;

	if( selection >= 0 && selection < m_len(((WsqlcomboWidget)self)->wsqlcombo.key_lst) ) {
	    key = STR( ((WsqlcomboWidget)self)->wsqlcombo.key_lst, selection ); 
	}
	else key="";

	TRACE(2,"wsqlcombo:%s - selection %s (num:%d)", XtName(self), key, selection );
	mvar_put_string( ((WsqlcomboWidget)self)->wsqlcombo.var5_res, key, 0 );
	TRACE(1,"call callback on var#%d", ((WsqlcomboWidget)self)->wsqlcombo.var5_res );
	mvar_call_callbacks( ((WsqlcomboWidget)self)->wsqlcombo.var5_res, 0 );
	XtCallCallbackList(self, ((WsqlcomboWidget)self)->wsqlcombo.sqlcombo_cb, key );
}
#line 84 "Wsqlcombo.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 84 "Wsqlcombo.widget"
static void show_translation(Widget self)
#else
#line 84 "Wsqlcombo.widget"
static void show_translation(self)Widget self;
#endif
#line 85 "Wsqlcombo.widget"
{
	TRACE(2, "Wsqlcombo %s", XtName(self) );	    
	WsqlcomboWidgetClass wc = (WsqlcomboWidgetClass)XtClass(self);
	char *s = wc->core_class.tm_table;
	s=wcomboClassRec.core_class.tm_table;
	if(!s) s="<empty tm_table>";
	TRACE(2, "Wsqlcombo %s: Translation:%s", XtName(self),s  );	    
}
#line 95 "Wsqlcombo.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 95 "Wsqlcombo.widget"
static void update_list(int  rows,char * pattern,int  list,int  res_set)
#else
#line 95 "Wsqlcombo.widget"
static void update_list(rows,pattern,list,res_set)int  rows;char * pattern;int  list;int  res_set;
#endif
#line 96 "Wsqlcombo.widget"
{
	m_free_strings(list,1);	/* clear string list */
	str_exp_t se;	
	se_init(&se);
	se_parse(&se, pattern ); /* prepare string expand */
	for( int i=0; i<rows; i++ ) {
	     char *s = strdup( se_expand(&se, res_set,i)); /* expand string, using index i */
	     m_put( list, &s );	     
	}	
	se_free(&se);
}
#line 108 "Wsqlcombo.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 108 "Wsqlcombo.widget"
static void update_listbox(Widget self)
#else
#line 108 "Wsqlcombo.widget"
static void update_listbox(self)Widget self;
#endif
#line 109 "Wsqlcombo.widget"
{
	int default_item = 0;
	char *default_selection = "";

	int rows =  row_count(((WsqlcomboWidget)self)->wsqlcombo.sqlres);
	update_list( rows, ((WsqlcomboWidget)self)->wsqlcombo.sql_disp_field, ((WsqlcomboWidget)self)->wsqlcombo.disp_lst, ((WsqlcomboWidget)self)->wsqlcombo.sqlres );
	update_list( rows, ((WsqlcomboWidget)self)->wsqlcombo.sql_key_field, ((WsqlcomboWidget)self)->wsqlcombo.key_lst, ((WsqlcomboWidget)self)->wsqlcombo.sqlres );
	
	if( m_len(((WsqlcomboWidget)self)->wsqlcombo.disp_lst) > default_item ) {
	    default_selection = STR( ((WsqlcomboWidget)self)->wsqlcombo.disp_lst,default_item);   
	}
	
	XtVaSetValues( self,
		       "lst", ((WsqlcomboWidget)self)->wsqlcombo.disp_lst,
		       "label", default_selection, NULL );

		      
	combo_cb(0,self, (void*) default_item ); /* select item 0 */
	
}
#line 130 "Wsqlcombo.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 130 "Wsqlcombo.widget"
static void sql_query(Widget self)
#else
#line 130 "Wsqlcombo.widget"
static void sql_query(self)Widget self;
#endif
#line 131 "Wsqlcombo.widget"
{
	v_free( ((WsqlcomboWidget)self)->wsqlcombo.sqlres );
	((WsqlcomboWidget)self)->wsqlcombo.sqlres = v_init();
	simple_query(((WsqlcomboWidget)self)->wsqlcombo.sql_host, ((WsqlcomboWidget)self)->wsqlcombo.sql_db, ((WsqlcomboWidget)self)->wsqlcombo.sql_user, ((WsqlcomboWidget)self)->wsqlcombo.sql_pwd, ((WsqlcomboWidget)self)->wsqlcombo.sqlres, ((WsqlcomboWidget)self)->wsqlcombo.sql_query_str);
	if( ((WsqlcomboWidget)self)->wsqlcombo.sql_result ) {
	    ((WsqlcomboWidget)self)->wsqlcombo.var5_res = mvar_parse( ((WsqlcomboWidget)self)->wsqlcombo.sql_result, VAR_STRING );
	    m_free(((WsqlcomboWidget)self)->wsqlcombo.sql_result);
	    ((WsqlcomboWidget)self)->wsqlcombo.sql_result=0;
	}
}
#line 142 "Wsqlcombo.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 142 "Wsqlcombo.widget"
static int  simple_query(char * host,char * db,char * user,char * pwd,int  res,char * query)
#else
#line 142 "Wsqlcombo.widget"
static int  simple_query(host,db,user,pwd,res,query)char * host;char * db;char * user;char * pwd;int  res;char * query;
#endif
#line 143 "Wsqlcombo.widget"
{
  MYSQL *sql = m_mysql_connect( host, db, user, pwd );
  
  char *real_query = str_expand( res, query );
  TRACE(1, "query: %s", real_query );
  int err = m_mysql_query(sql,real_query,res);
  m_mysql_close(sql);
  return err;
}

static XtResource resources[] = {
#line 5 "Wsqlcombo.widget"
{XtNsqlcombo_cb,XtCSqlcombo_cb,XtRCallback,sizeof(((WsqlcomboRec*)NULL)->wsqlcombo.sqlcombo_cb),XtOffsetOf(WsqlcomboRec,wsqlcombo.sqlcombo_cb),XtRImmediate,(XtPointer)NULL },
#line 6 "Wsqlcombo.widget"
{XtNsql_query_str,XtCSql_query_str,XtRString,sizeof(((WsqlcomboRec*)NULL)->wsqlcombo.sql_query_str),XtOffsetOf(WsqlcomboRec,wsqlcombo.sql_query_str),XtRString,(XtPointer)"select * from users"},
#line 7 "Wsqlcombo.widget"
{XtNsql_disp_field,XtCSql_disp_field,XtRString,sizeof(((WsqlcomboRec*)NULL)->wsqlcombo.sql_disp_field),XtOffsetOf(WsqlcomboRec,wsqlcombo.sql_disp_field),XtRString,(XtPointer)"$uid - $cn"},
#line 8 "Wsqlcombo.widget"
{XtNsql_key_field,XtCSql_key_field,XtRString,sizeof(((WsqlcomboRec*)NULL)->wsqlcombo.sql_key_field),XtOffsetOf(WsqlcomboRec,wsqlcombo.sql_key_field),XtRString,(XtPointer)"$uid"},
#line 9 "Wsqlcombo.widget"
{XtNsql_result,XtCSql_result,XtRArrayChar,sizeof(((WsqlcomboRec*)NULL)->wsqlcombo.sql_result),XtOffsetOf(WsqlcomboRec,wsqlcombo.sql_result),XtRString,(XtPointer)"sql.res"},
#line 10 "Wsqlcombo.widget"
{XtNsql_host,XtCSql_host,XtRString,sizeof(((WsqlcomboRec*)NULL)->wsqlcombo.sql_host),XtOffsetOf(WsqlcomboRec,wsqlcombo.sql_host),XtRString,(XtPointer)"localhost"},
#line 11 "Wsqlcombo.widget"
{XtNsql_user,XtCSql_user,XtRString,sizeof(((WsqlcomboRec*)NULL)->wsqlcombo.sql_user),XtOffsetOf(WsqlcomboRec,wsqlcombo.sql_user),XtRString,(XtPointer)"jens"},
#line 12 "Wsqlcombo.widget"
{XtNsql_pwd,XtCSql_pwd,XtRString,sizeof(((WsqlcomboRec*)NULL)->wsqlcombo.sql_pwd),XtOffsetOf(WsqlcomboRec,wsqlcombo.sql_pwd),XtRString,(XtPointer)"linux"},
#line 13 "Wsqlcombo.widget"
{XtNsql_db,XtCSql_db,XtRString,sizeof(((WsqlcomboRec*)NULL)->wsqlcombo.sql_db),XtOffsetOf(WsqlcomboRec,wsqlcombo.sql_db),XtRString,(XtPointer)"custsrv"},
#line 14 "Wsqlcombo.widget"
{XtNonEnter,XtCOnEnter,XtRCallback,sizeof(((WsqlcomboRec*)NULL)->wsqlcombo.onEnter),XtOffsetOf(WsqlcomboRec,wsqlcombo.onEnter),XtRImmediate,(XtPointer)NULL },
};

WsqlcomboClassRec wsqlcomboClassRec = {
{ /* core_class part */
/* superclass   	*/  (WidgetClass) &wcomboClassRec,
/* class_name   	*/  "Wsqlcombo",
/* widget_size  	*/  sizeof(WsqlcomboRec),
/* class_initialize 	*/  NULL,
/* class_part_initialize*/  _resolve_inheritance,
/* class_inited 	*/  FALSE,
/* initialize   	*/  initialize,
/* initialize_hook 	*/  NULL,
/* realize      	*/  XtInheritRealize,
/* actions      	*/  actionsList,
/* num_actions  	*/  1,
/* resources    	*/  resources,
/* num_resources 	*/  10,
/* xrm_class    	*/  NULLQUARK,
/* compres_motion 	*/  False ,
/* compress_exposure 	*/  TRUE ,
/* compress_enterleave 	*/  False ,
/* visible_interest 	*/  False ,
/* destroy      	*/  destroy,
/* resize       	*/  XtInheritResize,
/* expose       	*/  XtInheritExpose,
/* set_values   	*/  set_values,
/* set_values_hook 	*/  NULL,
/* set_values_almost 	*/  XtInheritSetValuesAlmost,
/* get_values+hook 	*/  NULL,
/* accept_focus 	*/  XtInheritAcceptFocus,
/* version      	*/  XtVersion,
/* callback_private 	*/  NULL,
/* tm_table      	*/  XtInheritTranslations,
/* query_geometry 	*/  XtInheritQueryGeometry,
/* display_acceleator 	*/  XtInheritDisplayAccelerator,
/* extension    	*/  NULL 
},
{ /* Wheel_class part */
XtInherit_exec_command,
XtInherit_sig_recv,
},
{ /* Wlabel_class part */
XtInherit_cache_hit,
},
{ /* Wcombo_class part */
 /* dummy */  0
},
{ /* Wsqlcombo_class part */
 /* dummy */  0
},
};
WidgetClass wsqlcomboWidgetClass = (WidgetClass) &wsqlcomboClassRec;
/*ARGSUSED*/
#line 156 "Wsqlcombo.widget"
static void CallOnEnter(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
	TRACE(8, "onEnter in Wsqlcombo");
	XtCallCallbackList( self, ((WsqlcomboWidget)self)->wsqlcombo.onEnter, NULL );
}

static void _resolve_inheritance(class)
WidgetClass class;
{
  WsqlcomboWidgetClass c __attribute__((unused)) = (WsqlcomboWidgetClass) class;
  WsqlcomboWidgetClass super __attribute__((unused));
  if (class == wsqlcomboWidgetClass) return;
  super = (WsqlcomboWidgetClass)class->core_class.superclass;
}
#line 23 "Wsqlcombo.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 23 "Wsqlcombo.widget"
static void initialize(Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 23 "Wsqlcombo.widget"
static void initialize(request,self,args,num_args)Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 24 "Wsqlcombo.widget"
{
    TRACE(2, "Wsqlcombo %s", XtName(self) );
    ((WsqlcomboWidget)self)->wsqlcombo.var5_res=0;
    ((WsqlcomboWidget)self)->wsqlcombo.sqlres=0;
    ((WsqlcomboWidget)self)->wsqlcombo.disp_lst=m_create(10,sizeof(char*));
    ((WsqlcomboWidget)self)->wsqlcombo.key_lst=m_create(10,sizeof(char*));
    XtAddCallback( self, "combo_cb", (XtCallbackProc) combo_cb, self );
    sql_query(self);
    update_listbox(self);
}
#line 39 "Wsqlcombo.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 39 "Wsqlcombo.widget"
static Boolean  set_values(Widget  old,Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 39 "Wsqlcombo.widget"
static Boolean  set_values(old,request,self,args,num_args)Widget  old;Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 40 "Wsqlcombo.widget"
{
    static int locked = 0;
    int n = *num_args;
    int do_expose = 0;
    TRACE(2, "Wsqlcombo:%s", XtName(self) );
    if( locked ) return False;
    locked=1;
    while( n-- )  {
	if(strncmp( args[n].name, "sql_",4 ) == 0 ) {
		sql_query(self);
		update_listbox(self);
		do_expose=1;
		break;
        }
    }
    locked=0;
    return do_expose;
}
#line 59 "Wsqlcombo.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 59 "Wsqlcombo.widget"
static void destroy(Widget self)
#else
#line 59 "Wsqlcombo.widget"
static void destroy(self)Widget self;
#endif
#line 60 "Wsqlcombo.widget"
{
	v_free( ((WsqlcomboWidget)self)->wsqlcombo.sqlres );
	m_free_strings(((WsqlcomboWidget)self)->wsqlcombo.disp_lst,0);
	m_free_strings(((WsqlcomboWidget)self)->wsqlcombo.key_lst,0);
}
