/* Generated by wbuild from "Tabs.w"
** (generator version $Revision: 3.0 $ of $Date: 95/08/30 17:50:38 $)
*/
#ifndef _XfwfTabsP_H_
#define _XfwfTabsP_H_
#include <Xfwf/BoardP.h>
#include <Xfwf/Tabs.h>
_XFUNCPROTOBEGIN
typedef void (*border_highlight_Proc)(
#if NeedFunctionPrototypes
void
#endif
);
#define XtInherit_border_highlight ((border_highlight_Proc) _XtInherit)
typedef void (*border_unhighlight_Proc)(
#if NeedFunctionPrototypes
void
#endif
);
#define XtInherit_border_unhighlight ((border_unhighlight_Proc) _XtInherit)

typedef struct {
/* methods */
border_highlight_Proc border_highlight;
border_unhighlight_Proc border_unhighlight;
/* class variables */
} XfwfTabsClassPart;

typedef struct _XfwfTabsClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
XfwfCommonClassPart xfwfCommon_class;
XfwfFrameClassPart xfwfFrame_class;
XfwfBoardClassPart xfwfBoard_class;
XfwfTabsClassPart xfwfTabs_class;
} XfwfTabsClassRec;

typedef struct {
/* resources */
Pixel  foreground;
TabsOrientation  orientation;
int  lefttabs;
int  righttabs;
StringArray  labels;
int  tabWidthPercentage;
int  cornerwidth;
int  cornerheight;
int  textmargin;
Pixel  tabcolor;
XFontStruct * font;
XtCallbackList  activate;
/* private state */
GC  textgc;
GC  topgc;
GC  bottomgc;
GC  backgc;
GC  fillgc;
int * tabwidths;
int * offsets;
} XfwfTabsPart;

typedef struct _XfwfTabsRec {
CorePart core;
CompositePart composite;
XfwfCommonPart xfwfCommon;
XfwfFramePart xfwfFrame;
XfwfBoardPart xfwfBoard;
XfwfTabsPart xfwfTabs;
} XfwfTabsRec;

externalref XfwfTabsClassRec xfwfTabsClassRec;

_XFUNCPROTOEND
#endif /* _XfwfTabsP_H_ */
