'\" t
.TH "MultiListT" "1" "19 May 1992" "Version 3.0" "Free Widget Foundation"
.SH NAME
MultiListT \- Test Program For The MultiList Widget
.SH DESCRIPTION
.PP
.I MultiListT
is a simple program that creates and test a MultiList widget.  The
source may be useful is seeing how the MultiList widget can be used.  The
test program allows you to selected at most 3 items at a time.  This is done
in the test code by setting the XtNmaxSelectable resource of the MultiList
widget to 3.
.SH AUTHOR
.sp
.nf
Brian Totty, \fItotty@cs.uiuc.edu\fR
Department of Computer Science,
University of Illinois at Urbana-Champaign
1304 W. Springfield Avenue
Urbana, IL 61801
.fi
