/* Generated by wbuild from "Arrow.w"
** (generator version $Revision: 3.0 $ of $Date: 95/08/30 17:50:38 $)
*/
#ifndef _XfwfArrowP_H_
#define _XfwfArrowP_H_
#include <Xfwf/BoardP.h>
#include <Xfwf/Arrow.h>
_XFUNCPROTOBEGIN

typedef struct {
/* methods */
/* class variables */
int dummy;
} XfwfArrowClassPart;

typedef struct _XfwfArrowClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
XfwfCommonClassPart xfwfCommon_class;
XfwfFrameClassPart xfwfFrame_class;
XfwfBoardClassPart xfwfBoard_class;
XfwfArrowClassPart xfwfArrow_class;
} XfwfArrowClassRec;

typedef struct {
/* resources */
Alignment  direction;
Color  foreground;
Dimension  arrowShadow;
Cardinal  initialDelay;
Cardinal  repeatDelay;
XtCallbackList  callback;
/* private state */
GC  arrowgc;
GC  arrowlightgc;
GC  arrowdarkgc;
XtIntervalId  timer;
XPoint  p1[3];
XPoint  p2[4];
XPoint  p3[4];
XPoint  p4[4];
Dimension  a2;
Dimension  a3;
} XfwfArrowPart;

typedef struct _XfwfArrowRec {
CorePart core;
CompositePart composite;
XfwfCommonPart xfwfCommon;
XfwfFramePart xfwfFrame;
XfwfBoardPart xfwfBoard;
XfwfArrowPart xfwfArrow;
} XfwfArrowRec;

externalref XfwfArrowClassRec xfwfArrowClassRec;

_XFUNCPROTOEND
#endif /* _XfwfArrowP_H_ */
