/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_WLIST5P_H
#define XTCW_WLIST5P_H
#include <xtcw/WheelP.h>
#include <xtcw/Wlist5.h>
_XFUNCPROTOBEGIN
#define AUTO_SCROLL_TIME_MS 200 


#define PREFETCH_BUFFER 4 


#define relgc(var) do if (var ){ XtReleaseGC(self, var ); var=0; }while (0 )


typedef void (*gotoxy_Proc)(
#if NeedFunctionPrototypes
Widget,int ,int 
#endif
);
#define XtInherit_gotoxy ((gotoxy_Proc) _XtInherit)
typedef void (*make_visible_Proc)(
#if NeedFunctionPrototypes
Widget,int 
#endif
);
#define XtInherit_make_visible ((make_visible_Proc) _XtInherit)
typedef void (*update_line_Proc)(
#if NeedFunctionPrototypes
Widget,int 
#endif
);
#define XtInherit_update_line ((update_line_Proc) _XtInherit)
typedef void (*draw_line_Proc)(
#if NeedFunctionPrototypes
Widget,int 
#endif
);
#define XtInherit_draw_line ((draw_line_Proc) _XtInherit)

typedef struct {
/* methods */
gotoxy_Proc gotoxy;
make_visible_Proc make_visible;
update_line_Proc update_line;
draw_line_Proc draw_line;
/* class variables */
} Wlist5ClassPart;

typedef struct _Wlist5ClassRec {
CoreClassPart core_class;
WheelClassPart wheel_class;
Wlist5ClassPart wlist5_class;
} Wlist5ClassRec;

typedef struct {
/* resources */
int  symbolSize;
int  tableStrs;
XftColor  fg;
XtCallbackList  notify;
XtCallbackList  getEntry;
int  line_distance;
int  want_visible_y;
int  want_visible_x;
int  top_x;
int  top_y;
int  multiline;
int  line_max;
int  line_height;
int  list_height;
int  line_width;
ArrayInt  tabs;
Distance  unit;
int  line_bh;
ArrayChar  titleBar;
Pixel  titleBarCol;
/* private state */
int  key_cursor;
int  key_cursor_drawn;
int  key_cursor_state;
int  titleBarHeight;
int  titleBarWidth;
GC  gc_copy;
Pixmap  pixmap;
rect32_t  buf;
XftFont * symbols;
uint  glyph_minus;
uint  glyph_check;
uint  glyph_up;
uint  glyph_down;
int  symbols_width;
int  glyph_width;
XftDraw * draw;
XftDraw * draw_title;
Display * dpy;
int  line_state;
ulong  drag_time;
ulong  drag_update;
int  drag_line_start;
int  drag_start_y;
int  drag_last_y;
XtIntervalId  autoscroll_id;
int  pixel_to_scroll;
int  autoscroll_cnt;
int  tab_pos;
GC  titleBarGC;
int  mark;
int  cursor;
} Wlist5Part;

typedef struct _Wlist5Rec {
CorePart core;
WheelPart wheel;
Wlist5Part wlist5;
} Wlist5Rec;

externalref Wlist5ClassRec wlist5ClassRec;

_XFUNCPROTOEND
#endif /* XTCW_WLIST5P_H */
