/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_GAUGE_H
#define XTCW_GAUGE_H
#include <xtcw/Wheel.h>
_XFUNCPROTOBEGIN
#ifndef XtNlabel
#define XtNlabel "label"
#endif
#ifndef XtCLabel
#define XtCLabel "Label"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNcornerRoundPercent
#define XtNcornerRoundPercent "cornerRoundPercent"
#endif
#ifndef XtCCornerRoundPercent
#define XtCCornerRoundPercent "CornerRoundPercent"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNtimer
#define XtNtimer "timer"
#endif
#ifndef XtCTimer
#define XtCTimer "Timer"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNqpercent
#define XtNqpercent "qpercent"
#endif
#ifndef XtCQpercent
#define XtCQpercent "Qpercent"
#endif
#ifndef XtRQVar
#define XtRQVar "QVar"
#endif

#ifndef XtNgauge_width
#define XtNgauge_width "gauge_width"
#endif
#ifndef XtCGauge_width
#define XtCGauge_width "Gauge_width"
#endif
#ifndef XtRDistance
#define XtRDistance "Distance"
#endif

#ifndef XtNhh
#define XtNhh "hh"
#endif
#ifndef XtCHh
#define XtCHh "Hh"
#endif
#ifndef XtRDistance
#define XtRDistance "Distance"
#endif

#ifndef XtNpercent0
#define XtNpercent0 "percent0"
#endif
#ifndef XtCPercent0
#define XtCPercent0 "Percent0"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNpercent1
#define XtNpercent1 "percent1"
#endif
#ifndef XtCPercent1
#define XtCPercent1 "Percent1"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNcolor0
#define XtNcolor0 "color0"
#endif
#ifndef XtCColor0
#define XtCColor0 "Color0"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNcolor1
#define XtNcolor1 "color1"
#endif
#ifndef XtCColor1
#define XtCColor1 "Color1"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNcolor2
#define XtNcolor2 "color2"
#endif
#ifndef XtCColor2
#define XtCColor2 "Color2"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

typedef struct _GaugeClassRec *GaugeWidgetClass;
typedef struct _GaugeRec *GaugeWidget;
externalref WidgetClass gaugeWidgetClass;
_XFUNCPROTOEND
#endif /* XTCW_GAUGE_H */
