/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_REPEATGBP_H
#define XTCW_REPEATGBP_H
#include <xtcw/GridboxP.h>
#include <xtcw/Repeatgb.h>
_XFUNCPROTOBEGIN
typedef struct {
/* Constraint resources */
/* Private constraint variables */
int dummy;
} RepeatgbConstraintPart;

typedef struct _RepeatgbConstraintRec {
GridboxConstraintPart gridbox;
RepeatgbConstraintPart repeatgb;
} RepeatgbConstraintRec;


typedef struct {
/* methods */
/* class variables */
int dummy;
} RepeatgbClassPart;

typedef struct _RepeatgbClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
ConstraintClassPart constraint_class;
GridboxClassPart gridbox_class;
RepeatgbClassPart repeatgb_class;
} RepeatgbClassRec;

typedef struct {
/* resources */
String  sensor;
String  count;
String  args;
/* private state */
} RepeatgbPart;

typedef struct _RepeatgbRec {
CorePart core;
CompositePart composite;
ConstraintPart constraint;
GridboxPart gridbox;
RepeatgbPart repeatgb;
} RepeatgbRec;

externalref RepeatgbClassRec repeatgbClassRec;

_XFUNCPROTOEND
#endif /* XTCW_REPEATGBP_H */
