/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_REPEATGB_H
#define XTCW_REPEATGB_H
#include <xtcw/Gridbox.h>
_XFUNCPROTOBEGIN
#ifndef XtNsensor
#define XtNsensor "sensor"
#endif
#ifndef XtCSensor
#define XtCSensor "Sensor"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNcount
#define XtNcount "count"
#endif
#ifndef XtCCount
#define XtCCount "Count"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNargs
#define XtNargs "args"
#endif
#ifndef XtCArgs
#define XtCArgs "Args"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

typedef struct _RepeatgbClassRec *RepeatgbWidgetClass;
typedef struct _RepeatgbRec *RepeatgbWidget;
externalref WidgetClass repeatgbWidgetClass;
_XFUNCPROTOEND
#endif /* XTCW_REPEATGB_H */
