/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_WTEXT2P_H
#define XTCW_WTEXT2P_H
#include <xtcw/WheelP.h>
#include <xtcw/Wtext2.h>
_XFUNCPROTOBEGIN

typedef struct {
/* methods */
/* class variables */
Atom  XA_UTF8_STRING;
} Wtext2ClassPart;

typedef struct _Wtext2ClassRec {
CoreClassPart core_class;
WheelClassPart wheel_class;
Wtext2ClassPart wtext2_class;
} Wtext2ClassRec;

typedef struct {
/* resources */
String  label;
int  cornerRoundPercent;
int  timer;
/* private state */
XftDraw * draw;
Pixmap  pixmap;
GC  gc_copy;
int  prefered_width;
int  prefered_height;
XtIntervalId  tmr;
int  xl2;
int  do_init;
} Wtext2Part;

typedef struct _Wtext2Rec {
CorePart core;
WheelPart wheel;
Wtext2Part wtext2;
} Wtext2Rec;

externalref Wtext2ClassRec wtext2ClassRec;

_XFUNCPROTOEND
#endif /* XTCW_WTEXT2P_H */
