/* Generated by wbuild from "RowCol.w"
** (generator version $Revision: 2.5 $ of $Date: 94/07/29 15:31:49 $)
*/
#ifndef _RowColP_H_
#define _RowColP_H_
#include <Xm/XmP.h>

#include "XmRowCol.h"

typedef void (*layout_Proc)(
#if NeedFunctionPrototypes
Widget,int 
#endif
);
#define XtInherit_layout ((layout_Proc) _XtInherit)

typedef struct {
    /* methods */
    layout_Proc layout;

    /* class variables */

} RowColClassPart;

typedef struct _RowColClassRec {
    CoreClassPart       core_class;
    CompositeClassPart  composite_class;
    ConstraintClassPart constraint_class;
    RowColClassPart     rowCol_class;
} RowColClassRec;

typedef struct {
    /* resources */
    Boolean    storeByRow;
    int        rows;
    int        columns;
    Alignment  alignment;
    Boolean    shrinkToFit;
    XtPointer  userData;
    Dimension  spacing;

    /* private state */
    Dimension  max_width;
    Dimension  max_height;
} RowColPart;

typedef struct _RowColRec {
    CorePart       core;
    CompositePart  composite;
    ConstraintPart constraint;
    RowColPart     rowCol;
} RowColRec;


/*
 * structure attached to all children
 */

typedef struct _RowColConstraintsPart {
    /* resources */
    int position;        /* position of sub widget in array */
                         /* 0 means last. But SetValues replace to reel pos */
} RowColConstraintsPart;


typedef struct _RowColConstraintsRec {
    RowColConstraintsPart rowCol;
} RowColConstraintsRec, *RowColConstraints;


/*
 * useful macros
 */

#define RowCol_CONSTRAINTS(w) \
                   ((RowColConstraints)((w)->core.constraints))


extern RowColClassRec rowColClassRec;

#endif /* _RowColP_H_ */
