/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_CANVASP_H
#define XTCW_CANVASP_H
#include <X11/CoreP.h>
#include <xtcw/Canvas.h>
_XFUNCPROTOBEGIN
#define BG ((CanvasWidget)self)->canvas.canv.xcol 


#define FG (((CanvasWidget)self)->canvas.canv.xcol +1 )


#define DRAW ((CanvasWidget)self)->canvas.canv.xdraw 



typedef struct {
/* methods */
/* class variables */
int dummy;
} CanvasClassPart;

typedef struct _CanvasClassRec {
CoreClassPart core_class;
CanvasClassPart canvas_class;
} CanvasClassRec;

typedef struct {
/* resources */
XftFont * xftFont;
Pixel  foreground;
XtCallbackList  callback;
/* private state */
canvas_draw_t  canv;
} CanvasPart;

typedef struct _CanvasRec {
CorePart core;
CanvasPart canvas;
} CanvasRec;

externalref CanvasClassRec canvasClassRec;

_XFUNCPROTOEND
#endif /* XTCW_CANVASP_H */
