/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_HSLIDERP_H
#define XTCW_HSLIDERP_H
#include <X11/CoreP.h>
#include <xtcw/HSlider.h>
_XFUNCPROTOBEGIN
#define RES 1000000 



typedef struct {
/* methods */
/* class variables */
int dummy;
} HSliderClassPart;

typedef struct _HSliderClassRec {
CoreClassPart core_class;
HSliderClassPart hSlider_class;
} HSliderClassRec;

typedef struct {
/* resources */
Pixel  foreground;
int  lineWidth;
Boolean  filled;
uint  frac;
uint  pos;
XtCallbackList  callback;
/* private state */
GC  gc_background;
GC  gc_fg;
int  slh;
int  sly;
} HSliderPart;

typedef struct _HSliderRec {
CorePart core;
HSliderPart hSlider;
} HSliderRec;

externalref HSliderClassRec hSliderClassRec;

_XFUNCPROTOEND
#endif /* XTCW_HSLIDERP_H */
