/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_SCROLLEDCANVAS_H
#define XTCW_SCROLLEDCANVAS_H
#include <xtcw/Gridbox.h>
_XFUNCPROTOBEGIN
#ifndef XtNslwidth
#define XtNslwidth "slwidth"
#endif
#ifndef XtCSlwidth
#define XtCSlwidth "Slwidth"
#endif
#ifndef XtRDistance
#define XtRDistance "Distance"
#endif

#ifndef XtNworld_width
#define XtNworld_width "world_width"
#endif
#ifndef XtCWorld_width
#define XtCWorld_width "World_width"
#endif
#ifndef XtRUint
#define XtRUint "Uint"
#endif

#ifndef XtNworld_height
#define XtNworld_height "world_height"
#endif
#ifndef XtCWorld_height
#define XtCWorld_height "World_height"
#endif
#ifndef XtRUint
#define XtRUint "Uint"
#endif

typedef struct _ScrolledCanvasClassRec *ScrolledCanvasWidgetClass;
typedef struct _ScrolledCanvasRec *ScrolledCanvasWidget;
externalref WidgetClass scrolledCanvasWidgetClass;
_XFUNCPROTOEND
#endif /* XTCW_SCROLLEDCANVAS_H */
