/* Generated by wbuild from "SpinLabel.w"
** (generator version $Revision: 3.0 $ of $Date: 95/08/30 17:50:38 $)
*/
#ifndef _XfwfSpinLabelP_H_
#define _XfwfSpinLabelP_H_
#include <Xfwf/LabelP.h>
#include <Xfwf/SpinLabel.h>
_XFUNCPROTOBEGIN

typedef struct {
/* methods */
/* class variables */
int dummy;
} XfwfSpinLabelClassPart;

typedef struct _XfwfSpinLabelClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
XfwfCommonClassPart xfwfCommon_class;
XfwfFrameClassPart xfwfFrame_class;
XfwfBoardClassPart xfwfBoard_class;
XfwfLabelClassPart xfwfLabel_class;
XfwfSpinLabelClassPart xfwfSpinLabel_class;
} XfwfSpinLabelClassRec;

typedef struct {
/* resources */
Pixel  arrowForeground;
XtCallbackList  callback;
Dimension  labelframeWidth;
FrameType  labelframeType;
Boolean  horizontal;
/* private state */
Widget  _child[3];
} XfwfSpinLabelPart;

typedef struct _XfwfSpinLabelRec {
CorePart core;
CompositePart composite;
XfwfCommonPart xfwfCommon;
XfwfFramePart xfwfFrame;
XfwfBoardPart xfwfBoard;
XfwfLabelPart xfwfLabel;
XfwfSpinLabelPart xfwfSpinLabel;
} XfwfSpinLabelRec;

externalref XfwfSpinLabelClassRec xfwfSpinLabelClassRec;

_XFUNCPROTOEND
#endif /* _XfwfSpinLabelP_H_ */
